kubernetes-sigs/aws-ebs-csi-driver

deploy/kubernetes/attacher.yaml, deploy/kubernetes/provisioner.yaml
Fixes: #11 
Tested on my EKS cluster that example app is deployed after recreate attacher/provisioner service as headless.
=> Update example attacher and provisioner yaml file to use headless service

tests/sanity/sanity_test.go
Fix #9 
This have several benefits that:
1. Using consistent testing framework as e2e test
2. Able to define multiple test configurations per:
https://github.com/kubernetes-csi/csi-test/tree/master/pkg/sanity
3. Test results will be print to stdout as test runs as opposes to stuck
for a while and dump all results at once in the old way
Tested using `make test-sanity` and tests are passing.
=> Update santiy test to use ginkgo.

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/fakes.go, pkg/cloud/mocks/mock_ec2.go, pkg/cloud/mocks/mock_ec2metadata.go, pkg/driver/controller.go
Only with the context object populated through the call stack, the operation could be cancelled properly. This PR fixes this issue.
Fixes: #37
=> Update cloud provider interface to take in context

tests/e2e/e2e_test.go
These are the bits missing in the unfinished e2e test.
I ran this test in a loop for about 20 minutes and it didn't flake.
=> Wait for volume status in e2e test

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/mocks/mock_ec2.go
This partly reverts 760663c to prevent issue #52. This is not meant to
be the definite solution; it just buys us some time while keeping the
driver functional.
/kind bug
=> Don't pick random AZ on volume creation

Makefile, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, tests/e2e/e2e_test.go, tests/e2e/setup_test.go
Also, upsdate e2e test.
Fixes #38.
/kind feature
=> Wait for attachment state after attach/detach

pkg/cloud/cloud.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/node.go
=> Implement support for storage class parameter - fsType

deploy/kubernetes/v1.12+/node.yaml, deploy/kubernetes/v1.12+/provisioner.yaml, pkg/driver/identity.go
Did manual testing on 1.12 and able to verify that volume and pod are co-scheduled in us-east-1c while provisioner is in us-east-1a.
=> Add missing capability and clusterrole permission to enable topology awareness scheduling

pkg/cloud/cloud.go, pkg/driver/controller.go, pkg/driver/controller_test.go
Fixes: #63 
I regroup the consts to make them more readable and changed `IOPSPerGB` type from `int64` to `int` since `int` should be sufficient.
=> Implement support for storage class parameter - volume type

Dockerfile
Fixes #59.
Image size decreases considerably:
```
quay.io/bertinatto/ebs-csi-driver           testing            b73128d25c5d   2 minutes ago    30.2MB
```
=> Switch to Alpine 3.8 as base image

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go
=> Add support for creating encrypted volume

pkg/cloud/devicemanager/manager.go
* Remove setting `releaseFunc` when device is already assigned since the
same func is already set in`newBlockDevice`
* Remove unnecessary error condition in `getDevicenamesInUse`
=> Refactor `GetDevice` method.

.travis.yml
Recent go 1.11.2 release breaks the go mod hash: https://travis-ci.org/kubernetes-sigs/aws-ebs-csi-driver/jobs/450071762
Fix go patch version to 1.11.1 to resolve the build issue.
I will update go version for both docker build and travis together later.
=> Switch to use go 1.11.1 for travis

hack/verify-golint, pkg/cloud/cloud.go, pkg/cloud/devicemanager/manager.go, pkg/cloud/devicemanager/manager_test.go, pkg/cloud/fakes.go, pkg/driver/controller.go, tests/integration/integration_test.go, tests/integration/setup_test.go
Fixes: #83 
Ran integration test manual and verified that the test is passed
=> Add golint verification

deploy/kubernetes/v1.12+/node.yaml, deploy/kubernetes/v1.12+/provisioner.yaml, deploy/kubernetes/v1.12+/sample_app/storageclass.yaml, deploy/kubernetes/v1.[10,11]/node.yaml, deploy/kubernetes/v1.[10,11]/provisioner.yaml, deploy/kubernetes/v1.[10,11]/sample_app/storageclass.yaml, docs/README.md, pkg/driver/driver.go
=> Update driver name and topology key

docs/README.md, docs/example-iam-policy.json
Fixes #113 
This adds an example IAM policy with the required permissions.
I ran the integration tests (`make test-integration`) on an EC2 instance using a role that had this policy attached.
=> Add example IAM policy

pkg/driver/controller.go, pkg/driver/identity.go, pkg/driver/node.go
=> Resolve memory addresses in log messages

Makefile, cmd/main.go, pkg/driver/driver.go, pkg/driver/identity.go, pkg/driver/version.go, pkg/driver/version_test.go
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/21
This PR adds `--version` flag at the top level command.
Running `aws-ebs-csi-driver --version` will pretty print the JSON, with the same format as `kubectl version`.
This PR does not add support for printing the info in any other format. 
Locally built the image and tested:
```
➜  aws-ebs-csi-driver git:(version) ✗ docker run -it amazon/aws-ebs-csi-driver:0.1.0-alpha --version
{
"driverVersion": "0.1.0-alpha",
"gitCommit": "c7b3689df8a5cdf212ca80f9f0332ac3d518eefc",
"buildDate": "2018-12-04T18:45:21Z",
"goVersion": "go1.11.1",
"compiler": "gc",
"platform": "linux/amd64"
}
```
I am not aware of a way to …
=> Add version flag

.travis.yml, Dockerfile, docs/README.md, go.mod, go.sum, vendor/modules.txt
Bug fix
When trying to test and build locally I get:
```
➜  aws-ebs-csi-driver git:(master) make test
go test -v -race ./pkg/...
go: verifying k8s.io/kubernetes@v1.12.2: checksum mismatch
downloaded: h1:JEj2cxR+5T31U4klP5hI5dxjr6udRIHm+4dzCEPk498=
go.sum:     h1:J94sY8nziFyzMNhnbD5CiSZTo7yWytir0ia+vJuwYfc=
make: *** [test] Error 1
➜  aws-ebs-csi-driver git:(master) go version
go version go1.11.2 darwin/amd64
```
I'm not really sure why this works in CI and when running `make image`, maybe its a darwin thing 🤷‍♂️.
If I delete `mod.sum` and recreate it, the hash for `k8s.io/kubernetes` is different 
```
-k8s.io/kubernetes v1.12.2 h1:J94sY8nziFyzMNhnbD5CiSZTo7yWytir0ia+vJuwYfc=
+k8s.io/kubernetes …
```
=> Bump vendored kubernetes to v1.12.3

cmd/main.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/fakes.go, pkg/driver/node.go, tests/integration/setup_test.go, tests/sanity/sanity_test.go
1. Split `NewDriver` into two methods `NewDriver` and `NewMockDriver`.
So that one is only takes in endpoint and serves as production uses and
the other create driver with mock dependencies
2. Move controller capability, node capability and volume capability out
of driver struct since they are constant that should never change for a
specific version of driver
=> Refactor the code

pkg/driver/node.go
=> Add mountOptions support

Makefile, hack/test-integration.sh, tests/integration/README.md
Feature
make test-integration uses [aws-k8s-tester](https://github.com/aws/aws-k8s-tester/)
Ran locally
@gyuho @leakingtapan
=> Move test integration

cmd/main.go
Bug
PR https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/151 introduced an issue when `klog` replaced `glog` and the `logtostderr` flag.
Rebuilt images locally and ran E2E tests.
=> Fix klog flag init

Makefile
I do not have write access to @kschumy's repository, thus creating a one.
Bug fix
The flag needed for PULL_NUMBER for test-integration is changing. See: aws/aws-k8s-tester#31
Local
Closes: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/170.
/cc @leakingtapan
=> Change flag for PULL_NUMBER with test-integration

deploy/kubernetes/latest/sample_app/storageclass.yaml, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/fakes.go, pkg/driver/controller.go, pkg/driver/controller_test.go
Bug fix
* In the waitForVolume case "creating" incorrectly returned an error. This would then return from `cloud.CreateDisk`, causing a possible race condition. Where the function driver.CreateVolume could create another disk with the same `com.amazon.aws.csi.volume` tag. Eventually erroring with `ErrMultiDisks`. This also exposed a bug where the `AvailabilityZone` and `fsType` were not properly set. Which only surfaced when setting `--feature-gates=Topology=true`.
* Added `volumeBindingMode: WaitForFirstConsumer` in the StorageClass because since the flag `--feature-gates=Topology=true` is set and it is required for that feature.
Manual testing and new unit tests
Error …
=> Fix an error when creating a volume with topology feature gate

pkg/driver/driver.go, pkg/driver/fakes.go, pkg/driver/internal/inflight.go, pkg/driver/internal/inflight_test.go, pkg/driver/node.go
Bug fix.
If NodeStageVolume takes longer than the default [CSI timeout](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L57) to format the volume the CO can issue another request. This can lead to multiple inflight format commands against the volume and unexpected behavior.
The CSI spec requires most operations to be idempotent.
Currently, some of the requests rely on AWS API to achieve this. An example is CreateVolume. If by any chance AWS API request latency increases the CO might issue the same request that will fail. This leads the CO to send more CreateVolume requests and the possibility of creating multiple disks for the same request. (NOTE: This bug …
=> Make NodeStageVolume idempotent

pkg/driver/node.go
Bug fix
PR https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/163 introduced a bug where `NodeStageVolume` would return prematurely.
This was only evident when using HDD volumes because the formatting takes longer than the default **15** seconds, unfortunately when I tested the change for https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/163#discussion_r244741296 I only ran the sample app with a SSD and did not catch this bug :(.
When I ran the remaining e2e tests, all HDD volume tests were failing to delete EBS volumes because they were still being formatted.
Below log, shows that `NodeStageVolume: volume="vol-0504e2cf8285d7bcc" operation is already in progress` after 15 …
=> Fix NodeStageVolume returning prematurely

deploy/kubernetes/controller.yaml, deploy/kubernetes/node.yaml, deploy/kubernetes/sample_app/claim.yaml, deploy/kubernetes/sample_app/pod.yaml, deploy/kubernetes/sample_app/storageclass.yaml
/bug 
1) rename controller daemon set name and node stateful set name. This
resolves name collision when deploying multiple CSI drivers.
2) remove secrets from node ebs-plugin since it is not needed
3) update sample manifest files with better names
e2e test passed
=> Update driver manifest files

pkg/driver/controller_test.go, pkg/driver/fakes.go, pkg/driver/node_test.go, tests/sanity/sanity_test.go
Feature.
Closes #142
This PR adds unit tests for the node service. 
Changes the `NewFakeDriver` function signature to accept a FakeMounter so we can simulate volumes are mounted at certain mount points. An example using these is the proposed `"success idempotency"` test.
Unit tests added:
=> Add unit tests for node service.

Makefile, docs/README.md, hack/additional-policies.yaml, hack/feature-gates.yaml, hack/run-e2e-test, tests/e2e/README.md
/feature
Add logics to provision the cluster for prow integration. The changes include:
* Creating/Delete cluster using kops
* Building/Pushing Container image to ECR
* Generate driver manifest for testing using the ECR image
* Split e2e test into two groups, single-az e2e test and multi-az e2e test
Tested:
* `make test-e2e-single-az`
* `make test-e2e-multi-az`
/cc @gyuho @M00nF1sh
=> Update run-e2e-test script to setup cluster

pkg/driver/node.go, pkg/driver/node_test.go
Bug fix. Closes #175
`NodeUnstageVolume` doesn't check if target path was already unmounted.
We don't have unit tests for the node service so testing was done manually.
=> Check if target path is mounted before unmounting

deploy/kubernetes/controller.yaml, deploy/kubernetes/node.yaml, hack/run-e2e-test
/release
Update manifest to use 0.2.0 driver
=> Update manifest to use 0.2.0 driver

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/fakes.go, pkg/cloud/mocks/mock_ec2.go, pkg/driver/controller.go, pkg/driver/controller_test.go
This is the first version of volume snapshotting support.
It implements:
* CREATE_DELETE_SNAPSHOT capability support (i.e. no snapshot listing so far). 
* create volume from snapshot
I did only basic testing of the feature so far, but it looks to be working fine. I will add some examples and documentation of the feature.
Ref Issue #25
=> Add snapshots support

tests/e2e/testsuites/testsuites.go
Test:
```
[ebs-csi-e2e] [single-az] Dynamic Provisioning should create a deployment object, write and read to it, delete the pod and write and read to it again
```
bug fix
Waif for pod to be actually deleted before checking if the replacement pod is running.
Test snipped from a failed test:
```
STEP: deleting the pod for deployment
Feb  7 17:46:15.467: INFO: Deleting pod "ebs-volume-tester-rp8kv-58f768d56f-fvwx5" in namespace "e2e-tests-ebs-zm5g2"
STEP: checking again that the pod is running
STEP: checking pod exec
Feb  7 17:46:15.822: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/Users/dkoshkin/.kube/config exec ebs-volume-tester-rp8kv-58f768d56f-fvwx5 --namespace=e2e-tests-ebs-zm5g2 -- cat …
```
=> Fix race condition in DynamicallyProvisionedDeletePodTest

docs/README.md
/bug
Also did minor changes to the readme
=> Fix link in readme

pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/internal/inflight_test.go, pkg/driver/node.go, pkg/driver/node_test.go
/maintenance 
Create constants for keys used in map lookup
=> Create constants for keys used in map lookup

deploy/kubernetes/controller.yaml
Bugfix
Inconsistent use of mounts for csi.sock socket file
Basic smoke testing on K8S cluster on AWS
=> Use same mount to place in the csi.sock, remove obsolete volumes

pkg/cloud/cloud.go, pkg/driver/controller.go
This patch changes the way the snapshots are being created: Originally the driver waited for the snapshot to complete. This is wrong since the snapshot creation may take a really long time. Also the gRPC would most likely timeout (the call is meant to be blocking) and cause all kinds of other problems.
Now the driver retruns the snapshot as soon as it appears in EC2 with ReadyToUse state in `false` and updates the state accordingly when the controller calls the SnapshotCreate again with the same parameters.
=> Don't wait for the snapshot to be completed

deploy/kubernetes/controller.yaml, docs/README.md, examples/kubernetes/snapshot/README.md, examples/kubernetes/snapshot/claim.yaml, examples/kubernetes/snapshot/pod.yaml, examples/kubernetes/snapshot/restore-claim.yaml, examples/kubernetes/snapshot/snapshot.yaml, examples/kubernetes/snapshot/snapshotclass.yaml, examples/kubernetes/snapshot/storageclass.yaml
Added external snapshotter to the controller yaml, updated readme and deployment example.
=> Add snapshot examples

pkg/driver/node.go, pkg/driver/node_test.go
Ref: #101 
To reach feature parity for in-tree ebs plugin and to support CSI migration, adding support for raw block volume
Manually tested using:
**pvc**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: block-pvc
spec:
accessModes:
- ReadWriteOnce
volumeMode: Block
storageClassName: ebs-sc
resources:
requests:
storage: 10Gi
```
**pod**
```
apiVersion: v1
kind: Pod
metadata:
name: pod-with-block-volume
spec:
containers:
- name: fc-container
image: fedora:26
command: ["/bin/sh", "-c"]
args: [ "tail -f /dev/null" ]
volumeDevices:
- name: data
devicePath: /dev/xvda
volumes:
- name: data
persistentVolumeClaim:
claimName: block-pvc
```
verified the device is …
=> Implement raw block volume support

pkg/driver/controller_test.go, pkg/driver/fakes.go, pkg/driver/node_test.go, tests/sanity/sanity_test.go
Increases test coverage. 
Increases test coverage.
Closes #199 
Add unit tests for ControllerPublish and ControllerUnpublish requests.
=> Add unit tests for ControllerPublish and ControllerUnpublish requests

tests/e2e/suite_test.go
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/182
Fallback to `$HOME/.kube/config` if `$KUBECONFIG` is not set.
```
➜  aws-ebs-csi-driver git:(master) ✗ unset KUBECONFIG
➜  aws-ebs-csi-driver git:(dkoshkin/block-volume-e2e) ✗ echo $KUBECONFIG
➜  aws-ebs-csi-driver git:(dkoshkin/block-volume-e2e) ✗ ginkgo -v --focus "should create a raw block volume on demand" tests/e2e
Feb 26 07:37:13.474: INFO: The --provider flag is not set.  Treating as a conformance test.  Some tests may not be run.
Running Suite: AWS EBS CSI Driver End-to-End Tests
==================================================
Random Seed: 1551184624 - Will randomize all specs
Will run 1 of …
```
=> Use default kubeconfig location

tests/e2e/testsuites/specs.go
Fix bug in e2e test where cleanup is missing for dynamic created pvs and pre created pvs.
**Testing**
Saw pvc deleting log for each pvc instead of only one:
```
[1mSTEP[0m: Deleting pod ebs-volume-tester-nrc2f in namespace e2e-tests-ebs-ccr6c
Feb 24 17:39:20.779: INFO: deleting PVC "e2e-tests-ebs-ccr6c"/"pvc-r6l9h"
Feb 24 17:39:20.779: INFO: Deleting PersistentVolumeClaim "pvc-r6l9h"
[1mSTEP[0m: waiting for claim's PV "pvc-f5047e9e-385a-11e9-abc0-025ab9cfe534" to be deleted
Feb 24 17:39:20.845: INFO: Waiting up to 10m0s for PersistentVolume pvc-f5047e9e-385a-11e9-abc0-025ab9cfe534 to get deleted
Feb 24 17:39:20.914: INFO: PersistentVolume pvc-f5047e9e-385a-11e9-abc0-025ab9cfe534 found and phase=Released (69.126832ms)
Feb 24 17:39:25.979: …
```
=> Fix bug in e2e test

hack/feature-gates.yaml, tests/e2e/dynamic_provisioning.go, tests/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go, tests/e2e/testsuites/specs.go, tests/e2e/testsuites/testsuites.go
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/221
Add 2 new e2e tests that provisions block volumes.
* a single pod with 1 block volume
* a single pod with 1 block volume and 1 filesystem volume
Locally ran the e2e tests:
```
• [SLOW TEST:58.178 seconds]
[ebs-csi-e2e] [single-az] Dynamic Provisioning
/Users/dkoshkin/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/dynamic_provisioning.go:35
should create a raw block volume on demand
/Users/dkoshkin/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/dynamic_provisioning.go:204
------------------------------
SSSSSSSSSS
Ran 1 of 32 Specs in 58.178 seconds
SUCCESS! -- 1 Passed | 0 …
```
=> New block volume e2e tests

deploy/kubernetes/controller.yaml, deploy/kubernetes/node.yaml
=> Add liveness probe

pkg/driver/node.go, pkg/driver/node_test.go, tests/sanity/sanity_test.go
Add support for nvme on Nitro instance
Fixes: #178 
Manually tested following scenario:
=> Implement device path discovery for NVMe support

go.mod, go.sum, hack/feature-gates.yaml, tests/e2e/driver/driver.go, tests/e2e/driver/ebs_csi_driver.go, tests/e2e/dynamic_provisioning.go, tests/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go, tests/e2e/testsuites/specs.go, tests/e2e/testsuites/testsuites.go
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/228 
Add a new e2e test to provision a pod, write to a volume, take a snapshot, provision a new pod with a volume source as the snapshot, and then validate the data is as expected.
```
• [SLOW TEST:175.757 seconds]
[ebs-csi-e2e] [single-az] Dynamic Provisioning
/Users/dkoshkin/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/dynamic_provisioning.go:39
should create a pod, write and read to it, take a volume snapshot, and create another pod from the snapshot
/Users/dkoshkin/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/dynamic_provisioning.go:411
------------------------------
SSSSSSSSSSSS
Ran 1 of 33 Specs …
```
=> New volume snapshot e2e tests

hack/release
This script is used for generate CHANGELOG content as part of the release.
Currently, it support:
* generate documentation link
* generate sha
Ref: #120
=> Add release script

deploy/kubernetes/controller.yaml
=> Make secret optional

Dockerfile, docs/README.md, examples/kubernetes/storageclass/README.md, examples/kubernetes/storageclass/specs/example.yaml, pkg/driver/node.go
Fixes: #194 
* Add example for storageclass using xfs
* Update Dockerfile to install mkfs.xfs
=> Add support for XFS filesystem

pkg/cloud/cloud.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/fakes.go, pkg/driver/node.go, pkg/driver/node_test.go
Currently, all the driver's dependency are grouped in `Driver` struct. This causes controller service has access to `mounter` and node service has access to `cloud`. This is to increase the maintainability and to modularize the components.
Refactor driver by modularizing node service and controller service so that each service has its own struct with required dependency fields.
=> Refactor driver to modularize node service and controller service

go.mod, go.sum, pkg/driver/controller.go, pkg/driver/node.go
/cc @bertinatto 
This unblocks volume resizing.
=> Upgrade CSI spec to 1.1.0

pkg/cloud/devicemanager/allocator.go, pkg/cloud/devicemanager/allocator_test.go, pkg/cloud/devicemanager/manager.go, pkg/cloud/devicemanager/manager_test.go
Simplify device name allocator logic:
* using deterministic algorithm to generate device name
* the device names are generated in order of: `a`, `b`, ..., `z`, `aa`, `ab`, ..., `az`
Fixes: #35 
/cc @bertinatto 
Verified creating 60 volumes on a 2 node cluster.
=> Refactor device path allocator

pkg/cloud/cloud.go, pkg/driver/controller.go
This should fix the issue #287: return correct error code when restoring a volume referencing non-existent snapshot.
=> Return correct error when restoring non-existent snapshot

pkg/cloud/metadata.go, pkg/cloud/metadata_test.go, pkg/driver/mocks/mock_metadata_service.go, pkg/driver/node.go, pkg/driver/node_test.go, tests/e2e/pre_provsioning.go
/king feature
Without having this field set, k8s will interpret that the node can handle any amount of volumes. I'll create an issue to customize this number per instance type.
Closes #39
=> Add max number of volumes that can be attached to an instance

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/mocks/mock_cloud.go, tests/sanity/fake_cloud_provider.go
Fixes: #233 
This implements ListSnapshots from the CSI spec (not yet used by Kubernetes).
Unit tests have been written for `driver` and `cloud` packages that handle both happy path and error cases.
=> Implementing ListSnapshots

pkg/cloud/devicemanager/allocator.go, pkg/cloud/devicemanager/allocator_test.go
According to
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html,
on HVM instances, sda1 and xvda are reserved for root partition. Also,
the available block device range for xvd follow "/dev/xvd[b-c][a-z]"
pattern.
However commit 1ace946 violates the reserved device names and the naming
logic. This causes volume attachment issues. For example, for instances
where /dev/xvda is root partition, the driver tries to create a new
device with the same reserved name.
This change fixes the issue.
Testing:
Deployed Kube 1.14 cluster.
Update manifest.yaml with canary images for sidecards and new names for
API resources.
Tested new plugin and created sc, pvc (pv) and pod.
Volume attaches to node successfully. New device attached is
"/dev/xvdba" as expected.
Pod mounts volume and …
=> Device allocator should not use reserved dev names.

aws-ebs-csi-driver/.helmignore, aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/templates/NOTES.txt, aws-ebs-csi-driver/templates/_helpers.tpl, aws-ebs-csi-driver/templates/manifest.yaml, aws-ebs-csi-driver/values.yaml
=> Add helm chart

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/mocks/mock_ec2.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/mocks/mock_cloud.go, pkg/driver/mocks/mock_mounter.go, pkg/driver/node.go, pkg/driver/node_test.go, tests/sanity/fake_cloud_provider.go
/kind feature
This PR adds partial support for volume expanding.
It doesn't add the resizer to the manifest file on purpose, so we can keep working on this without exposing the feature to people that try out the driver.
Fixes #146.
=> Add expand support

deploy/kubernetes/manifest.yaml
`deploy/kubernetes` does not work since Kubernetes 1.14:
* The cluster-driver-registrar sidecar container was not released in 1.14 and the version from 1.13 does not work. It is now formally deprecated, so create `CSIDriver` instance during installation.
* Bumped image versions to 1.15.
* Fixed also couple of issues with the yaml file along the way.
=> Update manifest for Kubernetes 1.15

Makefile, aws-ebs-csi-driver/templates/manifest.yaml, deploy/kubernetes/manifest.yaml
The connection-timeout is deprecated: https://github.com/kubernetes-csi/livenessprobe/blob/v1.1.0/cmd/livenessprobe/main.go#L41
=> Remove the deprecated connection-timeout flag for liveness probe

.travis.yml, Dockerfile
=> Upgrade to golang 1.12

aws-ebs-csi-driver/templates/manifest.yaml
**What is this PR about? / Why do we need it?** keep the helm manifest up to date with the deploy/kubernetes manifest updated in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/322
**What testing is done?** ran helm install like
helm install --name aws-ebs-csi-driver \
--set enableVolumeScheduling=true \
--set enableVolumeResizing=true \
--set enableVolumeSnapshot=true \
--set image.repository=$IMAGE_NAME \
--set image.tag=$IMAGE_TAG \
./aws-ebs-csi-driver
and all containers go Running without issue.
=> Update helm manifest for 1.15

hack/run-e2e-test, tests/e2e/suite_test.go
**What is this PR about? / Why do we need it?** test-grid should have tests separated by testcase instead of just Overall
fix https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/192
**What testing is done?** wait for the test to complete for this PR and check test-grid
=> Output junit to ARTIFACTS for testgrid

Makefile, hack/run-e2e-test
=> Running multi-az e2e test using Nitro instance

examples/kubernetes/static-provisioning/README.md, examples/kubernetes/static-provisioning/specs/example.yaml, hack/run-e2e-test, pkg/cloud/cloud.go, pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/node.go, pkg/driver/node_test.go, tests/e2e/driver/ebs_csi_driver.go
Fixes: #324 #326 
/cc @wongma7 @jsafrane @shanesiebken 
This fixes a bug to use `fstype` inside volume capacity for NodeStageVolume and NodePublishVolume call. So that pre-created persistence volume's fstype is used when mounting the volume correctly.
This change also removed the usage of `fstype` in driver's storage class parameter in favor of reserved `csi.storage.k8s.io/fstype` parameter.
Tested on Kops cluster with a pre-created xfs EBS volume and consume it with `fstype` set in the PV spec.
=> Fix the bug by passing fstype correctly

hack/run-e2e-test
**What is this PR about? / Why do we need it?** these tests will fail because ssh won't work. But we don't need to run them anyway as they're k8s specific not driver specific.
=> Skip new k8s-specific test that needs SSH

pkg/cloud/cloud.go
This a new feature. It allows users to specify a custom ec2 endpoint using the environment variable AWS_EC2_ENDPOINT. 
We're running k8s in multiple, non-standard AWS regions. The regions and endpoints are not included in the AWS Go SDK by default. Currently, the correct AWS region is retrieved from the EC2 metadata, but it fails to find the region in SDK's defaults.go and attempts to construct an ec2 URL with an incorrect domain suffix, amazonaws.com. We've been forking this project, vendoring dependencies, and patching the AWS SDK. The proposed change should allow us to use the upstream code without modification across all of our target regions. It does not impact default behavior.
**What …
=> enable users to set ec2-endpoint for nonstandard regions

.github/workflows/container-image.yaml
Add github workflow to build and publish container image:
* It publishes to both dockerhub and github registry
* It uses latest tag for master branch and version tag for git tag (release)
* It only triggers when *.go files are changed
=> Add github workflow to build and publish container image

cmd/main.go, go.mod, pkg/cloud/cloud.go, pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/fakes.go, pkg/driver/validation.go, pkg/driver/validation_test.go, tests/integration/setup_test.go
New feature.
Fixes #333
Add a new cli command option `--extra-volume-tags` which is a map of
string to string (syntax is similar to `--node-labels` for kubelet).  By
default, it's an empty map which maps the the current behavior.
If this option is not empty, when doing dynamic provisioning (i.e., in
`CreateVolume`), we always attach the extra volume tags when calling
`d.cloud.CreateDisk`.
See why we need this in #333.
Yes. Unit tests have been added.
=> Add a cmdline option to add extra volume tags

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/metadata.go, pkg/cloud/mocks/mock_ec2.go, pkg/driver/controller.go, pkg/driver/fakes.go, pkg/driver/mocks/mock_cloud.go, pkg/driver/mocks/mock_mounter.go, pkg/driver/node.go, tests/e2e/dynamic_provisioning.go, tests/e2e/pre_provsioning.go, tests/sanity/fake_cloud_provider.go
Refactor `NewCloud` method by pass in region. This will benefits: #378
=> Refactor NewCloud by pass in region

aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/templates/_helpers.tpl, aws-ebs-csi-driver/templates/manifest.yaml, aws-ebs-csi-driver/values.yaml
Add an option to configure extra volume tags.
New feature
Add an option to configure extra volume tags in helm chart. See #353 
Tested using `helm template` with the following cases:
1. Empty value
`values.yaml`
```yaml
extraVolumeTags: {}
```
`result:`
```yaml
- name: ebs-plugin
image: "amazon/aws-ebs-csi-driver:v0.4.0"
args:                                                                                                                                                                  
- --endpoint=$(CSI_ENDPOINT)
- --logtostderr
- --v=5
```
2. Single pair
`values.yaml`
```yaml
extraVolumeTags:
key1: value1
```
`result`
```yaml
- name: ebs-plugin …
```
=> helm: provide an option to set extra volume tags

hack/run-e2e-test
Add ensure port forwording logic for migration e2e test
/kind bug
=> Add ensure port forwording logic for migration e2e test

hack/run-e2e-test
=> Swith to use kops 1.16

docs/README.md
Bug Fix
Fixes two spelling issues
N/A
=> Fix spelling in README.md

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/mocks/mock_cloud.go, pkg/driver/node.go, tests/sanity/fake_cloud_provider.go
* Fix golint error and normalize variable or function/method naming
* ~If block ends with a return statement, so drop this else and outdent its block~
=> Normalize variable function and method naming

aws-ebs-csi-driver/templates/manifest.yaml, aws-ebs-csi-driver/values.yaml
**Is this a bug fix or adding new feature?** kind of both
At the moment the `tolerations` value is defined yet never used. Without it it's impossible to deploy ebs-csi-driver (the node component) to nodes with taints (which is necessary if you specialise nodes)
I modified the chart locally and generated using different tolerations, including empty, default and with extra custom tolerations.
=> Added tolerations for node support

pkg/cloud/cloud.go, pkg/driver/controller.go, pkg/driver/controller_test.go
/kind bug
From the CSI specs;
```
If the volume corresponding to the volume_id or the node corresponding to node_id cannot be found by the Plugin and the volume can be safely regarded as ControllerUnpublished from the node, the plugin SHOULD return 0 OK.
```
Fixes #330
=> Return success if instance or volume are not found

docs/example-iam-policy.json
Add `ec2:ModifyVolume` action to get authorization to resize volume.
I think it needs to be added to example permission policy json file
I think it is Improvement?
If it doesn't have this action in the permission policy, you should see the following error log when resizing volume.
```
I1230 05:25:14.083279       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"ebs-claim", UID:"6dc884e0-2ac4-11ea-95ac-025d239d2fe4", APIVersion:"v1", ResourceVersion:"547846", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-***
I1230 05:25:14.083201       1 connection.go:181] GRPC request: …
```
=> Add ec2:ModifyVolume action

aws-ebs-csi-driver/templates/manifest.yaml, aws-ebs-csi-driver/values.yaml
**What is this PR about? / Why do we need it?** allows pointing to Helm repo mirrors
If the format works, I will update rest of references in followup PR
=> Allow override for csi-provisioner image

Dockerfile, Makefile, aws-ebs-csi-driver/templates/manifest.yaml, aws-ebs-csi-driver/values.yaml, cmd/options.go, cmd/options/controller_options.go, cmd/options/controller_options_test.go, cmd/options/node_options.go, cmd/options/node_options_test.go, cmd/options/server_options.go, cmd/options/server_options_test.go, cmd/options_test.go, deploy/kubernetes/base/controller.yaml, docs/design.md, go.sum, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/fakes.go, pkg/driver/validation.go, pkg/driver/validation_test.go
Feature
Fixes #378 
This PR allows to only run the controller service of the driver (and not the node service). Also, it allows to configure the AWS region instead of always looking it up via the AWS EC2 metadata service.
This enables the use-case of running the CSI controllers (csi-provisioner, csi-attacher, etc., + the driver controller) separately outside of the cluster, and not necessarily on an AWS EC2 instance.
I ran the CSI controllers + EBS driver separately outside of the Kubernetes cluster (with the newly introduced flags of this PR). Also, I ran the EBS driver daemon set inside the cluster (together with the registrar) without the flags (i.e., with standard …
=> Implement different driver modes and AWS Region override for controller service

aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/node.yaml
Fixes a bug.
I think that the EBS CSI DaemonSet should schedule on all nodes regardless of taints, similar to what's done in the VPC CNI. Exceptions can still be made by re-rendering the helm chart in aws-ebs-csi-driver.
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/420#issuecomment-558409004 suggests the previous version was specific to one installation. By making the default behavior to run everywhere we err on the side of things working.
I'm running these changes on my production cluster without issues.
=> Schedule the EBS CSI DaemonSet on all nodes by default

pkg/cloud/cloud.go, pkg/driver/controller.go, pkg/driver/controller_test.go, tests/sanity/fake_cloud_provider.go
CSI wants CreateVolumeResponse.ContentSource to be set to the snapshot that has just been restored.
Fixes #444
=> Fix CreateVolumeResponse after snapshot restore

go.mod, go.sum
New feature
Update the SDK to get support for IMDSv2.
There potentially is a latency regression for IMDSv1: https://github.com/aws/aws-sdk-go/issues/2972, but supposedly it has been fixed: https://github.com/aws/aws-sdk-go/pull/3066.
In my testing I have not noticed any regression that would cause driver errors.
Ran k8s external-storage e2es on a cluster with IMDSv1 (and no v2), and separately on a cluster with IMDSv2 (only) enabled.
=> Update aws-sdk to v1.29.11 to get IMDSv2 support

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
It's improvement
Adding a `nodeSelector` to for the `aws-ebs-csi-driver` target only `amd64` machines for multi cluster architectures.  
Fixing Issue #471 
Yes, it's running on my multinode archtecture
Nodes
```bash
± |affinity ✓| → k get nodes -o wide | grep amzn2
ip-10-0-29-162.eu-west-1.compute.internal   Ready    <none>   4d2h    v1.15.10-eks-bac369   10.0.29.162   <none>        Amazon Linux 2                   4.14.171-136.231.amzn2.x86_64    docker://18.9.9
ip-10-0-87-226.eu-west-1.compute.internal   Ready    <none>   2d4h    v1.15.10-eks-bac369   10.0.87.226   <none>        Amazon Linux 2                   4.14.171-136.231.amzn2.aarch64   docker://18.9.9 …
```
=> Adding amd64 as nodeSelector to avoid arm64 archtectures (#471)

pkg/driver/controller.go
```
aws-ebs-csi-driver/pkg/driver/controller.go
Line 418: warning: if block ends with a return statement, so drop this else and outdent its block (golint)
```
=> Correct golint warning

pkg/driver/mount_test.go
=> Additional mount unittest

aws-ebs-csi-driver/templates/daemonset.yaml, deploy/kubernetes/base/node.yaml
bug fix
Add nodeAffinity in the daemonset to avoid schedule ebs-csi-node pods on Fargate worker nodes, as Fargate does not support ebs.
If there is a pod running in Fargate, the daemoset tries to place ebs-csi-node pod in the same node, with causes the pod to Pending state.
Apply the original with kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master" -> pods Pending.
Adding the nodeAffinity, all pods in the Pending state on Fargate are deleted and new are only created at EC2 nodes
=> Add nodeAffinity to avoid Fargate worker nodes

aws-ebs-csi-driver/templates/daemonset.yaml, aws-ebs-csi-driver/templates/deployment.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md
> kubelet  the beta.kubernetes.io/os and beta.kubernetes.io/arch labels, deprecated since v1.14, are targeted for removal in v1.18.
=> *: remove deprecated "beta.kubernetes.io/os" nodeSelector

aws-ebs-csi-driver/templates/rbac.yaml, deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml
/kind cleanup
With v2.0.0 of kubernetes-csi/external-snapshotter, it is split into two component - the csi-snapshotter sidecar and the snapshot controller (ref https://github.com/kubernetes-csi/external-snapshotter/pull/182). As the `VolumeSnapshot` watch is moved to the new snapshot controller, the csi-snapshotter sidecar ClusterRole no longer needs to rules for volumesnapshots.
This PR adapts the csi-snapshotter sidecar RBAC according to https://github.com/kubernetes-csi/external-snapshotter/blob/v2.1.1/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml.
=> Improve csi-snapshotter ClusterRole

aws-ebs-csi-driver/templates/statefulset.yaml, aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml, deploy/kubernetes/overlays/alpha/snapshot_controller.yaml
/kind cleanup
Update kubernetes-csi/external-snapshotter components to v2.1.1 - ref https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v2.1.1.
=> Update kubernetes-csi/external-snapshotter components to v2.1.1

deploy/kubernetes/overlays/stable/kustomization.yaml
**Is this a bug fix or adding new feature?** bug 
**What is this PR about? / Why do we need it?** 0.5.0 was released, bump overlay kustomization to match. This fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/494 because the `node` arg was added to the template but it isn't recognized by 0.4.0, need to bump to 0.5.0 for stable overlay to continue working.
=> Update stable overlay to 0.5.0

examples/kubernetes/resizing/README.md
=> Fixed resizing docs to refer the right path to example spec

docs/example-iam-policy.json
Originally authored by @pierresteiner at #461. He was unable to complete the PR due to being unable to sign a CLA. I have no such barrier so I am submitting instead.
> Without that, I was getting a nasty error message with 0.5.0
> 
> ```
> E0310 15:07:10.063122       1 controller.go:910] error syncing claim "835b97fa-62e0-11ea-b720-06ab0707f8ae": failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = Could not create volume "pvc-835b97fa-62e0-11ea-b720-06ab0707f8ae": failed to get availability zone UnauthorizedOperation: You are not authorized to perform this operation.
> ```
> 
> **Is this a bug fix or adding new feature?**: Bug
> 
> **What is this PR about? / Why do we need it?**: It fixes the list of permission
> 
> **What testing is done?**: Yes
> 
> …
=> Add missing IAM permissions

Dockerfile
cache go mod during docker build
=> optimization: cache go mod during docker build

cmd/main.go, cmd/options/node_options.go, cmd/options/node_options_test.go, cmd/options_test.go, deploy/kubernetes/base/node.yaml, docs/design.md, pkg/driver/driver.go, pkg/driver/driver_test.go, pkg/driver/node.go, pkg/driver/node_test.go, pkg/driver/sanity_test.go
/kind feature
This PR is a part of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/347 and proceeds with the way suggested in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/347#issuecomment-638177835: In order to allow existing clusters that are leveraging/relying on the `KUBE_MAX_PD_VOLS` feature for in-tree provisioners in Kubernetes (https://kubernetes.io/docs/concepts/storage/storage-limits/#custom-limits) to migrate to CSI, the EBS CSI driver is supporting the `--volume-attach-limit-overwrite` flag now until a more sophisticated solution can be implemented.
PS: I was adding a few missing doc strings along the way and reduced package/function name stuttering …
=> Allow volume attach limit overwrite via command line parameter

pkg/cloud/cloud.go
Bug fix.
Fixes: #306 
Our project requires the full IOPS capacity of EBS volumes.
Max IOPS for SSD (io1) volumes was increased from 20,000 to 32,000:
https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-ebs-provisioned-iops-ssd--io1--volumes-now-support-32-000-iops-and-500-mbs-per-volume/
and later to 64,000:
https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-elastic-block-store-announces-double-the-performance-of-provisioned-iops-volumes/
Rather than chasing this limit, allow the AWS SDK to surface errors for IOPS value out of range.
go test
=> Remove volume IOPS limit

cmd/main.go, cmd/options/controller_options.go, cmd/options/controller_options_test.go, docs/README.md, pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/driver_test.go
Bugfix, to reach 100% compatibility with the in-tree volume plugin, the CSI driver should create also the same tags on dynamically provisioned volumes.
* When the external-provisioner passes PV/PVC name/namespace via `CreateVolumeRequest.Parameters`, use those to tag volumes (i.e. the provisioner must run with `--extra-create-metadata=true`).
* When `--k8s-tag-cluster-id` was provided on cmdline, use those to tag the provisioned volumes as owned by the cluster.
Both set of tags are optional.
Fixes: #529
* Tested with Kubernetes 1.18 and external-provisioner 1.6.
=> Add tags that the in-tree volume plugin uses

cmd/options/node_options.go
Specify that the `--volume-attach-limit` is per node.
=> Nit: improve flag description

.github/workflows/container-image.yaml, aws-ebs-csi-driver/templates/controller.yaml, aws-ebs-csi-driver/templates/node.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Add arm support

Dockerfile, Makefile, go.mod, go.sum
I would say it is a security improvement.
When amazonlinux is used as base image we are detecting multiple critical vulnerabilities in the image, some of them are 
1. CVE-2016-4658
1. CVE-2017-7376
1. CVE-2016-4448
1. CVE-2016-1834
1. CVE-2017-16997
1. CVE-2017-18269
1. CVE-2019-5482
1. CVE-2019-5481
1. CVE-2019-3822
...
And many others.
Change the base image to ~alpine linux~ debian-base-amd64 to reduce the number of reported security vulnerabilities and also the size of the image from:
```
$ docker image ls amazon/aws-ebs-csi-driver:latest
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
amazon/aws-ebs-csi-driver   latest              ddab7a7bfa60 …
```
=> Change the base image to debian-base

aws-ebs-csi-driver/templates/controller.yaml
Without this, the manifest renders with empty line between the
arguments, which does not look nice.
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
=> aws-ebs-csi-driver/templates/controller.yaml: fix rendered emptyline

pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/util/util.go, pkg/util/util_test.go
Bug fix
If incorrect volume capabilities are specified for the in-tree driver, the following error message is displayed:
> invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported
This PR updates the CSI Driver's error message to be more explicit, so that the incorrect access modes are also displayed in the error message.
Performed manual testing with the AWS EBS CSI Driver and confirmed the error message had been updated.
=> Clarify error message when unsupported volume capabilities are provided

tests/e2e/driver/ebs_csi_driver.go
**What is this PR about? / Why do we need it?** tests timeout inexplicably, i still have not had much chance to deep dive/repro why so let's just bump iops from the minimum for now and see if it helps. ref: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/545
=> Double iops/gb for io1 and io2 e2e tests

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/498
This PR contains following fixes:
- When describeVolume returns volume size to be greater than requested size, we also verify if volume has any modifications pending. I have observed that, AWS can set targetSize on volume even with pending volume modifications. This is the root cause of EBS resize flake.
- When volume modifications check return volume resizing to be completed, we also verify volume size by describing volume. This is to ensure that - we minimize impact of eventual consistency by making two different API calls.
=> Make EBS controllerexpansion idempotent

tester/migration-test-config.yaml, tester/multi-az-config.yaml, tester/single-az-config.yaml
**Is this a bug fix or adding new feature?** routine bump
**What is this PR about? / Why do we need it?** We should be continuously testing new driver versions against new kubernetes versions.
**What testing is done?** N/A, will see if CI passes and adjust accordingly.
=> Bump all e2e test clusters to latest version 1.18.9

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/metadata.go, pkg/cloud/metadata_test.go, pkg/cloud/mocks/mock_ec2metadata.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/mocks/mock_metadata_service.go, pkg/driver/node.go, pkg/driver/node_test.go, tester/single-az-config.yaml, tests/e2e/driver/driver.go, vendor/github.com/aws/aws-sdk-go/aws/arn/arn.go, vendor/modules.txt
Bug Fix
[Outposts Documentation](https://docs.aws.amazon.com/outposts/latest/userguide/what-is-outposts.html) for background.
Currently, we're running oblivious to outposts. Volumes are created in the parent region instead of the outpost itself. In order to fix it, we need to pass the `outpostArn` to [CreateVolume](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html).
I'm leveraging the `outpost-arn` instance metadata to determine if we're in an outpost instance. There are two possible responses from the endpoint:
- The outpost-arn if it's an outpost instance
- `404` if it's a regular non-outpost instance.
I've verified the behavior using [this test …
=> Create volumes in outpost for outpost instances

deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
N/A
Adds a new kustomization layout that uses the images from ECR instead of quay and docker hub. Fixes #554.
=> Add overlay for ECR images

CHANGELOG-0.x.md, Makefile, aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
=> Release v0.7.0

.github/workflows/container-image.yaml
**What is this PR about? / Why do we need it?** Until I get approval to push debian based image to Docker Hub, need to revert to AL2. As discussed in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/551, there are good reasons to base on debian instead, but at least for the next release I don't have much choice!
This buildx command worked locally
```
~/g/s/g/k/aws-ebs-csi-driver (al2|✔) [1] $ docker buildx build \
-t a:b \
--output="type=image,push=false" . \
--target=amazonlinux
[+] Building 122.5s (13/13) FINISHED                                                         
=> [internal] load .dockerignore                                                       0.0s
=> => transferring context: 2B …
```
=> Push amazonlinux target to Docker Hub

docs/README.md
Fix markdown issue in README.md.
=> Fix markdown issue in README.md

docs/README.md
**What is this PR about? / Why do we need it?** unlike in-tree, we error if the iops of a volume is below min or above max. Document it to avoid surprises like https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/575
**What testing is done?** N/A
=> Document behavior wrt minimum and maximum iops

cmd/main.go, cmd/options/controller_options.go, cmd/options_test.go, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/driver_test.go, pkg/driver/validation.go, pkg/driver/validation_test.go
Adding a new feature, see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/566
This PR takes the `--extra-volume-tags` that are applied to provisioned EBS volumes in `CreateVolume()`, and also adds them provisioned snapshots via `CreateSnapshot()`.
- Included a unit test that asserts the `snapshotOptions` received by `cloud.CreateSnapshot()` includes the supplied 
`extraVolumeTags`
- Included a unit test that asserts the `snapshotOptions` received by `cloud.CreateSnapshot()` includes the cluster ID if that driver option is enabled (See PR feedback)
- Included a unit test that asserts the request object sent to the AWS API is correct
- This test caught a bug …
=> Apply extra volume tags to EBS snapshots

aws-ebs-csi-driver/values.yaml
Fixing image tag - see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/584
=> Fixed image tag for helm chart values

aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/templates/controller.yaml, aws-ebs-csi-driver/values.yaml
Feature
Add options to create EBS volume tags that the in-tree plugin creates
Tested within our EKS 1.17 cluster, confirmed that new volumes have correct names/tags.
=> [helm] add tag options and update csi-provisioner

tester/migration-test-config.yaml
**What is this PR about? / Why do we need it?** IDK if checking metrics' plugin_name https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/560#issuecomment-698543689 is a valid way of testing whether migration is working or not, better to set CSIMigrationAWSComplete to turn off the in-tree plugin entirely.
**What testing is done?** N/A, the migration suite is currently failing
=> Set CSIMigrationAWSComplete for migration tests

hack/run-e2e-test
**Is this a bug fix or adding new feature?** bug fix. 
**What is this PR about? / Why do we need it?** migration tests are still using this script & CSIMigrationComplete flag is in 1.17+ so my previous PR to set it didn't take effect, need to bump versions. (I guess kops doesn't validate feature gates or IDK how cluster creation passed with nonexistent gate)
**What testing is done?**  N/A, will keep an eye on migration job.
=> Bump migration kops and k8s version

deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Updates the ecr overlay to use the latest 0.7.1 version. Also fixes the base path (see #625).
=> Update ecr overlay image tag

cloudbuild.yaml
**Is this a bug fix or adding new feature?** new.
**What is this PR about? / Why do we need it?** To eventually publish release images to the community gcr https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io, need a cloudbuild.yaml to push staging images to gcr.io/k8s-staging-provider-aws https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing 
**What testing is done?** It looks like the only way to test this end to end is after making a PR in test-infra to add a ProwJob to run this build https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing#prow-config-template
=> Add cloudbuild.yaml for image pushing to gcr

hack/.gitignore, hack/run-e2e-test, hack/utils/helm.sh, hack/utils/kops.sh
**What is this PR about? / Why do we need it?** Used this PR to debug migration, it is still broken pending https://github.com/kubernetes/kubernetes/pull/96821 but there are various fixes I made to the script along the way .
TEST_ID=18512 CLEAN=false KOPS_STATE_FILE=s3://aws-ebs-csi-driver-e2e AWS_REGION=us-west-2 AWS_AVAILABILITY_ZONES=us-west-2a GINKGO_FOCUS=Dynamic.\*xfs.\*should.store.data GINKGO_NODES=1 ./hack/run-e2e-test
=> Update hack/run-e2e-test to be more idempotent and pleasant to use

index.yaml
This is a temporary bug fix to get all of the available chart versions into the chart repository
Currently the index.yaml for the chart repo is being maintained by hand and is out of date.  This will update the index to contain all currently available chart versions.
I have tested the index.yaml from my own chart repository.
I will create another PR to automatically manage the chart repository on pushes when it is updated.  This PR needs merged first so when the other change is made it has a correct index.yaml to merge updates into.
fixes #557
fixes #587
fixes #617
=> Update chart repo index.yaml to contain all currently available chart versions

cloudbuild.yaml
**What is this PR about? / Why do we need it?** the postsubmit should also push a latest tag to the staging gcr.
This is mostly for debugging purposes like to test that this cloudbuild even succeeds once I add a postsubmit to execute it. Also could be useful for dev purposes to have an image in staging gcr.
**What testing is done?** None yet, need that prow postsubmit to actually test this
=> Add latest tags to cloudbuild

docs/README.md
This will update the link to the developer documentation github pages.
Fixing a readme broken link
Documentation
Confirmed the link doesn't return a 404.
=> docs(readme): update link to developer documentation

aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml, deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_leaderelection_rolebinding.yaml
Bug fix
Before, the RoleBinding was named snapshot-controller-leaderelection. It
also incorrectly referenced the snapshot-controller-leaderelection Role
instead of the ebs-snapshot-controller-leaderelection Role defined by
the Helm chart
By default, the objects for the snapshot controller from
kubernetes-csi/external-snapshotter [1] are installed into the default
namespace. The manifests, however, recommend installing the objects in
the kube-system namespace instead. One of the objects is a RoleBinding
named snapshot-controller-leaderelection. When installing the snapshot
controller from the external-snapshotter repo into the kube-system
namespace, the AWS EBS CSI driver Helm chart fails to …
=> Fix the name of the snapshot controller leader election RoleBinding

cloudbuild.yaml
bug fix.
inaugural gcr jobs failed https://prow.k8s.io/?job=aws-ebs-csi-driver-push-images
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1334990729704902656
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/.github/workflows/container-image.yaml#L23
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/Dockerfile#L20
amazonlinux is the right target name.
=> Fix target name in cloudbuild.yaml from amazon to amazonlinux

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml
- Fix to apply resource constraints to all side containers.
- See #637 
- Updated resource constraints for all the side containers and deployed. Deployment was successful without any resource constraints errors on my EKS cluster.
=> Apply resource constraints to all sidecar containers

.github/workflows/container-image.yaml
**Is this a bug fix or adding new feature?**fix
**What is this PR about? / Why do we need it?**To match cloudbuild.yaml https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/cloudbuild.yaml and in preparation for the next release v0.8.0, amazonlinux based images will be suffixed with -amazonlinux, like v0.8.0-amazonlinux. And debian based images will become the "default" unsuffixed v0.8.0.
At the same time, I noticed crazy-max/ghaction-docker-buildx@v3 was deprecated https://github.com/crazy-max/ghaction-docker-buildx so I rewrote the action to use docker's official github actions.
**What testing is done?** Not sure if testing is possible? given the extensive rewrite I want to test the new scrijpt but it doesn't seem possible without actually triggering the action. So I will …
=> Suffix amazonlinux image with -amazonlinux and push debian image to GitHub

.github/workflows/container-image.yaml
**Is this a bug fix or adding new feature?**fix
**What is this PR about? / Why do we need it?** arm image build failed because I forgot to add support for building multi platform via qemu https://github.com/kubernetes-sigs/aws-ebs-csi-driver/runs/1519273877
**What testing is done?**  the docker buildx build commands work locally after I install qemu.
=> Set up QEMU to build for arm64

.github/workflows/container-image.yaml, .github/workflows/release.yaml
**What is this PR about? / Why do we need it?** Since now there is a separate workflow for releasing helm charts https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/.github/workflows/helm-chart-release.yaml, the steps in github release workflow are redundant and don't work.
~Container images workflow doesn't work either since it logs into ghcr.io but then tries to push to   docker.pkg.github.com like before: https://docs.github.com/en/free-pro-team@latest/packages/guides/migrating-to-github-container-registry-for-docker-images~
Since nobody uses the github registry (github reports 0 downloads) and I am not sure if ghcr.io is okay to use, I'll fix it later and backfill the v0.8.0 image manually if necessary
**What testing is …
=> Remove helm chart step from release github workflow and github registry step from container images workflow

deploy/kubernetes/overlays/dev/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
/bug
Fixing some oversights/neglect/mistakes from gcr migration. See: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/646
```
kubectl apply -k ./deploy/kubernetes/overlays/stable
k get deployment -n kube-system ebs-csi-controller
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
ebs-csi-controller   2/2     2            2           19d
k get deployment -n kube-system ebs-csi-controller -o jsonpath="{.spec.template.spec.containers[0].image}"
k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0^J  
kubectl apply -k ./deploy/kubernetes/overlays/dev
k get deployment -n kube-system ebs-csi-controller -o jsonpath="{.spec.template.spec.containers[0].image}" …
```
=> Fix overlays not being updated for gcr migration

.github/workflows/container-image.yaml, .github/workflows/release.yaml
**What is this PR about? / Why do we need it?** cherry pick of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/644 on 0.8 branch, else future cherry picks to 0.8 branch will have broken github release workflows
=> release-0.8: Remove helm chart step from release github workflow and github registry step from container images workflow

deploy/kubernetes/overlays/dev/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
/bug
**What is this PR about? / Why do we need it?** cherry-pick of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/649 on release-0.8. Else kubectl kustomize stable overlay commands pointing to this branch ( which they should, to avoid churn/breakage from master branch, hence "stable") will not work.
/hold
=> release-0.8: Fix overlays not being updated for gcr migration 

charts/aws-ebs-csi-driver/templates/clusterrole-attacher.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/clusterrole-attacher.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/arm64/kustomization.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, tester/multi-az-config.yaml, tester/single-az-config.yaml
Maintenance
Driver can't be deployed on arm instances because of non-multiarch sidecar images. This PR updates some of the sidecar images and adds an overlay with multiarch images.
Manual testing on my cluster + e2e tests.
=> Arm overlay

cloudbuild.yaml
cloudbuild is not magic, if arm64 images are desired then buildx must b ecalled
command works locally, don't have access to cloudbuild to test it in cloudbuild
=> Use buildx in cloudbuild

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml
Feature
This allows users to customize the nodeSelector field of the daemonset deploying the ebs-csi-nodes the same way one can customize the nodeSelector of the deployment deploying the controllers. This is needed in the case of a hybrid cluster where some nodes are AWS hosts whereas others are not (the ebs-csi-nodes on the non-AWS hosts continuously crashloop).
Verified that the Chart renders as expected
=> Feature: Add ability to customize node daemonset nodeselector

cloudbuild.yaml
**Is this a bug fix or adding new feature?** fix cloudbuild.yaml
**What is this PR about? / Why do we need it?** the attempt to do multiarch cloudbuilds from https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/658 failed horribly with "Step #0: unknown flag: --tag". I think it has something to do with buildx not being available so I am shuffling that stray "HOME=/root" thing that I csopy/pasted from the doc to someplace that makes sense to me. Also sinc ethe github workflow has to enable multiarch using the qemu image then I guess this does too.
```
docker run -e HOME=/root --entrypoint=bash -it  gcr.io/cloud-builders/docker
root@084b1a2e938b:/# DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build …
```
=> (Try to) fix cloudbuild

cloudbuild.yaml
**What is this PR about? / Why do we need it?** this explains the 
```
ERROR: (gcloud.builds.submit) build 91a9a509-a135-44aa-a439-af84587bbd96 completed with status "FAILURE"
Step #1: "docker buildx build" requires exactly 1 argument. 
```
error.
I still intend to move to a model where the cloudbuild calls a script similar to https://github.com/kubernetes-csi/csi-release-tools/blob/master/prow.sh#L1243 https://github.com/kubernetes-csi/csi-release-tools/blob/master/build.make#L132 (ty to person who pointed me to these : ) ) , it will be easier to maintain than wrestling with cloudbuild syntax, and anyway the github  workflow could call the same script so we don't have to maintain two copies of the same code. This is just a nobrainer …
=> Fix stray argument in cloudbuild.yaml

CHANGELOG-0.x.md, docs/README.md
Adding a note because gp3 is not supported on outposts. See #662 
N/A
=> Add note for gp3 on outposts

cloudbuild.yaml, hack/prow.sh
**Is this a bug fix or adding new feature?** fix gcr builds
**What is this PR about? / Why do we need it?** gcr builds are broken in attempt to fix multiarch build. 
I stopped short of migrating to csi-release-tools entirely, that would take more work. However I copied parts from it and linked to those parts.
**What testing is done?** Same as with previous PRs: Unfortunately I cannot test end-to-end without actually merging, the container release prow job runs on master and release* branches. I did briefly test the script on release-test branch with manual pushes before prow caught on and marked it protected....
Script works locally.
`env REGISTRY_NAME=public.ecr.aws/b5w6x5z2 GIT_TAG=asdf ./hack/prow.sh`
DEBIAN x86-64
```
$ sudo ctr image pull …
```
=> Call hack/prow.sh from cloudbuild

cloudbuild.yaml
**Is this a bug fix or adding new feature?** bug fix
**What is this PR about? / Why do we need it?** This variable needs to be set, same as here: https://github.com/kubernetes-csi/csi-release-tools/blob/master/cloudbuild.yaml#L48.
Else the build errors like:
invalid tag "gcr.io//aws-ebs-csi-driver:v20201219-aws-ebs-csi-driver-0.7.1-8-g1bb8ba8": invalid reference format 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1340088065888096256
=> cloudbuild: Set _STAGING_PROJECT

charts/aws-ebs-csi-driver/templates/clusterrole-attacher.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/clusterrole-attacher.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/arm64/kustomization.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, tester/multi-az-config.yaml, tester/single-az-config.yaml
**What is this PR about? / Why do we need it?** cherry-pick of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/653.
Since our kustomize templates are branched (they cannot be versioned like helm charts) changes to them have to be backported to the branch so that 
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-0.8"
works and stays stable.
=> release-0.8: Arm overlay

cloudbuild.yaml, hack/prow.sh
This is 5 commits squashed together. Squashed because they aren't useful on their own, they were each guess-and-test attempts at fixing prow cloudbuild job to produce multiarch images.
```
git cherry-pick 99c4c0a
git cherry-pick dff4ef1
git cherry-pick 5beb246
git cherry-pick 35e0ede
git cherry-pick e5b1c58
```
Corresponding PRs:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/658
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/659
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/661
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/666
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/668
**What testing is done?** This cloudbuild is working in …
=> release-0.8: Use buildx in cloudbuild

hack/run-e2e-test
fix
REF:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html
get-login doesn't exist anymore
New command works for me
=> Fix outdated ecr login command

.github/workflows/cr.yaml, .github/workflows/helm-chart-release.yaml
**Is this a bug fix or adding new feature?** fix https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/643
**What is this PR about? / Why do we need it?** Since chart version follows driver version but not really, to avoid confusion & ambiguity I want to prefix helm chart releases and tags with "helm-chart-". Open to suggestions of other names or references to best practices here.
**What testing is done?** tsted in my fork (took couple of tries):
https://github.com/wongma7/aws-ebs-csi-driver/runs/1658660168
https://github.com/wongma7/aws-ebs-csi-driver/releases/tag/helm-chart-aws-ebs-csi-driver-0.7.4
=> Prefix helm chart releases with "helm-chart-"

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/arm64/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
**What is this PR about? / Why do we need it?** cherry pick of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/683/files onto release-0.8 branch.
The reason this is needed is:
1. kustomize templates must be updated
2. Makefile should be updated so that --version output of the binary is correct. AS mentioned in above PR, i tagged v0.8.1 prematurely so actually the binary built at tag v0.8.1 is going to still print v0.8.0.
The helm chart/doc changes are superfluous but don't hurt
=> release-0.8: Release 0.8.1

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/arm64/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
**Is this a bug fix or adding new feature?** new
**What is this PR about? / Why do we need it?** Need a new release for multiarchness since v0.8.0 mutliarch is broken: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/656
**What testing is done?** 0.8.1 has the same tag as 0.8.1-rc.0 which I tested for multiarchness following the same steps as in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/666
TODO: I will need to cherry-pick the kustomize changes into the release-0.8 branch.
Known issue:
Since I already tagged v0.8.1 before updating the Makefile in this PR, the "version" output in the v0.8.1 image is still going to show v0.8.0. In future, this PR should come first THEN it should be tagged, even if it means YAMLS will refer to images that haven't been pushed it.
=> Release 0.8.1

.github/workflows/container-image.yaml
Originally avoided pushing debian base to docker hub cuz of internal restriction on what is allowed to be pushed, but this is approved .
**What testing is done?** the amazonlinux push already works
docker pull amazon/aws-ebs-csi-driver:v0.8.1-amazonlinux
/assign @ayberk
=> Push debian target to Docker Hub

go.mod, pkg/driver/mount.go, pkg/driver/node.go, pkg/driver/node_test.go, pkg/driver/sanity_test.go
Fixes #223
Fixes #499 
Implement Volume stats metrics
Added unit test for the change
=> add volume stats metrics -

examples/kubernetes/dynamic-provisioning/README.md
New documentation
Emphasise that enableVolumeScheduling should be equal to true, in order to provision EBS volumes dynamically.
=> Add a prerequisite to dynamic provisioning

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-provisioner.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-resizer.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshot-controller.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshotter.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-snapshot-controller.yaml, charts/aws-ebs-csi-driver/templates/statefulset.yaml, charts/aws-ebs-csi-driver/values.yaml
New feature
Fixes #485
```
ip-172-31-62-224  aws-ebs-csi-driver git:(service_account) ✗ 01/12 2:41 helm template charts/aws-ebs-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: ebs-csi-controller-sa
namespace: kube-system
labels:
app.kubernetes.io/name: aws-ebs-csi-driver
app.kubernetes.io/instance: RELEASE-NAME
helm.sh/chart: aws-ebs-csi-driver-0.7.1
app.kubernetes.io/version: "0.8.0"
app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: ebs-snapshot-controller
namespace: kube-system
labels:
app.kubernetes.io/name: aws-ebs-csi-driver
app.kubernetes.io/instance: RELEASE-NAME
helm.sh/chart: aws-ebs-csi-driver-0.7.1 …
```
=> Add support for existing service accounts

deploy/kubernetes/base/clusterrole-attacher.yaml
Resolves #689 
Allows patching volumeattachments/status.
bug
It appears the external attacher communicates by updating the status of volumeattachments, but the existing clusterrole doesn't have that ability.
Have validated is resolves #689 within an EKS cluster.
=> Adds patch for ebs-csi-controller-sa to volumeattachments/status

pkg/driver/node.go, pkg/driver/node_test.go
Fixes #346 
Fixes #339 
NodeExpandVolume will check volume type (mount point or block device)and skip resize on block volume.
Sanity test passed
Added unit tests
=> NodeExpandVolume no-op for raw block

charts/aws-ebs-csi-driver/templates/clusterrole-resizer.yaml, deploy/kubernetes/overlays/alpha/rbac_add_resizer_clusterrole.yaml, tests/e2e/driver/driver.go, tests/e2e/driver/ebs_csi_driver.go, tests/e2e/dynamic_provisioning.go, tests/e2e/pre_provsioning.go, tests/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go, tests/e2e/testsuites/specs.go
Fixes #316
Add e2e test for volume resizing
=> add e2e test for volume resizing

cloudbuild.yaml
**Is this a bug fix or adding new feature?** bug
**What is this PR about? / Why do we need it?**  The initial v0.9.0 build failed because of 20m* timeout: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1356735403712843776
Try bumping it to 30m*
If works, will make same PR against master.
I'll push a v0.9.0-rc.0 tag to test the build.
=> Bump cloudbuild timeout to 1800s

cloudbuild.yaml
Trying to unblock the release. We still need to investigate why builds have been failing since 01/11.
=> Increase timout for cloudbuild

docs/README.md, docs/RELEASE.md
Adds documentation for the release process. It's meant to be followed step by step, top-down.
Note that this is modified version of [authenticator release process](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/docs/RELEASE.md).
=> Add documentation for release process

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/storageclass.yaml, charts/aws-ebs-csi-driver/values.yaml
New feature in the helm chart
Most application charts don't usually create `StorageClass`es. They create PVCs.
Installed the chart with the following custom values:
```yaml
enableVolumeResizing: true
enableVolumeScheduling: true
enableVolumeSnapshot: true
serviceAccount:
controller:
name: ebs-csi-controller
annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::123:role/cluster-name-kube-system-ebs-csi-controller
snapshot:
create: false
name: ebs-csi-controller
annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::123:role/cluster-name-kube-system-ebs-csi-controller
storageClasses:
- name: ebs-sc
parameters:
encrypted: "true"
```
Then tried creating a PVC and a pod that …
=> feat: Add option to provision StorageClasses

charts/aws-ebs-csi-driver/Chart.yaml
Last PR I approved didn't update the chart version (appVersion was updated instead). This fixes that so we can release the chart.
See #697
=> Bump chart version

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/statefulset.yaml
Apply nodeSelector, affinity, tolerations and priorityClassName to snapshoter. This PR brings the `snapshot-controller` StatefulSet on par with the `ebs-csi-controller` Deployment, applying the same scheduling settings to it. This is important
for clusters where cluster-addons (like the aws-ebs-csi-driver) are scheduled to dedicated node groups, which are
isolated from other (general purpose) node groups.
=> More controll over snapshot-controller scheduling

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go
Fixes #515 
According to https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerpublishvolume-errors
We are returning wrong error code and error message when volume already assigned to different node
TODO: add logic to handle ALREADY_EXISTS scenario 
Sanity test passed
Added unit tests
=> modify error message when request volume is in use with other node

deploy/kubernetes/base/arm64/node.yaml
I think this is a bug fix.
The ARM-supporting kustomization base still missed the correct (multiarch) liveness sidecar image for the Node service.
The Helm chart already gets the [default](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v0.9.0/charts/aws-ebs-csi-driver/values.yaml) correctly.
=> Fix daemonset liveness image to multiarch version for ARM kustomization

Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/kustomization.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/base/serviceaccount-csi-node.yaml
New feature
Fixes #703
Helm template
=> Add support for node existing service accounts

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/storageclass.yaml
A new feature
The StorageClasses created by the Helm chart can currently only be configured with `volumeBindingMode`, `reclaimPolicy`, and `parameters`. We have `allowVolumeExpansion: true` set on ours, so we couldn't migrate them to be provisioned by the chart.
This PR allows any field permitted by the API to be specified.
I've templated the chart with a variety of StorageClasses and validated that the output manifests are correct.
=> Allow all fields to be set on StorageClasses

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/statefulset.yaml, charts/aws-ebs-csi-driver/values.yaml
CSI controller and node have different needs in a manner of capacity so
in this commit we enable users to define specific resources for the node
component. This will allow users not to reserve not needed resources on
all of their instances as node is a DaemonSet and may not need as much
CPU/Memory as the controller Pods.
Adding a feature of overriding resource for the node
Mitigate overprovisioning capacity for node component
Tested on our internal clusters
=> [chart] Allow resources override for node DaemonSet + priorityClassName

deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
It's been a while since we updated the ECR overlay. This PR
- Updates the driver version to 0.9.0
- Uses the new public ECR for sidecars
Deployed to my own cluster and verified it runs.
=> Update ECR overlay

pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/node.go, pkg/driver/node_test.go, pkg/driver/sanity_test.go
Addresses #165, but the full fix requires an EBS API change.
This PR works around idempotency issues with the `CreateVolume` API. It does so by using the `InFlight` struct to mark a request as "in progress". If an identical `CreateVolumeRequest` is received while another is in progress, we return an error to the caller.
Unit tests and smoke tests on a k8s cluster on AWS.
This issue can be repeated by the following command (similar to the one in the GitHub issue, however it uses `&` to background the first call):
```
csc controller --endpoint <socket or address> create-volume --cap SINGLE_NODE_WRITER,block <volume name> & \
csc controller --endpoint <socket or address> …
```
=> Make CreateVolume idempotent

pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/internal/inflight.go, pkg/driver/internal/inflight_test.go, pkg/driver/node.go, pkg/driver/node_test.go
Fixes #307 
Fixes #370 
Handle concurrency for node operations (stage/unstage publish/unpublish)
According to https://github.com/container-storage-interface/spec/blob/master/spec.md#concurrency driver's InFlight cache should track in-flight request per volumeId instead of per request to ensure no more than one request per volume at a given time.
=> Refactor inFlight key to add lock per volumeId

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml
Fixes #727 
Changes the default value of `enableVolumeScheduling` from `false` to `true` for the helm chart.
=> Set enableVolumeScheduling to true by default in the helm chart

hack/e2e/run.sh
Updating the k8s version e2e tests are running so we get the inline fix: https://github.com/kubernetes/kubernetes/pull/96821
See k8s [Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v11815).
=> Update test k8s version to 1.18.16

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/statefulset.yaml
Fixes #613 
Sets the `imagePullSecrets` if the value is set in the chart
Rendered the chart with & without `imagePullSecrets` set and validated the yaml with `kubeval`
=> Sets the imagePullSecrets if the value is set in the chart

pkg/cloud/cloud.go
This commit increase the number of retries to a high number (8) so
that the AWS framework retries failing requests until the request
context times-out.
By default, when throttled, the aws client retries a given request
3 times with exponentially increasing delay between retries.
The default number of retries is still low enough that requests are
only going to be retried for a few seconds.
Instead of retrying for a few seconds, we should retry until the
request context times out.
This should reduce the occurence of #754
Mitigation for #754
**What is this PR about? / Why do we need it?*
[waitForVolume](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L804) has a checkTime of 1 minute but current AWS client only …
=> Aws client config: increase MaxRetries

pkg/driver/controller.go, pkg/driver/controller_test.go
Explicitly return specific message in this case, otherwise the cloud returns generic `The parameter iops must be specified for io1 volumes`, which mentions `iops`, but the parameter that the user needs to set is `IOPSPerGB`.
Fixes: #766
=> Fix error message when IOPSPerGB is missing in io1 volumes

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
Fix #749 
Upgrade livenessprobe to patch memory leak 
helm install in k8s cluster
=> Update livenessprobe image version from 2.1.0 to 2.2.0

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Fixes #754 
Delete volume if the driver don't know about the volume status after creation
Could see this log after denying DescribeVolume api call manually
```volume is deleted because it is not in desired state within retry limit```
Added unit test
=> delete leaked volume if driver don't know the volume status

charts/aws-ebs-csi-driver/templates/storageclass.yaml
not a new feature
adds a document separator for storageclass template file
tested using helm template
=> add a document separator for storageclass template file

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/statefulset.yaml, charts/aws-ebs-csi-driver/values.yaml
new feature
allows this driver to work in VPC behind proxy
tested in our environment
=> Allow setting http proxy and no proxy environment values

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
Feature
Provisioners frequently end up on the same instance/zone endangering reliability
Allow to constraint their spread
1. Inspected the generated Helm chart visually.
2. Ran `apply -f ... --validate --dry-run=server`
3. Rolled out the generated Helm chart in our dev cluster. 
4. Generated deployment manifest applied successfully. Resulting deployment:
```
$ kubectl -n kube-system get po -o wide | grep ebs-csi-controller
NAME                                                   READY   STATUS    RESTARTS   AGE     IP                NODE                           NOMINATED NODE   READINESS GATES
ebs-csi-controller-559dcccd59-5q2k7                    6/6     Running   0 …
```
=> Add ability to specify topologySpreadConstraints

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/NOTES.txt, charts/aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-provisioner.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-resizer.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshot-controller.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshotter.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/role-snapshot-controller-leaderelection.yaml, charts/aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-snapshot-controller.yaml, charts/aws-ebs-csi-driver/templates/statefulset.yaml
Override hardcoded `kube-system` namespace
Ability to run helm chart in another namespace, for example `kube-system` could be free out of any mutation or validation webhooks.
Should address https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/621
Deployed in `example` namespace without issues.
=> removed harcoded NAMESPACE from helm chart

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml
Fixes #548 
This change reuses the liveness probe endpoint for a readiness probe, so that the csi controller's status can be reported accurately. Currently, if the ec2 instance metadata is unavailable, the csi controller deployment reports as ready, tries to fetch the metadata, panics when it cannot, and then stops reporting as ready. With this change, the controller deployment will not report ready from the get-go, and as a result will not report an inaccurate status if the instance metadata is unavailable.
Manually tested this using both kubectl and helm. Applied a global network policy to block access to the ec2 instance metadata, then created an ebs csi driver …
=> Add readiness probe so controller does not report "Ready" prematurely

charts/aws-ebs-csi-driver/templates/node.yaml, deploy/kubernetes/base/node.yaml
Bug
See issue: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/747
Valid template
=> Removing prestop hook for node-driver-registrar

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/README.md
Continue from #775 
Fixes #588
Not tolerate NoSchedule effect and add default 300s tolerationSeconds to all the NoExecute taints.
As we discussed, will default to tolerateAllTaints for now, will disable this in next release.
=> add toleration time to NoExecute effect --- Enable in next release

hack/e2e/README.md, hack/e2e/kops.sh, hack/e2e/run.sh, hack/values.yaml
**What is this PR about? / Why do we need it?** Minor changes to make the scripts more configurable and usable by EFS driver. https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/354 
It seems like git read tree is the simplest way to consume these scripts from EFS. subtree is more complicated because hack/e2e is a subdirectory of this repo and not its own repo
**What testing is done?** CI of PR https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/354  and CI of this PR.
=> hack/e2e: Support passing helm values as values.yaml and make other similar files optional

hack/e2e/run.sh
**Is this a bug fix or adding new feature?** new
**What is this PR about? / Why do we need it?** Hard to debug CSI driver issues without CSI driver logs. Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/788
lolcally , didnt actually run tests just wanted to see if it prints the pods' logs.
```
###
#
###
#
I0312 00:23:39.970276       1 driver.go:68] Driver: ebs.csi.aws.com Version: v0.9.0
W0312 00:23:43.218861       1 metadata.go:136] Failed to parse the outpost arn: 
I0312 00:23:43.219139       1 driver.go:138] Listening for connections on address: &net.UnixAddr{Name:"/var/lib/csi/sockets/pluginproxy/csi.sock", Net:"unix"}
I0312 00:23:43.299546       1 controller.go:352] ControllerGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} …
```
=> Print csi plugin logs at end of e2e test

examples/kubernetes/static-provisioning/README.md, examples/kubernetes/static-provisioning/specs/example.yaml
**Is this a bug fix or adding new feature?** fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/784
=> Remove storageclass from static example

pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/node.go, pkg/driver/node_test.go
Feature
See #729. This is the first part where we start writing the label and also give priority to it when reading topology labels. This change is completely backward-compatible with no change in behavior as far as users are concerned.
Unit tests
Single AZ e2e (there was one failed case that should be unrelated, probably flake)
=> Add well-known topology label

charts/aws-ebs-csi-driver/templates/statefulset.yaml
- Fix to apply resource constraints to snapshot controller
- See #637 and #640 
- Updated resources for snapshot controller stateful set and deployed in EKS. Pods were deployed without any issues. Ran `kubectl get po -A -o json | grep -B 3 -i '"resources": {},'` to verify the resources have been properly populated to the pods.
=> Update snapshot controller resources

hack/e2e/run.sh
**What is this PR about? / Why do we need it?**  The logging change I added in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/789 is worthless if the test fails and script exits prematurely. Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-efs-csi-driver/370/pull-aws-efs-csi-driver-e2e/1372684986401951744
(Mixed feelings about bash right now but I don't want to literally go in a circle and revamp the scripts all over again :cry:)
/cc @ayberk
TODO for myself: cherrypick in to efs copy of these scripts.
=> Don't exit script prematurely if test fails

docs/README.md
bug
The external-provisioner does not treat `csi.storage.k8s.io/fstype` as case-insensitive. Update the documentation accordingly.
None :-)
=> csi.storage.k8s.io/fstype is case sensitive

tests/e2e/driver/ebs_csi_driver.go, tests/e2e/testsuites/testsuites.go
/bug
e2e tests assumes only one topology key, so checks are hardcoded with the first element of each slice. Due to the recent addition of the well-known label as topology key, these checks might fail based on the ordering of the slice. This PR fixes it.
Tested on my account and verified it works and does what I expect it to do.
=> Use the old topology key for e2e tests

deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
This is a bug about ecr deploy error kustomization file
If do not fix this error, we can not deployed with this kustomization file.
I have tested in my eks cluster.
=> fix deploy stable ecr error kustomization file

hack/e2e/run.sh
Fixes #804  
Add driver start time info during e2e test. so we have better understanding on driver's behavior. 
Set threshold as 20s for now, may adjust as we have more info.
=> Track driver deploy time in e2e test pipeline

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
Merge release v0.9.1 commit into master
=> release v0.9.1

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
Fixes issue #722
Allows setting environment variables in values. For example: 
```
controller:
extraVars:
AWS_STS_REGIONAL_ENDPOINTS: regional
```
I need this in order to run in an environment with no internet access
=> AWS EBS CSI Driver Helm chart to inject environment variables

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
=> release v0.10.0

docs/README.md
Warn users about migrating nodes without fully draining them of mounted
EBS volumes.
=> Warn users of migrating without draining

pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/node.go, pkg/driver/node_linux.go, pkg/driver/node_test.go
Fixes #812 
Add volume partition support when stage&publish volumes to sync with in-tree driver
unit test
e2e test
=> support volume partition

docs/example-iam-policy.json, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/validation.go, pkg/driver/validation_test.go, tests/e2e/pre_provsioning.go
Fixes #571
Update sample IAM policy to scope down the resource restriction. The sample IAM policy is still open enough to cover all driver use cases, dynamic provisioning/static provisioning/snapshot/volume resizing etc. 
It can be scope down further if above use cases are not apply to your cluster at all. (Like only allow driver to attach/detach the volume created by driver if you are not using static provisioning feature)
Add a new tag  `ebs.csi.aws.com/cluster` to identify all the resources created by driver.
e2e test/ unit test/ manually test
=> update IAM policy sample and add new driver level tag

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/mocks/mock_cloud.go, pkg/driver/sanity_test.go, tests/e2e/pre_provsioning.go
fixes #389 
the describeInstances API follows an eventual consistency model. the csi driver should handle the fact that it may get inconsistent responses from this API
manual testing trying to reproduce
=> handling describe instances consistency issue

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/csidriver.yaml, deploy/kubernetes/base/csidriver.yaml
Improvement
In this commit, we switch CSIDriver resources to the latest stable
apiVersion so to surpass warning messages on deploying and also prepare
chart for future k8s version where storage/v1beta1 will be removed.
Already deployed this change on k8s cluster v1.18+
=> [helm/CSIDriver] Switch to non-deprecated apiVersion

charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
**Is this a bug fix or adding new feature?** sidecar versions are different depending on installation method, fix it.
|||
|-|-| 
|csi-provisioner|v2.1.1| 
|csi-attacher|v3.1.0| 
|livenessprobe|v2.2.0| 
|csi-node-driver-registrar|v2.1.0| 
|csi-snapshotter (helm only https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/797)|v3.0.3|
|csi-resizer (helm only, update overdue, https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/797)|v1.0.0|
CI will test helm installation.
=> Bump/reconcile sidecar versions in helm/kustomize

docs/README.md
Update readme file to provide more info on driver options and tagging
=> Update readme file to provide more info on driver options and tagging

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml, cmd/main.go, cmd/options/server_options.go, pkg/cloud/aws_metrics.go, pkg/cloud/cloud.go, pkg/cloud/handlers.go
**Is this a bug fix or adding new feature?** fix https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/806
**What is this PR about? / Why do we need it?** This publishes API metrics equivalent to those that the ebs plugin/aws cloud provider embedded in kube-controller-manager publishes today, like describeinstances/describevolume call durations, error counts, and throttle error counts.
I'm not well-versed in how people intend to consume the metrics so this PR is barebones, for now it just exposes them over port 80 using "k8s.io/component-base/metrics/legacyregistry"
DIFFERENCES between my implementation and the cloud provider one:
- I implement a `Complete` handler and refer to request.Operation.Name when emitting metrics. As opposed to wrapping every call and referring to a custom …
=> Emit AWS API operation duration/error/throttle metrics

pkg/cloud/cloud.go
**What is this PR about? / Why do we need it?** not sure how https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/842 passed tests at all but an import is missing.
=> Fix missing import

pkg/cloud/metadata.go
We recently encountered a case where driver wouldn't use the outpost arn despite metadata being available. I'm adding more logging around it to help troubleshooting the issue in the future.
=> Add additional logging for outpost arn handling

examples/kubernetes/static-provisioning/specs/example.yaml
**What is this PR about? / Why do we need it?** fix from https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/423 . without this change, pvc may bind to default storageclass pv which is NOT intended!
=> Add empty StorageClasses to static example

Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller-poddisruptionbudget.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller-poddisruptionbudget.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/kustomization.yaml, deploy/kubernetes/base/node.yaml
fixes #512 
manually tested with kustomize and helm
=> add pod disruption budget for csi controller

hack/e2e/ebs.sh, hack/e2e/eksctl.sh, hack/e2e/kops.sh, hack/e2e/run.sh, hack/e2e/util.sh
**Is this a bug fix or adding new feature?** testing
**What is this PR about? / Why do we need it?** Would like to test the driver on eks in addition to kops. eksctl command is similar enough to kops that I think the easiest way is to add a short eksctl script (eksctl.sh) like kops.sh
implementation detail differences:
- eksctl doesn't have an equivalent to 'kops export kubecfg' to export kubeconfig and (re) set the current-context to the test cluster. I refactored the scripts such that they export kubeconfig to a file in the test dir instead of .kube/config so that it's easier to keep track of them and to avoid polluting .kube/config
- I haven't figured out yet how to patch eksctl clujster config to add node iam policies, I think first I will add an eks prow job and then work on adding …
=> Add eksctl support to e2e scripts

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
merge v1.0.0 commit back into master
=> release v1.0.0

charts/aws-ebs-csi-driver/templates/clusterrolebinding-csi-node.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/clusterrolebinding-csi-node.yaml, deploy/kubernetes/base/controller.yaml
fix
fixes naming mistake
manually testing now, will finish before merging
=> fix naming mistake in clusterrolebinding, expose env var to controller via downward api

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/csidriver.yaml, deploy/kubernetes/base/csidriver.yaml
Fixes #887
storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+;
CSIDriver is general available in storage.k8s.io/v1 since v1.19
Instead of using v1beta1 version for all helm deployment, check the kubeVersion first in helm deployment and use v1 for clusterVersion >=1.19 and v1beta1 for clusterVersion >=1.17 and < 1.19
Tested in 1.17, 1.18, 1.19 cluster
=> deploy CSIDriver object api version dynamically based on kubeVersion

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-csi-node.yaml, deploy/kubernetes/base/clusterrolebinding-csi-node.yaml
bug fix
fixes #883 
installed helm chart from before #882 was merged, then tried upgrading to this chart. seems to have worked fine.
=> rename node clusterrolebinding to make auto upgrade work

pkg/cloud/metadata.go
Bug fix
Follow-up PR to this previous PR that fixed instance metadata retrieval when the EC2 metadata service is unavailable:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/855
In our cluster configuration, we run this such that an in-cluster configuration is not available, as we do not give these pods a service account. However, the pods do have access to the EC2 metadata service, as we run the pods with `hostNetwork: true`. When the in-cluster configuration is unavailable, this cause a crash at startup that cannot be avoided, even when setting the `AWS_REGION` environment variable. 
Resolves https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/876 …
=> Only initialize the in-cluster kube client when metadata service is actually unavailable

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller-poddisruptionbudget.yaml, deploy/kubernetes/base/controller-poddisruptionbudget.yaml
bug fix
fixes #886 
removed the hardcoded namespace field and tried installing the driver in a custom namespace. the poddisruptionbudget was created in that namespace instead of kube-system
=> remove hardcoded namespace for pod disruption budget

deploy/kubernetes/base/poddisruptionbudget-controller.yaml, deploy/kubernetes/base/poddisruptionbudget-snapshot-controller.yaml
Bug fix.  These files got missed during a rebase of PR #856 
Files are missing from the customization manifests
Ensured the file names match those in the kustomization.yaml
=> Add pod disruption budgets that got missed in a rebase

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/snapshot-controller.yaml, charts/aws-ebs-csi-driver/values.yaml
Adds the feature requested in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/904
Many organizations use custom labels for a variety of purposes such as grouping metrics and setting affinity rules for other pods. This feature is also present in most of the stable eks-charts.
=> Support custom pod labels in Helm chart

Makefile, pkg/cloud/cloud.go
new feature
modifies the aws sdk client's useragent string to differentiate the ebs csi driver's requests
turned on debug logs and confirmed that user agent had new string appended
=> add custom useragent suffix

pkg/driver/controller.go
No expansion on the node should be necessary if device is of type raw block
=> Skip volume expansion if block node

pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/node.go, pkg/driver/node_test.go
bug fix
fixes https://github.com/kubernetes/kubernetes/issues/102248
modified testing and verified
=> remove WellKnownTopologyKey from PV Topology

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/snapshot-controller.yaml
Bug fix.
This fixes the bug introduced in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/905 where `podLabels` did not have consistent case throughout the Helm chart.
`helm template` was successfully evaluated when `podLabels` was set for all three pod types.
=> Fix podLabels case in Helm chart

pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/internal/inflight.go
Fixes #918 
Per [spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#concurrency), there is no more than one call “in-flight” per volume at a given time. 
Add another layer of protection on the driver to make sure apis are idempotent.
e2e test on k8s 1.19
=> update inFlight cache to avoid race condition on volume operation

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, hack/values.yaml
**What is this PR about? / Why do we need it?** I reduced to 2 in a recent PR but that was lazy, it is useful to be configurable especially for our CI. 
copied from efs. https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L43
**What testing is done?**  ~~ will check PR CI results to see if logLevel: 5 actually took effect.~~ logLevel: 5 works
=> helm chart configurable log verbosity

Makefile, tests/e2e-kubernetes/manifests.yaml
**What is this PR about? / Why do we need it?** to opt-in to (future) e2e tests from kubernetes/kubernetes, capabilities shoudl be accurate. 
=> Update driver capabilities

pkg/driver/node.go, pkg/driver/node_test.go
Bugfix
By default, XFS does not allow mounting two devices that have the same UUID of the XFS filesystem. As result, it's not possible to mount a volume + its restored snapshot.
Therefore disable UUID check in XFS using a mount option.
Tested with https://github.com/kubernetes/kubernetes/pull/102538
=> Disable uuid checks on XFS

Makefile, charts/aws-ebs-csi-driver/templates/node.yaml, deploy/kubernetes/base/node.yaml, hack/e2e/eksctl.sh, hack/e2e/kops.sh, hack/e2e/run.sh, hack/eksctl-patch.yaml, hack/values_eksctl.yaml, pkg/cloud/metadata.go, pkg/cloud/metadata_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/node.go, tests/integration/setup_test.go
**Is this a bug fix or adding new feature?** test
**What is this PR about? / Why do we need it?** test for the case where instance metadata is disabled for pods. EKS specifically recommends this. In this case, only pods with hostNetwork true will have access to instance metadata.
To create the environment, use eksctl --disable-pod-imds.
The expected behavior is that in lieu of instance metadata
- the controller: should get credentials from IAM for SA. This gets configured via eksctl. 
- the node: should get instance info from k8s API. This gets configured by our helm chart. The node should NOT need hostNetwork true anymore because the sole reason that was there was so it could bypass `disable-pod-imds` to touch instance metadata.
TODO for future:
a  test case where instance metadata is …
=> Add test-e2e-external-eks make rule that tests EKS with pod instance metadata disabled. Remove hostNetwork from DaemonSet

charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
**Is this a bug fix or adding new feature?** this flag has been in external-provisioner for a long time now, we should default it true so that volumes get created with pvc/pv tags kubernetes.io/created-for  https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/9f4ce44bd3c1d454177bd97b12170b6f95bfafde/pkg/driver/constants.go#L89
**What is this PR about? / Why do we need it?** people want tags https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180
=> Default extra-create-metadata true so that volumes get created with pvc/pv tags

pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go
**What is this PR about? / Why do we need it?** users (namely kops) may have policies ocnfigured for their KCM such that KCM can only attach/detach/create/delete volumes with this tag. If user enables  migration, CSI provisions volume, and then user later disables migration, the tag must bep resent so that KCM can attach/detach/create/delete  it. Details:https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/927#issuecomment-858034205
TODO: I'll do a manual test to sanity check the tag actually shows up. we don't have an automatic tagging e2e test , could be useful (i.e. a test that sets extraTags, clusterID, and checks tags are present in AWS API)
=> Add KubernetesCluster tag to provisioned volumes when cluster-id set

Makefile, hack/e2e/ecr.sh, hack/e2e/eksctl.sh, hack/e2e/kops.sh, hack/e2e/run.sh
**What is this PR about? / Why do we need it?** this is part of the effort to get eksctl test CI in every PR.
To get Kubernetes API access to an EKS cluster you need to either be a) cluster creator or b) added to the aws-auth ConfigMap. Of course if you do not have Kubernetes API access in the first place then you can't edit the configmap, so the cluster creator has to do some bootstrapping. This PR enables the cluster creator to bootstrap one additional EKSCTL_ADMIN_ROLE with admin access to the cluster.
By contrast, with kops, if you have AWS API access to the kops cluster config in S3, then you can give yourself Kubernetes API access.
So why do we need one extra admin besides the cluster creator in the first place...I don't want to divulge …
=> Grant EKSCTL_ADMIN_ROLE admin access to eksctl clusters

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml
**What is this PR about? / Why do we need it?** https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/937 updated the toplevel extra-create-metadata but not the controller.extra-create-metadata . the top level is the one we want to deprecate. In any case they should match to avoid confusion.
=> Default controller.extra-create-metadata true so that volumes get created with pvc/pv tags

docs/README.md, docs/example-iam-policy.json, hack/kops-patch.yaml, hack/values.yaml
**What is this PR about? / Why do we need it?**  The example policy is a minimal restrictive example so it's not guaranteed to work in all scenarios... but there are is at least one* notable scenario where it breaks, so we should update* the example and documentation to account for this scenario:
- if migration is enabled, the policy restricts csi from deleting volumes that were created by KCM pre-migration
- to fix this, i've edited the example policy such that it has permission to delete volumes with tag `"aws:RequestTag/kubernetes.io/cluster/<ID of the Kubernetes cluster>": "owned"`. also add permission to create although it's not totally necessary, maybe redundant, but to be consistent.
=> Update example policy, use it in tests, and document it

Dockerfile.windows, Makefile, charts/aws-ebs-csi-driver/templates/node-windows.yaml, examples/kubernetes/windows/README.md, examples/kubernetes/windows/specs/windows.yaml, pkg/driver/mount.go, pkg/driver/mount_linux.go, pkg/driver/mount_test.go, pkg/driver/mount_windows.go, pkg/driver/node.go, pkg/driver/node_linux.go, pkg/driver/node_windows.go
**Is this a bug fix or adding new feature?** /feature
**What is this PR about? / Why do we need it?** In-tree EBS driver supports windows, so too must CSI in case an in-tree EBS volume gets migrated to CSI
I will add build/push job to CI in a separate PR. Since windows images are big, don't want to prematurely upload stuff to registry.
NOTE: this requires a not-yet-released  version of csi-proxy with changes from
- https://github.com/kubernetes-csi/csi-proxy/pull/116
- https://github.com/kubernetes-csi/csi-proxy/pull/126
- https://github.com/kubernetes-csi/csi-proxy/pull/127
I will detail this in README so that my test results are reproducible.
TODO:
Windows mount/unmount works, data persists.
I will let CI test that my refactoring has not broken Linux.
``` …
```
=> Implement Windows NodePublish/Unpublish

Makefile, deploy/kubernetes/base/clusterrolebinding-attacher.yaml, deploy/kubernetes/base/clusterrolebinding-csi-node.yaml, deploy/kubernetes/base/clusterrolebinding-provisioner.yaml, deploy/kubernetes/base/clusterrolebinding-resizer.yaml, deploy/kubernetes/base/clusterrolebinding-snapshot-controller.yaml, deploy/kubernetes/base/clusterrolebinding-snapshotter.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/base/rolebinding-snapshot-controller-leaderelection.yaml
This reverts commit 3716e5ef3175bdbb6745018f9646957b5a635eac.
**What is this PR about? / Why do we need it?** see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/947
=> release-1.1: Revert kustomize changes

Makefile, deploy/kubernetes/base/clusterrolebinding-attacher.yaml, deploy/kubernetes/base/clusterrolebinding-csi-node.yaml, deploy/kubernetes/base/clusterrolebinding-provisioner.yaml, deploy/kubernetes/base/clusterrolebinding-resizer.yaml, deploy/kubernetes/base/clusterrolebinding-snapshot-controller.yaml, deploy/kubernetes/base/clusterrolebinding-snapshotter.yaml, deploy/kubernetes/base/rolebinding-snapshot-controller-leaderelection.yaml
This reverts commit `3716e5ef3175bdbb6745018f9646957b5a635eac`
Fixes #946 946
Issue described in ticket
=> Revert "Fix kustomize RBAC bindings to have namespace kube-system"

docs/README.md
**What is this PR about? / Why do we need it?**  for instance profile to work, applications like ebs need to be able to retrieve the instance profile creds from instance metadata.
=> Clarify that using instance profile for permission requires instance metadata access on

Makefile, hack/e2e/run.sh, hack/values.yaml, tests/e2e-upgrade/README.md, tests/e2e-upgrade/e2e_test.go, tests/e2e-upgrade/kops.go
**What is this PR about? / Why do we need it?** see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/920. Need to make sure toggling migration on/off works correctly.
For kops, toggling is easy by editing the cluster spec, that's what this test does
For EKS, ATM it's impossible to get a cluster with migration enabled in the first place.
I am testing it locally.
```
ginkgo -nodes=1 -v -- --state s3://aws-efs-csi-driver-e2e --name test-cluster-41400.k8s.local --delete-namespace=false --max-nodes-to-gather-from=0
```
having this test as part of CI is not a criteria for enabling CSIMigrationAWS on by default, but at least it has to be manually run. It's very slow (even with just 1 master + 1 node instance) so …
=> Add migration upgrade/downgrade test

charts/aws-ebs-csi-driver/templates/controller.yaml
bug fix
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/942
locally, yes
=> [helm-chart] csi-snapshotter in ebs-csi-controller now checks for enableVolumeSnapshot before including it in containers

hack/e2e/eksctl.sh, hack/e2e/run.sh
**What is this PR about? / Why do we need it?** eks job is failing, the latest release 0.55.0 has a bug "Error: --instance-types is only valid with managed nodegroups (--managed)" https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-aws-ebs-csi-driver-external-test-eks that is fixed in 0.56.0-rc.1. Could also revert to 0.54.0 but it doesn't really matter IMO, may as well try the newest.
**What testing is done?**  watch CI job
=> Download fixed version of eksctl to avoid bugs

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/internal/inflight.go
**Is this a bug fix or adding new feature?** bug fix 
**What is this PR about? / Why do we need it?** release the fix merged here https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/924#issuecomment-872303474 
I didn't see other fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/release-1.1...master worth cherry-picking in to 1.1.x branch. They are mostly eks e2e testing changes and helm chart-specific fixes which can be released separately via helm chart releases. (Which I am adding a CHANGELOG for btw.) Plus the windows refactor and the instance metadata refactor which I don't see the point in cherry-picking.
windows support in particular will probably come in 1.2.0 to signal it, or if nothing else because it's been a few months and we're due for another minor …
=> release-1.1: Release 1.1.1 and chart v1.2.4 with inFlight cache race fix

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
**What is this PR about? / Why do we need it?** cherrypick of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/958 onto master branch for housekeeping, doc update, andh elm chart release.
=> Release v1.1.1 and chart v1.2.4

Makefile, hack/e2e/run.sh, hack/values.yaml
In preparation for removing snapshot controller installation from our helm chart https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/965, try using other  methods to install it as a prerequisite.
- kops e2e tests:
- ~upgrade kops to 1.21.0 and add   `snapshotController.enabled: true` to hack/kops-patch.yaml (the resources are embedded in kops, copied from external-snapshotter repo)~ same as below
- eks e2e tests:
- kubectl apply the resources from external-snapshotter github repo.
=> Install snapshot controller independently of helm for e2e tests

hack/e2e/README.md
since I am trying to reuse these scripts in efs and fsx repo (in poor imitation of csi-release-tools) i want to document how to work with them.
These commands generated patch that applied cleanly you can see in first commit here:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/510
=> Add how to consume new hack/e2e scripts in other repos (efs/fsx)

.gitignore, docs/README.md, examples/kubernetes/dynamic-provisioning/README.md, examples/kubernetes/snapshot/specs/classes/snapshotclass.yaml, examples/kubernetes/snapshot/specs/snapshot-import/README.md, examples/kubernetes/snapshot/specs/snapshot-import/static-snapshot/volume-snapshot-content.yaml, examples/kubernetes/snapshot/specs/snapshot-import/static-snapshot/volume-snapshot.yaml, examples/kubernetes/snapshot/specs/snapshot/snapshot.yaml
…hot examples
No, made few changes to the updates in the repository.
1. Changed the release version from 0.10 to 1.1 for deploying the CSI Driver.
2. Updated the Api version in the snapshot example yaml files from v1beta1 to v1.
It was a document update. No testing required.
=> Updated README.md and changed the version in snapshot example

charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/values.yaml
Issue fix #975 
It is about providing an option for the user to enable/disable the csi-node-windows daemon-set to run. By default, it is set to 'false'. This was needed because node-windows daemon set starts by default irrespective of the operating system it is running on.
Tried to install the helm chart after the changes, it installed the CSI Driver and node-windows daemon set was started based on the boolean value in values.yaml
=> Updated default setting of windows daemon set

charts/aws-ebs-csi-driver/Chart.yaml
No,  Bumped up the the helm chart version
Change in helm chart version because, the PR #978 after merge had thrown message "Error: error creating GitHub release helm-chart-aws-ebs-csi-driver-2.0.0: POST https://api.github.com/repos/kubernetes-sigs/aws-ebs-csi-driver/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]". Since the changes were done in the helm chart in PR #978, apparently the helm chart version should be also be increased.
No testing required.
=> Increased the helm chart version

Dockerfile
**What is this PR about? / Why do we need it?** trigger another build. for al2, this time make sure update packages. for debian, make sure we are using a newer base image that roughly matches whatever k/k is using (although nowadays most k/k images are distroless) https://github.com/kubernetes/release/tree/master/images/build/debian-base
BTW I am probably going to soon be removing debian base and going back to just maintaining amazonlinux base. We wanted to push debian because users are probably already using debian base images in their cluster anyway (kube-proxy) and they don't want to risk CVEs from both debian images and amazonlinux images in their cluster. But it's harder on maintainers to keep up pushing builds for both which is itself a …
=> Update base images: yum update al2, bump debian tag

CHANGELOG-0.x.md, Dockerfile, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
cherry-picking helm/doc changes from release-1.1 branch to master.
we released 1.1.2 with base image changes for cve, and then 1.1.3 right after cuz of an issue with the ECR build.
/hold
=> Release 1.1.3

CHANGELOG-0.x.md, Makefile, docs/README.md
Release aws-ebs-csi-driver v1.2.0
part 1 - build gcr/ecr image and update Change log
=> release v1.2.0 - part 1

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
Driver v1.2.0 release part 2:
Update kustomize and helm to use latest driver image with tag v1.2.0
```
gcr image repo:
gcloud container images list-tags gcr.io/k8s-staging-provider-aws/aws-ebs-csi-driver --format='get(tags, digest)' --filter='tags:v1.2.0 AND tags!~rc.\d'                                 gcloud 16:10:20
v20210728-v1.2.0	sha256:25ece67112a267a2ccd6dc870b0dac4091cbcc2dc835e15c1f9492d6489ea906
v20210728-v1.2.0-amazonlinux	sha256:c1d7f2d06901c145a734cb97b444063ab9344b79a1e379b327014ecece4bd6b9
ecr repo:
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v1.2.0
=> release v1.2.0 - part 2

docs/RELEASE.md
**What is this PR about? / Why do we need it?** fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/994.
This brings kustomize in line with helm, we should not be "releasing" a kustomize template until after the images it references actually exist!
Helm works because we only merge the main branch changes and release helm chart after image verification. But, for kustomize the "release" is done in the release branch, so we have to make a post-release PR.
Basically: 
Before:
- release-x PR
- verify images
- master branch PR
- 
After:
- release-x PR 1
- verify images
- release-x PR 2
- master branch PR
- 
=> Update kustomize templates only after verifying images are available in registries

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/node.yaml
This PR adds the ability to configure the node update strategy and uses the chart app version for the image tag.
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/985.
With the default update strategy the more nodes added to the cluster the longer it takes to upgrade, this PR makes this customisable and sets the default to the 10% unavailable strategy used by the aws-vpc-cni and the EKS kube-proxy daemonsets.
Helm template output validated.
=> [chart] Node update strategy & auto driver image tag

.github/workflows/container-image.yaml
build is failing. There is no "library" in the registry name https://github.com/kubernetes-sigs/aws-ebs-csi-driver/runs/3256645072
**What testing is done?** locally can pull from docker.io/amazon but not docker.io/library/amazon, the former is the correct one.
=> Fix github build failing because of wrong docker hub registry name 

hack/prow.sh
build is failing. It seems like the build container already sets IMAGE to gcr.io/k8s-testimages/gcb-docker-gcloud:v20200421-a2bf5f8 so the new Makefile rule tries pushing to this invalid tag: "invalid tag "gcr.io/k8s-testimages/gcb-docker-gcloud:v20200421-a2bf5f8:v20210805-helm-chart-aws-ebs-csi-driver-2.0.4-3-gf30d7f8e-linux-amd64-amazon": invalid reference format". The fix should be to override IMAGE for the `make` call. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1423392293334814720
Can't verify locally, will check if build succeeds in master branch after this merges.
=> Fix gcr prow build failing because of IMAGE variable collision

docs/RELEASE.md
**Is this a bug fix or adding new feature?** docs
**What is this PR about? / Why do we need it?** If we are going to do two commits to the release branch per release,
1. to trigger the image build
2. to update the kustomize yaml to refer to the image
it makes sense to me that helm yaml updates should go into step 2, not 1.
=> Update helm chart alongside kustomize, after images have been pushed, for consistency

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
This PR adds the ability to configure the controller update strategy.
With the default update strategy and tightly mapped zones the surge pods cause issues.
Helm template output validated.
=> [chart] Add controller strategy

cloudbuild.yaml
**What is this PR about? / Why do we need it?** doing some wack a mole . the new build makle rule almost succeeded but failed at the manifest annotate step with `unknown flag: --os-version` https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1425539295917117440 . This new image version has a new docker version with the flag.
```
$ docker run -it -e DOCKER_CLI_EXPERIMENTAL=enabled --entrypoint docker gcr.io/k8s-testimages/gcb-docker-gcloud:v20210722-085d930 manifest annotate --help
Unable to find image 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20210722-085d930' locally
v20210722-085d930: Pulling from k8s-testimages/gcb-docker-gcloud
Digest: …
```
=> Fix gcr prow builld failing because docker missing --os-version

pkg/cloud/aws_metrics.go, pkg/driver/mocks/mock_mount.go, pkg/driver/mount.go, pkg/driver/node.go, pkg/driver/node_linux.go, pkg/driver/node_test.go, pkg/driver/sanity_test.go, pkg/mounter/safe_mounter_unix.go, pkg/mounter/safe_mounter_windows.go
Cherry pick of #1019 on release-1.1.
#1019: Added Mount Idempotency
=> [release-1.1] Automated cherry pick of #1019: Added Mount Idempotency

pkg/cloud/aws_metrics.go, pkg/driver/mocks/mock_mount.go, pkg/driver/mount.go, pkg/driver/mount_linux.go, pkg/driver/mount_windows.go, pkg/driver/node.go, pkg/driver/node_linux.go, pkg/driver/node_test.go, pkg/driver/node_windows.go, pkg/driver/sanity_test.go, pkg/mounter/safe_mounter_unix.go, pkg/mounter/safe_mounter_windows.go
Cherry pick of #1019 on release-1.2.
#1019: Added Mount Idempotency
=> [release-1.2] Automated cherry pick of #1019: Added Mount Idempotency

pkg/cloud/cloud.go
fixes #1038 
hash the volume name using sha-256 in case the name is longer than 64 characters.
manually tested that a volume could be created with new token
=> hash volume name to get client token

pkg/driver/mount_windows.go
**What is this PR about? / Why do we need it?** as seen in our master branch CI https://github.com/kubernetes-sigs/aws-ebs-csi-driver/runs/3508198636  the windows build fails.
this was not cauhgt by PR CI because no PR CI exercises the windows build, I've assigned myself a task to fix this: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1046
~After this merges, what I plan to do is retag 1.1.4 and 1.2.1 to trigger another image rebuild. It is not pretty but, since no images for 1.1.4 or 1.2.1 got pushed to docker hub/gcr there is no harm.~
edit: 1.1.4 and 1.2.1 failed for a different reason than master branch, they timed out unexpectedly after 1hr: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1 …
=> Fix windows build IsCorruptedMnt not implemented

cloudbuild.yaml
**What is this PR about? / Why do we need it?** This is a bandaid fix to get 1.1.4 out. Our build time has been steadily increasing and now it consistently breaches the 1h timeout. https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images. It was already very slow before compared to github actions (30-45 mins vs 15mins) so it will need to be fixed, tracking it here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1048
for comparison master branch is still pretty slow at 40 mins but it building for windows in addition to x86 and arm! So one option to solve https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1048 is to backport the Makefile/Dockerfile/build changes to release-1.1 branch. …
=> [release-1.1] Increase prow timeout to 1h15m

docs/RELEASE.md
=> Fix spacing in RELEASE.md

pkg/cloud/metadata.go, pkg/cloud/metadata_test.go
/kind bug
This fixes volume limits on nodes that dont have the EC2 metadata endpoint available.
kOps is experiencing [volume limit test failures](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-aws-ebs-csi-driver-irsa/1436862817599754240) and I believe this is because the limit is being set incorrectly.
[The nodes are t3.mediums](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-aws-ebs-csi-driver-irsa/1436862817599754240/artifacts/cluster-info/nodes.yaml) which should have a [limit of 28 volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html).
[The csi-node pod logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-aws- …
=> Recognize instance-type node label when EC2 metadata isn't available

pkg/cloud/cloud.go
Cherry pick of #1041 on release-1.2.
#1041: hash volume name to get client token
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
=> [release-1.2] Automated cherry pick of #1041: hash volume name to get client token

pkg/driver/mount_windows.go
Cherry pick of #1047 on release-1.2.
#1047: Fix windows build IsCorruptedMnt not implemented
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
=> [release-1.2] Automated cherry pick of #1047: Fix windows build IsCorruptedMnt not implemented

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
Signed-off-by: Joseph (Jy) Yaworski <jyaworski@carotid.us>
Fixes #1040 
Adds support for image.pullPolicy to another container previously hardcoded
`ct lint` passes validation.
=> [chart] Support image.pullPolicy for csi-resizer image

.github/workflows/container-image.yaml, cloudbuild.yaml, hack/prow.sh
**What is this PR about? / Why do we need it?** https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1062 just got merged which was a cherry-pick of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/957.
I forgot that https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/957 on its own didn't work, it needed a few iterations of fixes: #1016, #1017, and #1020. Then after #1020 the builds passed: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/runs/3376750521, https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1428483776043814912 
So of course, I need to cherry-pick these 3 PRs alongside 957. Whoops!
=> [release-1.2] Fix gcr prow and github builds: cherry-pick of #1016, #1017, and #1020

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
New feature.
Default `fstype` is hardcoded as ext4, users may wish to override it to use other filesystems instead of specifying them explicitly in the StorageClass resource.
Helm templating + test deploy on k8s cluster.
Change is backwards compatible, as the default is still `ext4`
=> Allow default fstype to be overriden via values.yaml

CHANGELOG-0.x.md, Makefile, docs/README.md
**What is this PR about? / Why do we need it?** This release is to mark the start of the image in ECR being multi-arch/os just like the image in GCR/Docker Hub. EKS documentation points to the image in ECR and EKS supports linux/arm instances + windows/amd instances so the image in ECR ought to run on such instances. Anyway, it has been a source of confusion how different registries host different variations of the driver image so this release should make it so all registries are equal and facilitate the deprecation of GCR/Dcoker Hub as announced in v1.1.3.
=> Release v1.3.1

deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
Feature
* Set `csi-snapshotter` and `csi-resizer` images in `kustomization.yaml` like the others
* Add their Public ECR counterparts in ECR overlay
Deployed images from Public ECR on EKS
=> deploy: Add resizer and snapshotter images to kustomization

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/_helpers.tpl
Bugfix
Get rid of `DEPRECATION WARNING: --extra-volume-tags is deprecated, please use --extra-tags instead`
The chart has been deployed to own EKS cluster
=> Replace deprecated arg "--extra-volume-tags" by "--extra-tags"

charts/aws-ebs-csi-driver/templates/controller.yaml
Rather a bug fix/
This PR fixes the inability to deploy snapshotter in environments featuring storage.io API at v1beta1
Deployed to an number of EKS clusters at 1.18 and having snapshot.storage.k8s.io/v1beta1 CRD deployed; confirmed the snapshotter to work as expected.
=> [chart] Allow installing snapshotter with storage.io API v1beta1

deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
New feature.
Address @wongma7's comment on PR #1098: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1098#discussion_r733131616.
This will allow ECR Private to be used when pulling images. Advantages of this method include being able to use the ECR Endpoint and to target a specific AWS Region where the image will be pulled from.
I decided to use `ecr` as the overlay for ECR Private and `ecr-public` as the overlay for ECR Public for it to match the identifiers of both services used on their domains and when writing IAM policies for them.
Check that all images referenced on Kustomization are publicly available.
It's important to note that …
=> add ecr-private kustomize overlay

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md, examples/kubernetes/windows/README.md
=> Release v1.5.0

deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
New feature.
Remove tag override from ECR overlay. The GCR overlay now has the same version of the CSI Driver as the other overlays, so this patch on the tag is not needed any longer.
This will also help to keep the same version of the CSI Driver synced between all overlays.
Run `kustomize build` and check the output is the same as before.
=> remove tag override from ecr overlay

Dockerfile, Makefile
**What is this PR about? / Why do we need it?** The Makefile->Dockerfile->Makefile recursion is pretty confusing. I think it would be clearer if:
1. the Makefile continues to use OS and ARCH.
2. then when the Makefile invokes Dockerfile, it passes --platform which magically sets the args TARGETOS and TARGETARCH: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope. This means build-arg OS and build-arg ARCH are redundant, so I'm removing them.
3. then when the Dockerfile invokes Makefile, it sets OS to TARGETOS and ARCH to TARGETARCH
`make image` still works as intended.
```
#11 [builder 4/4] RUN OS=linux ARCH=amd64 make linux/amd64
#11 0.182 CGO_ENABLED=0 GOOS=linux …
```
=> Use TARGETOS/TARGETARCH in Dockerfile but OS/ARCH in Makefile

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
=> [chart] Update kubernetes-csi/livenessprobe

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
Bug fix for EKS kubernetes versions below `1.19`.
Your [compatibility matrix ](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/v1.2.1#kubernetes-version-compatibility-matrix)says that appVersion 1.2.1 of the Helm Chart supports Kubernetes versions 1.17 and above. In EKS this [does not seem to be the case](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#run-the-application-as-a-non-root-user).
We are running appVersion 1.2.1 of the `aws-ebs-csi-driver` on EKS Kubernetes `v1.18` and encountered the following error when the controller attempted to mount an EBS volume:
```
error listing AWS instances: "WebIdentityErr: failed fetching WebIdentity token: \ncaused by: …
```
=> Add support for securityContext in controller

pkg/driver/node_linux.go, pkg/driver/node_linux_test.go, pkg/driver/node_test.go
Bug fix further improving on https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1082
- It allows the `/dev/xvdXX` symlinks to continue to function, but properly identifies them as nvme devices based on the `/dev/nvme` prefix
- No matter what kind of symlinking is setup, it will always find the canonical block device because all symlinks are always resolved now. This means that if some crazy non-nitro system had `/dev/xvdb` symlinked to `/dev/sdb`, even that would work correctly.
- nvme devices resolved via the `/dev/xvdXX` symlinks will now correctly handle appending the partition string
- The `/dev/disk/by-id` fallback continues to work correctly
- It fixes logging for `node_linux.go`: …
=> Fix canonical nvme device resolution in more cases

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
**What is this PR about? / Why do we need it?** cherry-pick https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1124 (and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1133) on 1.5 branch because that's where stable kustomize overlay lives i.e. where kustomize installation instructions point to
=> [release-1.5] add ecr-private kustomize overlay and Update ECR sidecars to 1-18-13

.github/workflows/release.yaml, docs/RELEASE.md
This is a hack to "hide" the release until images are ready. Right now, we cut a github release the moment a a tag is pushed. However, there is a period after that during which images need to be scanned and possibly rebuilt. Therefore we should treat the release as "pre-release" until we actually have a working image that passes tests/scans etc., at the end of the release process.
=> Set prerelease=true for new releases before images are ready

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
=> v1.5.1 post-release

deploy/kubernetes/base/clusterrole-snapshotter.yaml
Remove un-necessary access to secrets by the external-snapshotter-role
External-snapshoter does not require access to secrets for its functionality, keep the access to all secret values may cause other security issues.
=> Update cluster role configuration for external snapshotter

pkg/cloud/metadata.go, pkg/cloud/metadata_ec2.go, pkg/cloud/metadata_interface.go, pkg/cloud/metadata_k8s.go, pkg/cloud/metadata_test.go, pkg/cloud/mock_metadata.go, pkg/cloud/volume_limits.go, pkg/driver/node.go, pkg/driver/node_test.go
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1139
This commit fixes the `getVolumesLimit` function.
Previously, the volume limit for Nitro instances was based off of a
regex. This regex is insufficient for the wide variety of Nitro
instances that AWS supports today.
Nitro instances share attachments with ENIs and NVMe instance
stores.
The number of attached ENIs is queried through IMDS, against the
`network/interfaces/macs` endpoint.
The number of already attached block devices is also queried through
IMDS, against the `block-device-mapping` endpoint.
Currently, IMDS does not provide a way to query NVMe instance store
volumes. So, all instances that support NVMe instance …
=> Fix nodeService.getVolumesLimit() adding more instance types

pkg/mounter/safe_mounter_windows.go
- Customers can encounter this bug when attempting to mount a disk with offline status on a Windows node, resulting in pods being perpetually stuck in the ContainerCreating stage. #1090 
- This bug is fixed by ensuring the disk is online before being mounted using the CSI-Proxy API.
1. Build and upload container images to a registry.
2. Change the image in the helm chart.
3. Test mounting functionality using the new helm chart.
=> Fix windows mounting bug-1090

Makefile, hack/e2e/run.sh
Bug fix
Command `go get` in Makefile and test script deprecated
Unit test passed
=> Update deprecated command `go get`

cmd/main.go, cmd/options/controller_options.go, docs/README.md, docs/TAGGING.md, go.mod, pkg/cloud/cloud.go, pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/driver.go, pkg/driver/validation.go, pkg/driver/validation_test.go, pkg/util/template/funcs.go, pkg/util/template/template.go, pkg/util/template/template_test.go
/kind feature
This commit adds tagging support (w/ string interpolation) through StorageClass.parameters.
For more information about the design, refer to https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1190 and the markdown file in `docs/`. 
Also, see #180.
Unit tests
e2e test
Manual testing by creating volumes specified with tags through StorageClass.parameters.
=> Adding tagging support through StorageClass.parameters

charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml
This is an API upgrade PR.
This is a PR to upgrade PDB api version for kubernetes 1.21+
The policy/v1beta1 api version will not be supported after kubernetes 1.25+. So we need to upgrade this version.
Use policy/v1 for k8s 1.21+, to avoid displaying any warning of deprecated api version.
This PR is related to below issue:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1184
Tested on different kubernetes version in minikube.
=> Upgrade PodDisruptionBudget api version for kubernetes 1.21+

Makefile
- Bug fix
- The `os.version` is being incorrectly set which makes the image not OCI compliant and thus incompatible with containerd. The `os.version` on Windows should be a 4-part string similar to 10.0.14393.1066. Reference: https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/config.go#L100
- The current annotate overrides base image values, unnecessarily.
- Built images and verified description is correct with `docker manifest inspect`.
=> Ensure image OCI compliance

examples/kubernetes/resizing/manifests/pod.yaml, pkg/driver/constants.go, pkg/driver/mock_mount.go, pkg/driver/mount.go, pkg/driver/mount_linux.go, pkg/driver/mount_windows.go, pkg/driver/node.go, pkg/driver/node_windows.go, pkg/driver/sanity_test.go, pkg/mounter/safe_mounter_windows.go, pkg/resizefs/resizefs_windows.go
- New feature
- When attempting to resize a volume on Windows by editing the PVC, you will encounter the error: "Resize is not supported for this build".
- In the current implementation, the [NodeExpandVolume](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/a304d3eaa3a246c630a56551005e6ee630c3800c/pkg/driver/node.go#L280) function in the node service is not platform agnostic because it uses the mount-utils package to resize the file system. The mount-utils package does not implement the [Resize](https://github.com/kubernetes/mount-utils/blob/6e81bcc03fc8c22aa460c3c4bd32a7ad602abd6c/resizefs_unsupported.go#L39) function for windows …
=> Add volume resizing support for windows

Makefile
**Is this a bug fix or adding new feature?** /feature
**What is this PR about? / Why do we need it?** 
When building image, always run `yum update -y` and avoid using whatever amazonlinux image/layer is in the cache because it might be outdated.
--no-cache-filter requires buildx 0.8.x which just came out in March https://github.com/docker/buildx/releases/tag/v0.8.0
there is another flag --no-cache that is available in earlier versions but I DON'T want to use that because it means that the windows layers don't get cached and those take a LONG time to build.
We need to build new images frequently to keep up with CVEs in amazonlinux image. At least until we switch to a "minimal" image that has less surface area for CVEs.
`make image`  works and yum update -y is …
=> Use docker buildx 0.8.x --no-cache-filter to avoid using cached amazonlinux image

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml
It's a bug fix.
Some namespaced resources has namespace
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/0fbd9f793c2da68abcdce991e045c0d72675e0e8/charts/aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml#L11
where other doesn't
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/0fbd9f793c2da68abcdce991e045c0d72675e0e8/charts/aws-ebs-csi-driver/templates/node.yaml#L2-L6
Those resources without namespace are created in the default namespace where other resources are created in release namespace. This caused confusions when the `default` namespace is missing where helm says the resources is supposed to be deployed in a different namespace. This is what I'm seeing from …
=> Add namespace for namespaced resources in helm chart

cloudbuild.yaml
/kind bug
cloudbuild is failing because the gdb-docker-gcloud image uses buildx v0.7.0, which doesn't support the `--no-cache-filter` argument (v0.8.0). Updating the image to the latest version which uses buildx v0.8.0.
=> Update gcb-docker-gcloud to latest

Dockerfile, Makefile
- Stop building for Windows 2004 which has reached EOL for all editions.
- Build ltsc2019.
- Deployed CSI driver with helm chart using new ltsc2019 image.
=> Replace Windows 2004(EOL) with ltsc2019

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
- Bug Fix: #1235 
- The IOPS parameter, defined in the StorageClass.parameters, is not picked up by the driver when the volume type is not defined (i.e. defaults to gp3). 
- Create a StorageClass without a volume type but with IOPS
```
apiVersion: storage.k8s.io/v1
metadata:
name: test
parameters:
iops: "6000"
provisioner: ebs.csi.aws.com
```
- Provision a volume with this StorageClass.
```
k apply -f claim.yaml
```
- You'll see that the IOPS values is not honored in the volume created. 
```
% aws ec2 describe-volumes --volume-id vol-085b747b34dd7f330 --query 'Volumes[0].[Iops, VolumeType]'
[
3000,
"gp3"
]
```
=> Fix IOPS parameter bug when no volume type is defined

hack/e2e/eksctl.sh
- Bug fix
- Temporarily fix CI failing due to `error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"`.
until this PR gets merged: https://github.com/weaveworks/eksctl/pull/5287
- CI passing
=> Temporarily fix CI

hack/e2e/eksctl.sh
Cherry pick of #1240 on release-1.6.
#1240: Temporarily fix CI
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```
=> Automated cherry pick of #1240: Temporarily fix CI

charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/clusterrole-snapshotter.yaml, deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
- Bug fix: #1249
- Also addresses: #1243 #1159
- Bumped up `csi-snapshotter` to `v6.0.1` which fixes "Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)" when attempting to create a snapshot, as support for `v1beta1` has been removed.
- Added `patch` to verbs list in `charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml` and `deploy/kubernetes/base/clusterrole-snapshotter.yaml`.
csi-snapshotter `v6.0.1` has not been published to public ECR: …
=> Fix unable to create CSI snapshot-EBS csi driver

charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
bump up the following sidecars:
external-attacher v3.1.0 -> v3.4.0
external-resizer v1.1.0 -> v1.4.0
external-provisioner v2.2.2 -> v3.1.0
node-driver-registrar v2.3.0 -> v2.5.1
livenessprobe v2.4.0 -> v2.5.0
re-generate kustomize profile
Unit test and functionality test
=> Bump up sidecar versions

hack/e2e/README.md
I use git  to basically vendor or copy/paste hack/e2e for reuse in efs/fsx repos. When adding ebs remote to efs/fsx, use `--no-tags`, otherwise `git fetch` also fetches tags that might conflict, e.g. it fetches 1.6.0 which points to some EBS commit when I want 1.6.0 to point to an EFS commit when I am in the efs repo, obviously
=> Avoid git tag conflicts when vendoring hack/e2e in other repos (efs/fsx)

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
- Bump up the Helm chart to `v2.6.10` to include fix: #1198
=> Bump up Helm chart to v2.6.10

hack/e2e/eksctl.sh, hack/e2e/run.sh
- https://github.com/weaveworks/eksctl/pull/5287 included in the new release fixes eksctl utils write-config breaking CI.
- Remove sed workaround which temporarily fixed CI.
- Upgrade `eksctl` to v`0.101.0`
- CI
=> Upgrade eksctl to v0.101.0

charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml
If online resizing is supported this should
be set to false. Otherwise, the resizer
will watch pods and use a lot more memory.
This fixes: #1248
It set's the check to see if the volume is in use to false. This should only be turned on
when the volume supports live resizing. I believe EBS volumes support resizing when in use.
This setting is used in other csi implementations
=> Set handle-volume-inuse-error to false

charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml
This PR improves on an existing feature introduced in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/e4569c373c609115ce2cf756e4e1646095f7a979. With this change, a user can configure the EC2 endpoint using a config map. For example, to change the EC2 endpoint a user can apply the following:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: aws-meta
namespace: kube-system
data:
endpoint: "https://specific.aws.endpoint"
```
Tested locally with setting a custom endpoint and seeing cloud actions being sent to endpoint domain.
Please let me know if there is a different preferred method to set this endpoint as well as if you want me to document this approach anywhere.
=> Support optional ec2 endpoint configuration

charts/aws-ebs-csi-driver/templates/node.yaml
Fixes #1274.
The current implementation doesn't respect `.Values.node.kubeletPath` and doesn't work in case kubelet uses a non-default directory.
Related to https://github.com/k0sproject/k0s/issues/1842
Manual testing
=> Node driver registrar socket path fix

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
- Bump up Helm chart to v2.7.0
Helm chart  v2.7.0
* Support optional ec2 endpoint configuration.
* Fix node driver registrar socket path.
* Fix hardcoded kubelet path.
=> Bump up Helm chart to v2.7.0

Dockerfile, Makefile
- Most incoming CVEs are not related to the CSI driver binary, but the base AL2 image layer. By using a minimal base image (for linux builds) we can greatly reduce ebs-csi-driver container image attack surface area and size.
- Addresses: #272
- The CSI driver requires the following dependencies in the base image layer: 
```
util-linux
e2fsprogs
xfsprogs
mount
```
- The driver uses the following binaries:
```
blkid
blockdev
dumpe2fs
resize2fs
fsck
fsck.ext4
fsck.ext3
mkfs
mkfs.ext4
mkfs.ext3
mkfs.xfs
xfs_io
xfs_growfs
umount
mount
```
- Using docker entrypoint to test binaries in container image:
```
$ docker run --entrypoint blkid …
```
=> Use minimal base image for linux builds

pkg/driver/mount_linux.go, pkg/driver/node.go
Refactoring only.
There was some copy-pasted code from mount utils to get it early. It was needed to check if volume needs resizing.
The code is already released in kuberenes/mount-utils so the copy-pasted code should be removed.
This is what I did to verify the resize still works fine and did not break:
1) Prepare at least one snapshot of a claim (size 1G in the example)
```
$ oc get volumesnapshots
NAME                READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
claim-1-snapshot    true         claim-1                             1Gi           csi-aws-vsc …
```
=> Use k8s mount-utils for checking volume resize

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, deploy/kubernetes/secret.yaml, docs/install.md
Co-authored-by: t0rr3sp3dr0 <pedro.torres@incognia.com>
Closes #1286 and #1136
=> Fix version of K8s manifest images

deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
- Fixes #1304 
```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
error: accumulating resources: accumulation err='accumulating resources from 
'./ecr-public': '/tmp/kustomize-014789932/deploy/kubernetes/overlays/stable/ecr-public' must resolve to a file': 
couldn't make target for path '/tmp/kustomize-014789932/deploy/kubernetes/overlays/stable/ecr-public': json: unknown field "tagSuffix"
```
```
kubectl apply -k "github.com/torredil/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
serviceaccount/ebs-csi-controller-sa unchanged …
```
=> Fix image tags in ecr-public kustomization

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml, charts/aws-ebs-csi-driver/values.yaml
Adding envFrom property to container specs in the controller, node, and values templates. Sanitize comment related to EKS IRSA in the serviceaccount-csi-controller template.
envFrom provides a simple way to reference configMaps across multiple resources. Sanitizing the comment in the template removes sensitive AWS account information and also makes the value more generic. 
Deployed the AWS EBS CSI driver using Helm with these changes made to the templates and referencing a configMap with values for http/s_proxy and no_proxy, and successfully ran a test using the dynamic provisioning example.
=> add envFrom to container specs; sanitize comment with account info

CHANGELOG.md, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md, pkg/cloud/cloud.go, pkg/cloud/devicemanager/allocator.go, pkg/cloud/volume_limits.go, pkg/mounter/safe_mounter_windows.go
=> Post-release v1.10.0

Dockerfile, Makefile
**What is this PR about? / Why do we need it?** for networks where proxy.golang.org is blocked, go mod download fails.
**What testing is done?**  ~~testing now, now go mod download seems to be working but it is taking a while.~~
edit: it worked. took 15+ minutes but I assume it will be cached :pray: '
```
10 [builder 4/6] RUN go mod download
#10 DONE 1052.4s
```
=> Pass GOPROXY to image builder

Makefile, cloudbuild.yaml
- The `vendor` directory was removed in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1328 to address https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1326.  As a result of this change, we need to account for two scenarios:
1) For security, a user might want to prevent outgoing connections outside their internal network. Addressed in #1330.
2) If GOPROXY is undefined or set to "direct", then `go get` will use a direct connection to the VCS (e.g github.com). This is causing our build to [timeout](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1554118382679232512), since `go mod download` takes nearly 30 minutes to complete. Addressed …
=> Set `GOPROXY` in `cloudbuild.yaml`

examples/kubernetes/static-provisioning/README.md, examples/kubernetes/static-provisioning/manifests/claim.yaml
- Fix **static volume provisioning** example
- Set `volumeNmae` explicitly to avoid falling back to dynamic provisioning.
- Ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume
- Tested by deploying to an EKS cluster
=> Fix static provisioning example

.github/workflows/helm-chart-release.yaml
"Bug fix"
The helm release action gets run every time the `charts/` directory is modified. However, if the helm version hasn't been bumped (either by accident or because the new changes intentionally shouldn't be released) then the commit has a sad red X when merged into master:
This PR fixes that by only running the helm release action when `Chart.yaml` is modified (which very likely is a version bump).
Manually tested on test branch of forked repo
=> Only run helm action when Chart.yaml modified

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/ec2_interface.go, pkg/cloud/metadata.go, pkg/cloud/metadata_ec2.go, pkg/cloud/metadata_k8s.go, pkg/cloud/metadata_test.go, pkg/cloud/mock_ec2.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/node.go, pkg/driver/node_linux.go, pkg/driver/node_linux_test.go, pkg/driver/node_test.go, pkg/util/util.go, tests/integration/setup_test.go
=> Enable EBS CSI driver for snow device

Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/base/poddisruptionbudget-controller.yaml, deploy/kubernetes/base/serviceaccount-csi-controller.yaml
New feature
Fixes #1332
Fixes #1101
Implements `securityContext` for the node pod and all containers (including sidecar containers). Also switches to a more secure `securityContext` default of running as a non-root user and with a read-only root filesystem.
Currently, the node pod must run as a root user because `/var/lib/kubelet/plugins/ebs.csi.aws.com/` and `/var/lib/kubelet/plugins_registry/` are kubelet-managed and usually only writable by root (additionally, the node driver needs `privileged` for the bidirectional mount anyways, so root would not give extra security to that container anyways).
Also makes some minor improvements to `make generate-kustomize` so it doesn't generate useless diffs …
=> Improve securityContext implementation

.github/workflows/publish-ecr.yaml, Makefile
- Added workflow to automate publishing container images to staging / public ECR. Workflow is split into two separate jobs to enable a manual approval step / verify the release before pushing to public ECR.
- `create-manifest: all-image-registry` allows for parallelization with ``make -j `nproc` all-push`` to improve build times.
- Changes `GOPROXY` default value to `https://proxy.golang.org`.
closes #1317 
closes #1315
=> Automate publishing to ECR

.github/workflows/publish-ecr.yaml
- Bug fix
- The version flag, i.e `docker run $image --version` outputs the wrong driver version. Since we are no longer doing a pre-release commit to update the version in the [Makefile](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/6760e34480fa74894149d52c15cf21924bacf442/Makefile#L15), the `VERSION` env variable needs to be set and correctly passed into [LDFLAGS](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/6760e34480fa74894149d52c15cf21924bacf442/Makefile#L21) to fix the `--version` flag.
=> Set VERSION env variable in publish-ecr workflow

deploy/kubernetes/base/node.yaml
Fixes #1347, will need a cherry pick to `release-1.11` as well. I will open the cherry pick PR after this is merged.
Blocks 1.11.1 post-release PR.
=> Apply fix from helm chart to kustomize manifests

deploy/kubernetes/base/node.yaml
Cherry pick of #1348 on release-1.11.
#1348: Apply fix from helm chart to kustomize manifests
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```
=> Automated cherry pick of #1348: Apply fix from helm chart to kustomize manifests

.github/workflows/publish-ecr.yaml, .github/workflows/release.yaml, Dockerfile, Makefile
- `VERSION` is being [set](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/runs/7883559757?check_suite_focus=true#step:7:4)  but not correctly passed into [LDFLAGS](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/runs/7883559757?check_suite_focus=true#step:8:228) because it must be passed explicitly as a build-arg.
- Set release draft to true.
- Test run on forked repo: https://github.com/torredil/aws-ebs-csi-driver/runs/7886619522?check_suite_focus=true#step:8:234
=> Explicitly pass VERSION as a build-arg

Makefile, hack/verify-kustomize
New "feature"
Adds verification to CI that kustomize templates were regenerated when the helm chart is changed. Prevents mistakes that cause issues such as #1347.
Manually tested. CI will fail until #1348 is merged because it is designed to test for the problem that PR fixes (and thus, fails against current master).
=> Add kustomize verification for CI

CONTRIBUTING.md, Makefile, cloudbuild.yaml
Go settings are managed by `go env`. This is the way.
Also, simplify the build instructions. `GO111MODULE` does not need to
be set in the build environment.
Signed-off-by: Wayne Mesard <wsm@amazon.com>
=> Builds should not set/get GOPROXY in the environment

pkg/cloud/volume_limits.go, pkg/driver/node_test.go
Signed-off-by: Wayne Mesard <wsm@amazon.com>
Bug
An earlier version of the [Available instance types list](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances) was unclear on whether `c6i.metal` and `g5g.metal`. They are. And the docs now say so unambiguously. This PR updates the code to match the doc (and reality).
`make && make test`
=> c6i.metal and g5g.metal are nitro instances

pkg/driver/controller.go
Adds clearer warning message so customers with cases such as #1357 understand they should manually supply the region.
N/A
=> Add warning message when region is unavailable on the controller

cmd/main.go, cmd/options.go, go.mod, go.sum, pkg/cloud/cloud.go, pkg/cloud/devicemanager/manager.go, pkg/cloud/handlers.go, pkg/cloud/metadata.go, pkg/cloud/metadata_ec2.go, pkg/driver/controller.go, pkg/driver/driver.go, pkg/driver/identity.go, pkg/driver/internal/inflight.go, pkg/driver/node.go, pkg/driver/node_linux.go, pkg/driver/node_windows.go, pkg/driver/validation.go, pkg/resizefs/resizefs_windows.go
- Bug fix.
- closes #1369 
```
//current logging with --v=5
kubectl logs ebs-csi-node-5dfp2 -n kube-system -c ebs-plugin
I0901 00:11:25.194251       1 driver.go:73] Driver: ebs.csi.aws.com Version: v1.11.2
I0901 00:11:25.194302       1 node.go:96] [Debug] Retrieving node info from metadata service
I0901 00:11:25.194307       1 node.go:98] regionFromSession Node service
I0901 00:11:25.194319       1 metadata.go:85] retrieving instance data from ec2 metadata
W0901 00:11:28.364912       1 metadata.go:88] ec2 metadata is not available
I0901 00:11:28.364931       1 metadata.go:96] retrieving instance data from kubernetes api
I0901 00:11:28.369502       1 metadata.go:101] …
```
=> Update module k8s.io/klog to v2

examples/kubernetes/static-provisioning/README.md, examples/kubernetes/static-provisioning/manifests/pv.yaml
This is a very minor update to address a documentation issue that was raised as part of issue #1365 
Setting spec.csi.fsType is required when defining the PV if the end user plans on using spec.securityContext.fsGroup in their deployment to set correct permissions on their EBS volume mount.
=> Updating static example to include setting fsType

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
Adding support to the helm chart for granular tuning of the leader election flags that the `csi-provisioner` and `csi-attacher` use.
Issue lodged: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1368
The flags exist for tuning the behaviour of lease lock logic in the csi-provisioner and csi-attacher code. We have been observing lease issues due to a control plane issue that our manged provider is investigating. Therefore we want to tune these flags but need support for them in the helm chart.
This PR aims to implement this so that anyone using this chart can tune the flags when needed.
I've tested the chart logic with our local deployment:
// Default only …
=> Add support for tuning leader election to the helm chart for  csi-provisioner and csi-attacher

docs/parameters.md, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, tests/e2e/driver/ebs_csi_driver.go
- Support IOPS parameter for IO1/IO2 volumes.
- Support IOPSPerGB for GP3 volumes.
- Address #1364.
- `make test`
- CI
```
StorageClass
---------------------------
apiVersion: storage.k8s.io/v1
metadata:
name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
csi.storage.k8s.io/fstype: ext4
IOPS: "100"
type: io2
---------------------------
**Old behavior**
$ kubectl describe pvc
Warning  ProvisioningFailed    2s (x3 over 5s)  ebs.csi.aws.com_ebs-csi-controller-756d5594dd-vgzsj_728a3701-f044-4021-bfaf-316189032728  failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = Could not create volume …
```
=> Support IOPS parameter for IO1/IO2 volumes

pkg/driver/controller.go, pkg/driver/controller_test.go
Adds support for adding tags to snapshots based on the parameters from `VolumeSnapshotClass`es, similar to support for tags for volumes in `StorageClass`es.
Fixes #1261
Added test case for VSC-based tags
=> Add tags to snapshot based on VolumeSnapshotClass

go.mod, go.sum
- Upgrade `github.com/prometheus/client_golang v1.11.0` -> `v1.11.1` to address CVE-2022-21698.
- Upgrade `golang.org/x/net v0.0.0-20220225172249-27dd8689420f` -> `v0.0.0-20220906165146-f3363e06e74c` to address CVE-2022-27664.
=> Address CVEs

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/csidriver.yaml, charts/aws-ebs-csi-driver/values.yaml
=> Update release notes; Implement useOldCSIDriver parameter

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
- adding new feature
- Make the chart able to accept custom initContainers for the controller
see: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1378
Manually tested by helm template: 
`helm template .` with `initContainers: []`
```
kind: Deployment
apiVersion: apps/v1
...
containers:
- name: ebs-plugin
image: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.11.2
imagePullPolicy: IfNotPresent
args:
- controller
- --endpoint=$(CSI_ENDPOINT)
- --logtostderr
- --v=2
...
```
`helm template .` with
```
- name: wait
image: busybox
command: [ 'sh', '-c', "sleep 20" ]
```
```
---
kind: Deployment
apiVersion: apps/v1
spec:
nodeSelector:
kubernetes.io/os: linux …
```
=> Add initContainer parameter to the controller's template

pkg/cloud/cloud.go
Currently, setting the _AWS_EC2_ENDPOINT_ environment variable overwrites the STS endpoint as well. This patch adds a custom resolver to only set a custom endpoint in EC2 service.
This should fix #1122.
Manual tested in a cluster with custom endpoints and STS.
=> Add resolver to handle custom endpoints

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/metrics.yaml, charts/aws-ebs-csi-driver/values.yaml, docs/metrics.md
- This PR adds a Helm chart configuration which facilitates scraping AWS metrics when `enableMetrics` is set to true and the Prometheus Operator is installed, by deploying:
1.  A [Service](https://kubernetes.io/docs/concepts/services-networking/service/) object that exposes the EBS CSI Driver's controller metric port through a `ClusterIP`. 
2. A [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#:~:text=Alertmanager-,ServiceMonitor,-See%20the%20Alerting) object which updates the Prometheus scrape configuration and allows scraping metrics from the endpoint defined. For more information, see the manifest `metrics.yaml`.
- `httpEndpoint` is deprecated.
**What …
=> Add enableMetrics configuration

charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml
Bug fix. Users can not override or remove the default toleration for taints in the current helm chart.
Moves the default toleration for `NoExecute` for 300s to the values.yaml, which is where default values should be defined. This allows users to provide their own complete set of tolerations which can override the default toleration.
Helm template verification.
=> helm: Move default toleration to values.yaml so it can be overriden

docs/parameters.md
Signed-off-by: Terry Howe <tlhowe@amazon.com>
This is a bug fix for the parameters documentation to add snow volume types. It was tested manually by looking at the changed file on the branch.
=> Add snow device types to parameters

docs/install.md
users were confused about the preq steps about checking feature gates.
these need for enabling these gates is largely outdated. it is also clearer to discribe the version directly. 
=> revise preqs for install docs

README.md
- Address https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1382
- Merge after releasing `v1.12.0`.
closes #1382
=> Add release and support policy to README.md

charts/aws-ebs-csi-driver/templates/metrics.yaml, charts/aws-ebs-csi-driver/values.yaml
- Allow modifying `labels` for the `ServiceMonitor` object. 
- Parameterize the hardcoded namespace in `metrics.yaml`.
- Address https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1380#discussion_r988904466
- closes  #1420
- Rendered Helm chart.
=> Add serviceMonitor.labels parameter

hack/prow.sh
Grabs the version information from the tag for GCR, as we no longer do a pre-release commit
Fixes #1423 
Manual build
=> Add version information from tag to GCR build

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml
Give more flexibility to the helm chart users for the csi-controller tolerations.
The default values remains unchanged and the default behavior is also unchanged.
However, one with different needs regarding those tolerations can modify them at will.
=> refactor: Move the default controller tolerations in the helm chart values

pkg/driver/constants.go
BUG
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/controller.go#L139 All the parameters transformed to lower key, thus they should be compared to strings in lower key
=> [BUG] pkg/driver/controller.go uses ToLower

cloudbuild.yaml
- The additional windows build `windows-ltsc2022` is causing our cloudbuild to timeout. This PR increases the amount of time that the build is allowed to run by 1800 seconds (30 minutes) to account for the additional image.
=> Increase cloudbuild timeout

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
Feature. 
Allows users who wish to integrate the controller with IRSA authentication manually (i.e not using the https://github.com/aws/amazon-eks-pod-identity-webhook) to configure the controller with the correct mounts for authentication. For example:
```
volumes:
- name: aws-token
projected:
sources:
- serviceAccountToken:
audience: "sts.amazonaws.com"
expirationSeconds: 86400
path: token
volumeMounts:
- mountPath: "/var/run/secrets/eks.amazonaws.com/serviceaccount/"
name: aws-token
```
Helm template verification.
=> helm: Expose volumes and volumeMounts for the ebs-csi-controller deployment

Makefile, go.mod, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/metadata_ec2.go, pkg/cloud/metadata_k8s.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/mount.go, pkg/driver/mount_linux.go, pkg/driver/mount_test.go, pkg/driver/node.go, pkg/driver/node_linux.go, pkg/driver/sanity_test.go, pkg/driver/validation.go, pkg/driver/validation_test.go, pkg/util/util.go, tests/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go, tests/e2e/testsuites/pre_provisioned_snapshot_volume_tester.go, tests/e2e/testsuites/testsuites.go, tests/integration/integration_test.go, tests/integration/setup_test.go
- Upgrade `golangci-lint`: `v1.21.0` ->  `v1.50.1`
- Fix linter errors.
- `make verify`
- `make test`
- `CI`
=> Upgrade golangci-lint; Fix linter errors

hack/prow.sh
Bug fix
Fixes GCR version
Manual/CI
=> Use PULL_BASE_REF for VERSION instead of GIT_TAG for GCR builds

hack/prow.sh
Bug fix
`PULL_BASE_REF` is unreliable, switching to grabbing the version directly from git via `git describe`
CI/Manual
=> Grab version via tag directly from git

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
=> Release v1.13.0

docs/example-iam-policy.json
-  Remove invalid policy conditions.
-  Introduce a new policy condition that allows for deleting volumes created by the in-tree storage plugin.
=> Update example policy

docs/install.md, docs/options.md
- Update `docs/install.md` - The policy was updated in #1450 which introduced a new condition for managing volumes created by the in-tree driver. The removed section is no longer relevant. See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1450#issuecomment-1349539639
- Update `docs/options.md` - Sneaking this change in here as well, the current description for the endpoint driver option is not accurate.
=> Update install.md & options.md docs

Makefile, charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml, charts/aws-ebs-csi-driver/values.yaml, hack/e2e/chart-testing.sh, hack/e2e/run.sh, tests/ct-config.yaml
- Add test-helm-chart target to Makefile to test Helm chart upgrades
- Prevent this class of issue: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1390
- Manual
- CI
1. Pull changes locally.
2. Run `CLUSTER_TYPE=kops KOPS_STATE_FILE="s3://devcluster-state-e2e" make test-helm-chart`
=> Add test-helm-chart target to Makefile to test Helm chart upgrades

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
Add some sensible defaults to the chart (that are already used in the EKS-managed version of the driver), and also add `image.containerRegistry` parameter to allow prefixing all repositories (we will set this to `public.ecr.aws` in the upcoming 1.15.0 driver release when we switch the default to the EKS-D sidecars).
=> Chart Cleanup

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
- Bug fix.
- Prevent deployment of testing resources during normal installation by adding `helm.sh/hook: test` annotation.
- closes #1476
- Manually validated that testing resources are not deployed.
=> Add `helm.sh/hook: test` annotation to chart testing resources

Makefile, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Fixes #1456 and also bumps the sidecar versions. New ECR (private) sidecars need promotion on AWS side (these will be the same images as the Public ECR deployment). All other deployment methods tested and working.
=> Change default sidecars to EKS-D

hack/e2e/run.sh
- When performing upgrade tests, `ct` needs to use the test driver image created by `ecr_build_and_push` to correctly test changes made to the Helm chart and container image in the same PR.
- CI
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1467
=> Use test driver image when testing upgrades with CT

README.md, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
`registry.k8s.io` is the new `k8s.gcr.io`. New versions of Kubernetes are being released _exclusively_ on `registry.k8s.io`, who knows how long the old DNS name `k8s.gcr.io` is going to stick around: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/
Our images will continue to be promoted to `k8s.gcr.io` as long as it continues to exist for users that need it, but we should stop advertising that DNS name and start advertising the new one.
This PR also drops extremely old and unsupported images from the README images list. Those images are still present on the associated `release-X.Y` branches if users should need them.
=> k8s.gcr.io -> registry.k8s.io

.github/workflows/helm-chart-release.yaml, .github/workflows/publish-ecr.yaml, .github/workflows/unit-tests.yaml, Makefile, hack/provenance
- Fixes #1489  by building with `--provenance=false`
- Bumps Github Actions versions to non-deprecated versions
=> Minor CI Fixes

go.mod
This is a bugfix intended to fix the following error:
```
$ go list -mod readonly -m all
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
```
This patch pins `k8s.io/dynamic-resource-allocation` to `v0.26.0`, like the other kube dependencies.
```$ go list -mod readonly -m all```
=> Pin k8s.io/dynamic-resource-allocation to v0.26.0

Makefile, pkg/cloud/cloud.go, tests/e2e/suite_test.go
- Fix CI, see: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1503#issuecomment-1422822965
- [endpoints.Ec2ServiceID](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/) is deprecated: Use client package's [EndpointsID](https://github.com/aws/aws-sdk-go/blob/1c759fb5b09ba21a4a82883f8a2a1a411c814ad4/service/ec2/service.go#L33) value instead of `ServiceIDs`.
- `rand.Seed` is deprecated; use `rand.New(NewSource(seed))`. Per https://go.dev/doc/go1.20, "_Programs that need a reproducible sequence of random numbers should prefer to allocate their own random source, using `rand.New(rand.NewSource(seed))`._ "
```
$ docker run -it --rm --entrypoint /bin/bash …
```
=> Fix CI; Upgrade golangci-lint

cmd/options.go, cmd/options_test.go
Fix version handling code to output version info, which was inadvertantly removed in ad25982
=> Fix --version output

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Release 1.16

README.md
sig-infra is now considering [drastic changes](https://kubernetes.slack.com/archives/CCK68P2Q2/p1677709804935919) such as deleting existing high-cost images on `k8s.gcr.io` (like ours). This PR adds a warning about the issue to the most visible place possible, the top of the README.
=> Add warning to README about k8s.gcr.io deprecation

deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Backport of #1488 to (currently) supported 1.15 branch
=> [BACKPORT] k8s.gcr.io -> registry.k8s.io

pkg/driver/node.go
XFS requires "size=" prepended to the size passsed to -b for mkfs.xfs
=> Add support for XFS custom block sizes

pkg/driver/driver.go
- This information helps with debugging. The current default is `--v=2` which unfortunately does not log this information.
```
$ kubectl describe pod ebs-csi-controller-5b7b77b787-d4ml5 -n kube-system
Name:                 ebs-csi-controller-5b7b77b787-d4ml5
Namespace:            kube-system
Containers:
ebs-plugin:
...
Args:
controller
--endpoint=$(CSI_ENDPOINT)
--logging-format=text
--v=0
$ kubectl logs ebs-csi-controller-5b7b77b787-d4ml5 -n kube-system -c ebs-plugin
I0309 16:01:08.462742       1 driver.go:73] "Driver Information" Driver="ebs.csi.aws.com" Version="v1.16.0"
```
=> Always log driver information

Makefile, pkg/cloud/cloud_test.go, pkg/cloud/devicemanager/allocator.go, pkg/cloud/devicemanager/allocator_test.go, pkg/cloud/devicemanager/manager.go, pkg/cloud/devicemanager/manager_test.go
DM treats the prefixes "/dev/xvd" and "/dev/sd" as magic. This leads to a bug where volumes with a prefix starting with "/dev/sd" (for example, "/dev/sdf") will get incorrectly mangled into a "/dev/xvd" form (i.e. converting "/dev/sdf" to "/dev/xvdf"). This will cause a volume that is already mounted and prefixed with "/dev/sd" (for example, a volume manually mounted via the AWS console) to get stuck in an infinite loop as the node will believe it is mounted at the wrong path.
With this change, instead of storing only the end of the path in the inflight and existing volumes map, we instead store the entire device path. The previously leaky abstraction from the allocator to store only the end of the path is contained to the allocator, which has a new parameter for the desired prefix.
This …
=> Stop treating prefixes as magic in DeviceManager

deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
- `bases` has been deprecated and replaced by `resources`: https://github.com/kubernetes-sigs/kustomize/blob/2a8a17e3af263c8cd61452bd2fc5e2e7d7bc5330/api/types/kustomization.go#L85-L88.
- We use `resources` for some Kustomization objects and `bases` for others. This PR replaces all instances of `bases` with `resources`.
=> Kustomize: use 'resources' instead of deprecated 'bases'

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
- Currently, we run the entire External.Storage e2e suite when testing Helm chart changes / upgrades -- overkill. This PR significantly reduces the number of tests we run to a select few that still cover all the functionality:
- `Kubernetes e2e suite: [It] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (default fs)] volumes should store data`
- `Kubernetes e2e suite: [It] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (delayed binding)] topology should provision a volume and schedule a pod with AllowedTopologies`
- `Kubernetes e2e suite: [It] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand Verify if offline PVC expansion works`
- …
=> Reduce scope of testing for test-helm-chart

charts/aws-ebs-csi-driver/templates/volumesnapshotclass.yaml, charts/aws-ebs-csi-driver/values.yaml
**Is this a bug fix or adding new feature?**  
New feature.
Allow defining VolumeSnapshotClass in Helm Chart. #1459 
1. Modified ``values.yaml`` to declare VolumeSnapshotClass like this 
```
volumeSnapshotClasses:
- name: ebs-vsc
annotations:
snapshot.storage.kubernetes.io/is-default-class: "true"
deletionPolicy: Delete
parameters:
testKey: testValue
```
2.  Installed the helm chart. 
``helm upgrade --install aws-ebs-csi-driver --namespace kube-system ./charts/aws-ebs-csi-driver --values ./charts/aws-ebs-csi-driver/values.yaml``
3. Ran ``kubectl get volumesnapshotclass -n kube-system`` and verified VolumeSnapshotClass is installed as expected:
```
NAME      DRIVER            DELETIONPOLICY   AGE
ebs-vsc …
```
=> Support VolumeSnapshotClass in Helm Chart

README.md
""Bug fix""
Updates the README to clarify volume resizing can be done both offline and online. Also replaces Chromium-specific links with standard links.
N/A
=> Clarify volume resizing in README; Remove Chrome(ium)-specific links

pkg/driver/controller.go, pkg/driver/controller_test.go
Bug fix for #1545 
When users set "Name" tag for a snapshot via `VolumeSnapshotClass.parameters`, the value of the Name tag is overwritten by [the value automatically populated by the Driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/5d75bf4be309d3b554d3959a79cc8f05ed65d4d2/pkg/driver/controller.go#L632), which is unexpected behavior.
This PR fixes the bug by setting the tags from VolumeSnapshotClass.parameters _after_ the Driver automatically populates the Name tag.
Added unit test & 
1. Built and installed the driver that has the changes. 
2. Followed the repro steps in #1545 to create a snapshot with "Name" tag in ``VolumeSnapshotClass.parameters``. …
=> Fix VolumeSnapshotClass tagging

pkg/driver/mount_windows.go, pkg/driver/node.go, pkg/mounter/safe_mounter_windows.go
- Bug fix.
**What is this PR about?**
This PR fixes several bugs uncovered by running the external e2e tests on Windows. It will allow us to run the tests in parallel and should land before https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1521.
- `GetDeviceNameFromMount` now returns the disk number for a mount path on Windows.
- Cleanup the stage path via `Rmdir` in `proxyMounter.Unmount()` before offlining the disk.
- Remove unnecessary call to `proxyMounter.WriteVolumeCache()` when unpublishing a volume from the node.
- Return a nil error in `GetDeviceNameFromMount` if the target path does not exist, per the CSI spec: _If the volume corresponding to the volume_id is not staged to the staging_target_path, the Plugin MUST reply 0 OK._ …
=> Fix staging / unmounting volume operations on Windows

hack/e2e/run.sh
If changes are made to the driver / chart simultaneously, testing should be performed against the newly built test image. This PR ensures this desired behavior via the [CT parameter](https://github.com/helm/chart-testing/blob/70acba19d18a72d456aab1b8739e8c6998225566/doc/ct_install.md?plain=1#L54) `--helm-extra-set-args`.
Currently, in the CT job we set the image repository / tag using yq. CT uses `--reuse-values` when performing helm upgrades, this parameter causes Helm to use the values in a previous release as the base, disregarding any changes that may have happened in the new chart version.
From the [Helm documentation](https://helm.sh/docs/helm/helm_upgrade/):
```
--reuse-values  when upgrading, reuse the last release's values and merge …
```
=> Set image repository/tag via `--helm-extra-set-args` param in CT

charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml, docs/tagging.md, pkg/driver/constants.go, pkg/driver/controller.go, pkg/util/template/template.go, pkg/util/template/template_test.go
New feature. 
For more details, see issue #1553 
1. Added support for interpolated snapshot tags that are dynamically computed at runtime using ``VolumeSnapshot`` name, namespace and ``VolumeSnapshotContent`` name.
2. Modified the helm chart template ``controller.yaml`` to allow setting ``--extra-create-metadata`` for ``csi-snapshotter`` sidecar. It enables ``external-snapshotter`` to pass the snapshot parameters to CSI Driver.
3. Added the documentation for Snapshot Tagging.
1. Added unit tests of string interpolation on the VolumeSnapshot template.
2. E2E tests. Deployed the Driver with the changes. Provisioned a snapshot using this VolumeSnapshotClass
```
apiVersion: …
```
=> Support interpolated snapshot tags

pkg/cloud/metadata_ec2.go, pkg/cloud/metadata_test.go, pkg/driver/node.go, pkg/driver/node_test.go
- Bug fix.
Currently, the `blockVolumes` count returned from the ec2 metadata service is incorrect. 
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/7db7d1a745abd1473eb86e63383c119209dcfc80/pkg/driver/node.go#L729
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/7db7d1a745abd1473eb86e63383c119209dcfc80/pkg/cloud/metadata_ec2.go#L71 
As an example, on Windows the virtual devices for [instance store](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) volumes are counted which results in -1 as the attachment limit when block devices are subtracted from the available limit:
```
$ kubectl logs ebs-csi-node-windows-gjllb -n kube-system -c ebs-plugin
I0404 …
```
=> Fix volume attachment limit calculation

docs/fast-snapshot-restores.md, pkg/cloud/cloud.go, pkg/cloud/cloud_interface.go, pkg/cloud/cloud_test.go, pkg/cloud/ec2_interface.go, pkg/cloud/mock_cloud.go, pkg/cloud/mock_ec2.go, pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/sanity_test.go
- New feature.
- This PR adds support for [Fast Snapshot Restores](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-fast-snapshot-restore.html) via the `fastSnapshotRestoreAvailabilityZones`  VolumeSnapshotClass parameter.  Availability zones are specified as a comma-separated list.
**Example**
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
name: csi-aws-vsc
driver: ebs.csi.aws.com
deletionPolicy: Delete
parameters:
fastSnapshotRestoreAvailabilityZones: "us-east-1a, us-east-1b"
```
- The driver must be given permission to access the [EnableFastSnapshotRestores EC2 API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EnableFastSnapshotRestores.html). …
=> Add support for Fast Snapshot Restores

Makefile, hack/e2e/ecr.sh, hack/e2e/eksctl.sh, hack/e2e/run.sh, hack/vpc-resource-controller-configmap.yaml, tests/e2e-kubernetes/manifests.yaml
- Add `test-e2e-external-eks-windows` target to run the External Storage tests on Windows nodes.
- Known issues: 
~1. `GINKGO_PARALLEL=1`. Running the tests in parallel will sometimes trigger a bug when mounting volumes:~
Fixed by https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1526.
~2. Skipped test `volumeLimits [It] should verify that all csinodes have volume limits` - Known bug; CSINode Allocatable property is not set on Windows nodes:~
Fixed by https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1561.
```
$ kubectl describe csinode                                             
Name:               ip-192-168-59-155.us-west-2.compute.internal
Labels:             <none>
Annotations: …
```
=> Add target to run External Storage tests on Windows nodes

charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, deploy/kubernetes/base/node.yaml
Feature
Adding configure map for liveness-probe check in node-driver-registrar
Block the CSI socket `/csi/csi.sock` access, after `csi-node` pod start up, `node-driver-registrar` reports log as following:
```
I0413 21:54:55.333415       1 main.go:167] Version: v2.7.0
I0413 21:54:55.333449       1 main.go:168] Running node-driver-registrar in mode=registration
I0413 21:54:55.333810       1 main.go:192] Attempting to open a gRPC connection with: "/csi/csi"
W0413 21:55:05.334651       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0413 21:55:15.334376       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0413 21:55:25.333936       1 …
```
=> configure lievness probe check for node-driver-registrar

hack/e2e/run.sh
- For `kubetest2`, the `--test-package-version` should be set to 1.27 for Windows as this version of K8s released the changes necessary to run the External Storage testing pods on a EKS Windows nodegroup: https://github.com/kubernetes/kubernetes/pull/115443
```
CLUSTER_TYPE=eksctl HELM_VALUES_FILE=./hack/values_eksctl.yaml make test-e2e-external-eks-windows
```
=> Use K8s `stable-1.27` for External Storage tests on Windows

pkg/cloud/volume_limits.go
bugfix
Updating the list of nonNitro instances to be in sync with the [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances). There were some types in the list that didn't belong (eg, c7g is a Nitro type), and a few types that needed to be added.
This makes the limit prediction logic a little bit more accurate and helpful for these instance types.
I ran unit tests --  but it doesn't seem as though I have permission to run any of the other tests. Happy to take suggestions, though.
=> update list of nitro instances

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Fixes #1583 and adds a test case for the scenario
=> Allow throughput with defaulted GP3 volume type

tests/e2e/dynamic_provisioning.go
- Bug fix.
- closes #1559 
```
$ ginkgo run --until-it-fails \
--focus='should create multiple PV objects, bind to PVCs and attach all to a single pod' \
--focus='should create a raw block volume and a filesystem volume on demand and bind to the same pod' \
tests/e2e
Will run 2 of 33 specs
SSSSSSSSSSSSSSS•SS•SSSSSSSSSSSSSS
Ran 2 of 33 Specs in 60.476 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 31 Skipped
PASS
All tests passed...
Will keep running them until they fail.
This was attempt #50
No, seriously... you can probably stop now.
```
=> Fix e2e test flakes due to volume node affinity conflict

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml, hack/e2e/run.sh
This PR replaces references of https://storage.googleapis.com/kubernetes-release with https://dl.k8s.io/
https://github.com/kubernetes/k8s.io/issues/2396
=> Use dl.k8s.io instead of kubernetes-release bucket

charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
- Bug fix.
- This PR removes CPU limits to prevent unnecessary throttling and decreases the livenessprobe frequency for the node-driver-registrar sidecar container in the node pod.
- closes #1591
=> Remove CPU limits; Decrease node pod CPU usage

Dockerfile, Makefile
As mentioned in the [release notes](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md), v1.18.0 is the last minor release of the AWS EBS CSI Driver to support Windows 20H2.
=> Drop support for Windows 20H2

README.md, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml, docs/modify-volume.md, go.mod, go.sum, pkg/cloud/cloud.go, pkg/cloud/cloud_interface.go, pkg/cloud/mock_cloud.go, pkg/driver/controller.go, pkg/driver/controller_modify_volume.go, pkg/driver/driver.go, pkg/driver/sanity_test.go
The commit allows users to modify volume properties through PVC annotations. For more details, refer to the modify-volume doc.
=> Enable volume modification through annotations

Dockerfile, charts/aws-ebs-csi-driver/templates/node-windows.yaml
"Feature"
* Migrates Windows containers to EKS-D base images
* Add explicit runAsUserName to Windows manifests (required because the EKS-D images run as a non-privileged user by default, and we need to be privileged to do our job)
Manual/CI
=> Migrate to EKS-D Windows base images

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml
This commit enables leader election in the csi-resizer sidecar. Without it, a resize request is routed to all instances of the sidecar, which would cause all but one of them to fail.
Feature
Without leader election:
```
$ k describe pvc ebs-claim                                    
Name:          ebs-claim
Namespace:     default
StorageClass:  resize-sc
Status:        Bound
Volume:        pvc-7c054c55-c253-449c-97f2-09fdf6edcf75
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
pv.kubernetes.io/bound-by-controller: yes
volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com …
```
=> Enable leader election in csi-resizer sidecar

pkg/driver/mount_linux.go
bug fix
We observed an issue where a workload mounting multiple EBS volumes gets stuck Terminating because unmount is failing on the node. It's racy and difficult to reproduce, but from the kubelet logs, the unmount succeeded once and about 0.1s later Unmounter.TearDownAt starts failing with `exit status 32`. Then the pod is left in the Terminating state until kubelet is restarted.
There was some work to make mounts idempotent in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1019 but it did not address the unmount path. Other CSI drivers use `mountutils.CleanupMountPoint` which checks if the path exists, if the mount is corrupted, and if the mount exists before attempting to call …
=> idempotent unmount from NodeUnstageVolume / NodeUnpublishVolume

pkg/driver/controller.go, pkg/driver/controller_test.go
Condition on iopsPerGB key being mandatory for io1 volumes introduced by https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/767 is irrelevant and should be removed as it's possible to create a io1 volume by specifying the desired number of iops.
```
$ aws ec2 create-volume --availability-zone eu-west-3a --iops 1337 --size 100 --volume-type io1
{
"AvailabilityZone": "eu-west-3a",
"CreateTime": "2023-05-04T12:30:04+00:00",
"Encrypted": false,
"Size": 100,
"SnapshotId": "",
"State": "creating",
"VolumeId": "vol-0cba6d099003264f2",
"Iops": 1337,
"Tags": [],
"VolumeType": "io1",
"MultiAttachEnabled": false
}
```
The documentation updated by https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1409 is also already mentioning that iopPerGB **or** iops can be used for io1 volumes …
=> remove condition on iopspergb key being mandatory for io1 volumes

pkg/driver/node.go
Just updating a logline.
This code path is always hit when mounting, even when the filesystem was already present, and we just mount it.
Reading these log lines for existing PVCs makes my heart miss a beat, when I realize that the volume was indeed not formatted before mounting. If its being formatted, its already present in logs above when on v=4.
n/a
=> Update logline to remove "formatted"

README.md
Remove the coverage banner from the README. The banner points to this link: https://coveralls.io/github/kubernetes-sigs/aws-ebs-csi-driver?branch=master, which is of 2 year old testing that doesn't seem to be supported anymore. It's been removed from the FSx Lustre CSI Driver
=> Remove old coverage banner from README

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml
New feature (for helm chart)
Adds an `additionalArgs` parameter to sidecars, for parameters such as `--retry-interval-max` or `--kube-api-qps`.
Supersedes #1585
Fixes #1579 
Manually rendered, CI
=> Add additionalArgs parameter for sidecars

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go
----
**`cloud.go`** changes:
This PR addresses incorrect handling of the Context in `WaitForAttachmentState` which implements a retry mechanism using exponential backoff to wait for an attachment to reach the expected state via the `DescribeVolumesWithContext` API.
The context is used to carry deadlines and cancellation signals across API boundaries. When polling for volume state, its possible for the context to be cancelled due to timeout etc. If this happens while we're waiting for the volume to reach the expected state, it is desirable to stop waiting and immediately return an error to the caller. This change allows us to better handle cases where the context is cancelled or reaches its deadline by stopping execution when no longer …
=> Fix context handling in WaitForVolumeAttachment & add in-flight checks to attachment/detachment operations

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Avoid generating manifests with empty envFrom fields

charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/serviceaccount-csi-controller.yaml, deploy/kubernetes/base/serviceaccount-csi-node.yaml, docs/install.md
new feature
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes
> The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#se …
=> chore: Allow to set automountServiceAccountToken in ServiceAccount

deploy/kubernetes/base/kustomization.yaml
This PR expands the resource list in our Kustomization file. It adds the role and rolebinding resource for leases and ensures they're created in the correct namespace, `kube-system`.
Without this patch:
```
kubectl get roles --all-namespaces                                                                                                                                                                       
NAMESPACE     NAME                                             CREATED AT
kube-public   system:controller:bootstrap-signer               2023-06-16T14:15:38Z
kube-system   extension-apiserver-authentication-reader        2023-06-16T14:15:37Z
kube-system   kops-controller …
```
=> Extend resource list in Kustomization file

.github/workflows/unit-tests.yaml, .github/workflows/verify.yaml
Resolve  #1635 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: |
echo "::set-output name=go-build::$(go env GOCACHE)"
echo "::set-output name=go-mod::$(go env GOMODCACHE)"
```
**TO-BE**
```yml
run: |
echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
shell: bash
```
=> Replace deprecated command with environment file

hack/e2e/kops.sh, hack/e2e/run.sh
Use AWS SSM to get the latest AL2023 AMI ID.
- CI
=> Use SSM to get latest stable AMI for EC2 nodes

README.md, docs/install.md
Documentation
Add instructions for uninstalling the driver. Especially helpful to those who wish to migrate to the EKS-managed add-on. 
=> Add Uninstall Documentation to install.md

hack/e2e/metrics/metrics.sh
`error_handler` breaks CI - removing it until we can find a better solution
See, for example, the end of the logs for https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/1703/pull-aws-ebs-csi-driver-test-e2e-external-eks-windows/1686370764527243264
=> Remove error_handler breaking CI

charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml
policy/v1beta1 was removed almost a year ago in kubernetes 1.25. The default for the `PodDisruptionBudget` should be modernized to `policy/v1` and fallback to `v1beta1` if `policy/v1` is not supported in the cluster. The `.Capabilities` object does not validate cluster capabilities when generating templates so is an imperfect solution for ensuring we're using the right api version.
Signed-off-by: Noah Krause <krausenoah@gmail.com>
=> chore: default to policy/v1

docs/modify-volume.md, pkg/cloud/cloud.go, pkg/cloud/cloud_interface.go, pkg/cloud/cloud_test.go, pkg/cloud/mock_cloud.go, pkg/driver/controller.go, pkg/driver/controller_modify_volume.go, pkg/driver/controller_test.go, pkg/driver/request_coalescing_test.go, pkg/driver/sanity_test.go
New feature
One [restriction](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/modify-volume.md) of the volume modification support provided by EBS CSI Driver is that if a user updates both annotations and capacity of a PVC at the same time, it will result in 2 RPC calls from ``external-resizer`` and [``volume-modifier``](https://github.com/awslabs/volume-modifier-for-k8s) sidecars  to the CSI Driver, and only one of the them will succeed due to the 6-hour cool down period for EBS ModifyVolume.
This PR solves that problem by implementing the Request Coalescing feature in EBS CSI Driver that merges RPC requests from ``externa-resizer`` and ``volume-modifier`` sidecars.
**What …
=> Request coalescing for resizing and modifying volume

pkg/cloud/volume_limits.go
This PR adds a `i4i.large` to the volume limits configuration file. See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1699 for context.
https://aws.amazon.com/ec2/instance-types/i4i/
=> Add `i4i.large` to volume limits config

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, cmd/main.go, cmd/options/server_options.go, cmd/options_test.go, docs/options.md, go.mod, pkg/driver/driver.go, pkg/driver/driver_test.go, pkg/driver/trace.go
This PR adds support for opentelemetry tracing in the driver. The feature is opt-in behind a feature flag `--enable-otel-tracing`.
Adds basic tracing instrumentation focused around the gRPC calls by using an opentelemetry lib to intercept the calls automatically. However, some more in-depth instrumentation could be added at a later date.
The chart was also updated to allow users to use this new feature.
Closes #1691 
This change has been running in Datadog's AWS clusters for a month without any issue. Below is a screenshot of an example of a captured trace.
=> Add opentelemetry tracing of gRPC calls

charts/aws-ebs-csi-driver/values.yaml, docs/install.md
Add doc of `additionalArgs` and mention `--kube-api-burst` and `--kube-api-qps` that #1666 requested.
=> Add doc of chart value additionalArgs

hack/e2e/eksctl.sh
"Bug fix"
Windows e2e is broken since the June AMI, this temporarily works around that breakage so the Windows e2e tests will be a reliable signal again.
CI
=> Temporarily workaround Windows e2e failures with larger instance type and slimmer AMI

Makefile, hack/e2e/run.sh
New feature
This PR adds a new parameter to `hack/run/e2e.sh` called `$DEPLOY_METHOD`. This parameter supports `"helm"` (the default and existing method) and `"kustomize"` (newly added for this PR) to specify the method that the EBS CSI Driver is deployed for testing.
It uses this parameter to crate a new make target, `test-e2e-external-kustomize` - which runs the e2e tests with a Kustomize installation of the driver.
Manually tested locally, additionally will start as optional when flipped on in `test-infra`:
```
Ran 83 of 7486 Specs in 305.820 seconds
SUCCESS! -- 83 Passed | 0 Failed | 0 Pending | 7403 Skipped
...
###
#
```
Test locally via `make` (replace …
=> Add kustomize e2e test

charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, docs/additional-daemonsets.md
Bug
I've tested the Additional DaemonSets creation locally and noticed the missing `---`
=> Additional Node DaemonSets bug fixes

tests/ct-config.yaml
This PR enables verbose output in test-helm-chart CI job to help debug issues.
- CI
=> Display verbose output for test-helm-chart CI job

charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/values.yaml
This is a new feature needed to enable/disable the daemonset. Having different kubelet locations on clusters, there's the need to add daemonsets per each kubelet location.
=> Manage DaemonSets enablement

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Bug fix
Today, the EBS CSI Driver will call `ModifyVolume` in cases when the volume is already in the desired state (which will trigger a modification in EBS). This PR changes the behavior so that the driver instantly reports a success in the case that the volume already matches the desired state.
Added unit tests, Manual
=> Do not call ModifyVolume if the volume is already in the desired state

hack/e2e/metrics/metrics.sh, hack/e2e/run.sh
related to https://github.com/kubernetes/k8s.io/issues/5194
=> Switch to new s3 bucket in AWS community account

hack/e2e/eksctl.sh, hack/e2e/run.sh, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1741
=> Cherry pick of 0a1b70c792226d5ac31b33b6f21eee25a5bc24b1 to release-1.22

pkg/cloud/volume_limits.go
> **Is this a bug fix or adding new feature?**
Updating hardcoded values.
> **What is this PR about? / Why do we need it?**
This PR adds volume limits for `m7a`, `c7i`, `r7a`, `and r7iz` instance families. See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html#nitro-system-limits.
> **What testing is done?** 
`make test`
=> Add volume limits for m7a, c7i, r7a, r7iz instance families

charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml
bug fix
Close #1750 
Removes deprecated PodDisruptionBudget API version policy/v1beta1. 
Install default helm chart to test cluster, verifying the chart renders and uses policy/v1. 
```
❯ kubectl api-resources | grep -i "disruption"
poddisruptionbudgets              pdb          policy/v1                              true         PodDisruptionBudget
```
=> Update default API version for PodDisruptionBudget

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/volumesnapshotclass.yaml, charts/aws-ebs-csi-driver/values.yaml
Hello,
This PR is adding the option to set labels to the volume snapshot classes created by the Helm chart.
For now this is only possible on the storage classes.
Thanks,
Fred
=> feat(helm): add labels to volumesnapshotclass

.github/workflows/helm-chart-release.yaml
"Bug fix"
By default, the chart releaser messes up the latest release on GitHub by marking the release used for the Helm chart as latest. This disables that behavior.
See parameter list here: https://github.com/helm/chart-releaser-action/blob/main/action.yml
N/A
=> Change chart-releaser-action config to not set Helm Chart releases as default

charts/aws-ebs-csi-driver/templates/controller.yaml
**Is this a bug fix or adding new feature?** & **What is this PR about? / Why do we need it?**
This is a new feature. While using the `aws-ebs-csi-driver` as a dependency for another chart , I found it difficult to pass a global or a dynamic value for the clusterName related fields. This PR adds support for passing a template as value for `podAnnotations` and `k8sTagClusterId` fields.
I've tested it by passing both static value and dynamic ones as follow:
* for the current values (empty/unset) nothing has changed:
`values.yaml`
```
k8sTagClusterId:
podAnnotations: {}
```
` helm template --debug  .` output: no podAnnotations added and no argument
* for static values
`values.yaml`
```
k8sTagClusterId: "cluster"
podAnnotations:
test.annotation: test
```
` helm …
=> [ebs-csi-controller] Allow passing template value for clusterName

charts/aws-ebs-csi-driver/templates/clusterrole-attacher.yaml, charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml, charts/aws-ebs-csi-driver/templates/clusterrole-resizer.yaml, charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml, charts/aws-ebs-csi-driver/values.yaml
feature
Allows users to more easily pass in sidecar cluster role rules when installing driver via helm chart. Closes #1746 
helm install with an additional cluster role rule
=> feat(helm): add to additionalClusterRoleRules to sidecar chart templates

examples/kubernetes/static-provisioning/README.md
bug fix
Small documentation update for the static-provisioning example. Closes #1733.
N/A
=> Update static-provisioning example README.md

.github/workflows/generate-code-coverage.yaml, .github/workflows/output-code-coverage.yaml
"New feature" for CI
Adds a GitHub Actions CI job to diff code coverage and comment the difference on the PR.
Note: although the PR jobs will run on this PR, the comment job must be committed to `master` before it can run. See example runs below:
Example with decrease: https://github.com/ConnorJC3/aws-ebs-csi-driver/pull/2
Example with no change: https://github.com/ConnorJC3/aws-ebs-csi-driver/pull/3
Example with increase: https://github.com/ConnorJC3/aws-ebs-csi-driver/pull/5
Example with external contributor: https://github.com/ConnorJC3/aws-ebs-csi-driver/pull/6
=> Add Github actions code coverage CI job

docs/parameters.md
Documentation 
Adds topology documentation (along with minor cleanup to fit it in) to `parameters.md`
Fixes #1701 
N/A, docs change
=> Document topologies in parameters.md

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
=> [release-1.23] Bump volume-modidifer-for-k8s sidecar to 0.1.3

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
Releases v1.23.1
* Update changelog.md with content from stage 0 of runbook
* readme.md latest version and install table
* Makefile VERSION 
* install.md all occurences of old version
* charts/aws-ebs-csi-driver/Chart.yaml with new version & appVersion 
* charts/aws-ebs-csi-driver/CHANGELOG.md with Helm changelog from stage 0
* Update overlays by running make generate-kustomize
=> Release v1.23.1

pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/node.go, pkg/util/util.go, pkg/util/util_test.go
bug fix
Split off parts of #1706 that refactor the format option parameter validation and controller unit tests. 
make test
=> Refactor format option validation and tests

pkg/cloud/volume_limits.go
Add volume attachment limits for `c7a` instance family, see https://aws.amazon.com/about-aws/whats-new/2023/10/compute-optimized-amazon-ec2-c7a-instances/.
`make test`
=> Add volume attachment limits for c7a instance family

hack/e2e/chart-testing.sh
Bug fix
See [PEP 668 – Marking Python base environments as “externally managed”](https://peps.python.org/pep-0668/) and https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/1706/pull-aws-ebs-csi-driver-test-helm-chart/1711789551590051840/build-log.txt for context.
CI
=> CI: Fix 'error: externally-managed-environment'

pkg/cloud/cloud.go
Bug fix
go test -v ./pkg/cloud/...
=> Fix DeleteDisk error handling in volume creation failure

.github/workflows/dependency-review.yaml, .github/workflows/govulncheck.yaml, Dockerfile
This PR adds [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) and [dependency-review-action](https://github.com/actions/dependency-review-action) CI checks for pull request events.
CI
=> Add govulncheck and dependency-review to CI workflow

hack/e2e/run.sh
CI is failing due to the node pod on the control plane node being stuck in a `CrashLoopBackOff` state. This PR prevents the node pod from being scheduled on the control plane node. 
See logs:
```
#
I1020 18:45:18.555825       1 driver.go:77] "Driver Information" Driver="ebs.csi.aws.com" Version="v1.24.0"
I1020 18:45:18.555934       1 node.go:82] "[Debug] Retrieving node info from metadata service"
I1020 18:45:18.555942       1 node.go:84] "regionFromSession Node service" region=""
I1020 18:45:18.555953       1 metadata.go:85] "retrieving instance data from ec2 metadata"
I1020 18:45:21.697673       1 metadata.go:88] "ec2 metadata is not available"
I1020 18:45:21.697695       1 metadata.go:96] "retrieving instance data from kubernetes api"
I1020 18:45:21.698336       1 metadata.go:101] …
```
=> Disable `tolerateAllTaints` on kOps

Dockerfile, Makefile, charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/node.yaml, hack/e2e/ecr.sh
Bug fix
Adds compatibility for running on instances with the a1 instance family
```
$ helm install aws-ebs-csi-driver . --set a1CompatibilityDaemonSet=true --set image.repository=368597081700.dkr.ecr.us-west-2.amazonaws.com/aws-ebs-csi-driver --set image.tag=fdb98666fa056862748ca337049f907d7b080e25
NAME: aws-ebs-csi-driver
LAST DEPLOYED: Wed Oct 25 15:15:29 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
To verify that aws-ebs-csi-driver has started, run:
kubectl get pod -n default -l "app.kubernetes.io/name=aws-ebs-csi-driver,app.kubernetes.io/instance=aws-ebs-csi-driver"
NOTE: The [CSI Snapshotter](https://github.com/kubernetes-csi/external-snapshotter) …
```
=> Add compatibility workaround for A1 instance family

Dockerfile, Makefile, charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/node.yaml, hack/e2e/ecr.sh
=> [cherry-pick release-1.23] Add compatibility workaround for A1 instance family

charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/node.yaml
bug fix and new feature
- Fixes #1813
- `additionalArgs` was under env vars in helm template, moves to container args as intended
- Fixes #1814
- Allows overriding the default livenessProbe
`helm template . -f values.yaml`
- `additionalArgs` now properly renders when provided
- Default livenessProbe is unchanged
=> Chart: node-driver-registrar sidecar fixes

Makefile, hack/e2e/ecr.sh, hack/e2e/run.sh
New feature (for CI)
Adds `Makefile` target and associated changes to `hack/` to run e2e tests on ARM instances
Tested locally:
```
$ KOPS_STATE_FILE=s3://368597081700-kops-state make test-e2e-external-arm64
AWS_REGION=us-west-2 \
AWS_AVAILABILITY_ZONES=us-west-2a,us-west-2b,us-west-2c \
HELM_EXTRA_FLAGS='--set=controller.k8sTagClusterId=$CLUSTER_NAME' \
EBS_INSTALL_SNAPSHOT="true" \
TEST_PATH=./tests/e2e-kubernetes/... \
GINKGO_FOCUS="External.Storage" \
GINKGO_SKIP="\[Disruptive\]|\[Serial\]" \
INSTANCE_TYPE="m7g.medium" \
AMI_PARAMETER="/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64" \
IMAGE_ARCH="arm64" \
./hack/e2e/run.sh
...
Running Suite: …
```
=> Add arm64 e2e test

docs/multi-attach.md, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/internal/inflight.go, pkg/driver/internal/inflight_test.go, tests/e2e/driver/driver.go, tests/e2e/driver/ebs_csi_driver.go, tests/e2e/dynamic_provisioning.go, tests/e2e/pre_provsioning.go, tests/e2e/testsuites/dynamically_provisioned_multi_attach_tester.go, tests/e2e/testsuites/pre_provisioned_multi_attach_tester.go, tests/e2e/testsuites/specs.go, tests/e2e/testsuites/testsuites.go
- New feature
- Closes #449 
This PR implements the ability to enable [multi-attach](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html) for `io2` block devices by specifying the `ReadWriteMany` access mode in `PersistentVolumeClaim.spec.accessModes`. A few important points to note:
- EBS Multi-Attach does not support standard file systems. Standard file systems such as `xfs`, `ext3`, `ext4`, and `NTFS` aren't designed to be simultaneously accessed by multiple EC2 instances.
- Simultaneous access to a standard file system can result in data corruption or data loss.
- Multi-Attach is only enabled for io2 block devices. 
See the documentation: …
=> Feature: Multi-Attach for io2 block devices

pkg/cloud/volume_limits.go
This PR adds `r7i` to the `instanceFamilies` map that holds the list of EBS-only instance storage families ahead of the November release.
See https://aws.amazon.com/ec2/instance-types/r7i/ for more details.
- `make test`
=> Add volume limits for r7i

charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml
Mostly a bug fix
Now that #1819 is going to land, the default QPS values are way too low. Bump them up so the driver does not come by default in slow mode.
Includes a check to prevent setting these values if the user has already done so via `additionalArgs`.
CI, local rendering
Use `helm template . --set 'sidecars.provisioner.additionalArgs[0]=--kube-api-qps=999'` to confirm that the `additionalArgs` check is working
=> Increase default QPS and worker threads of sidecars

charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml
- This PR changes the default timeout value (15s) for the attacher sidecar, responsible for exercising `ControllerPublishVolume` / `ControllerUnpublishVolume`. The default value of 15s used today is not a sensible default, as a result the following error is observed frequently:
```
E1101 14:21:54.345145       1 driver.go:124] "GRPC error" err="rpc error: code = Internal desc = Could not detach volume \"vol-07ec886465a316b9b\" from node \"i-0e137107f5012fb1f\": context deadline exceeded"
```
In the vast majority of cases the volume is successfully detached just mere seconds after the attacher times out.
closes #1671
For context:
```
--timeout <duration>: Timeout of all calls to CSI driver. It should be set to value that accommodates majority …
```
=> Update sidecar timeout values

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
Prepares branch for release via the following steps:
* Update changelog.md 
* readme.md latest version and install table
* Makefile VERSION 
* install.md all occurences of old version
* charts/aws-ebs-csi-driver/Chart.yaml with new version & appVersion 
* charts/aws-ebs-csi-driver/CHANGELOG.md with Helm changelog
* Update overlays by running make generate-kustomize
`make verify`
=> Release aws-ebs-csi-driver v1.25.0

.github/workflows/helm-chart-release.yaml, .github/workflows/output-code-coverage.yaml
"Bug fix" for CI
- Fixes code coverage job by changing to tag `1_5` which actually works (tag `1_6`, which the current hash is for, is broken)
- Bumps chart-releaser-action to latest tagged version
N/A
=> Update GitHub actions versions

pkg/cloud/metadata.go, pkg/cloud/metadata_ec2.go, pkg/cloud/metadata_interface.go, pkg/cloud/metadata_k8s.go, pkg/cloud/metadata_test.go, pkg/cloud/mock_metadata.go, pkg/driver/node.go, pkg/driver/node_test.go
/kind bug
Fixes: #1808
`meta-data/block-device-mapping` reports devices that were attached to the VM at the time the VM was started. It does not reflect devices attached/detached later.
In addition, even when it showed the attachments accurately, the CSI driver uses this information only at the driver startup. At this time, there may be some CSI volumes attached from the previous node boot. Those volumes are then counted as permanently attached to the node, while Kubernetes may detach them later.
Therefore do not count block-device-mapping at all and always reserve just 1 attachment for the root disk. Assume all other attachments are CSI volumes, and let Kubernetes do the calculations of attached …
=> Remove block-device-mapping from attach limit

.gitignore, Makefile, hack/release-scripts/generate-sidecar-tags, hack/release-scripts/get-latest-sidecar-images
Release automation
This PR adds:
- `image-digests-template.yaml`: A helper file for collating images, tags, and manifest digests used in the rest of the repository. Scripts in `hack/release-scripts` will generate an `image-digests.yaml` file from this template and propagating those updates to the rest of the repository. 
- `get-latest-sidecar-images`: Generates a `image-digests.yaml` file with the latest tags and associated manifest digests for each sidecar image by using `crane`.
- `generate-sidecar-tags` in hack/release-scripts: Generates the sidecar image tags in `deploy/kubernetes/overlays/stable/gcr/kustomization.yaml` and `charts/aws-ebs-csi-driver/values.yaml` based off of the values in …
=> Add release scripts for upgrading sidecar dependencies and collating image digests

hack/release-scripts/generate-release-pr
Release automation
This PR adds:
- `generate-release-pr` in hack/release-scripts: This script prepares (most of) a post-release PR, including updates to: 
- `README.md`
- `docs/install.md`
- `Makefile`
- `charts/aws-ebs-csi-driver/Chart.yaml`
- Kustomize Overlays
Running `./generate-release-pr v1.23.1 v1.24.0` on the `release-1.23` branch will produce the following diff:
``` diff
diff --git a/Makefile b/Makefile
index 14381011..b32b030c 100644
--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,7 @@
-VERSION?=v1.23.1
+VERSION?=v1.24.0
PKG=github.com/kubernetes-sigs/aws-ebs-csi-driver
GIT_COMMIT?=$(shell git rev-parse HEAD)
diff --git a/README.md b/README.md
index …
```
=> Add generate-release-pr to /hack/release-scripts

Makefile, tests/e2e/modify_volume.go, tests/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go, tests/e2e/testsuites/e2e_utils.go, tests/e2e/testsuites/format_options_tester.go, tests/e2e/testsuites/modify_volume_tester.go
Test-coverage
Note: This PR has been rebased since merging #1845 
The purposes of each commit exclusive to this PR are:
- [Refactor E2E: Extract resize-related helper functions](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/74108d8198c5e448a299bd783ad00e513ac43dcc)
- We want to ensure that customers who both expand the size of a volume and modify a volume's performance parameters at the same time can do so (without waiting for the 6 hour modifyVolume EC2 API cooldown. This implicitly testing request coalescing). Therefore we should extract resize-related helper functions into the shared e2e-utils file (and hopefully someday a separate e2e-utils package). 
- [Add E2E tests for …
=> Add E2E tests for modifying volumes via annotations

hack/kops-patch.yaml, pkg/driver/controller.go, tests/e2e/driver/driver.go, tests/e2e/driver/ebs_csi_driver.go, tests/e2e/requires_aws_api.go, tests/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go, tests/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go, tests/e2e/testsuites/e2e_utils.go, tests/e2e/testsuites/pre_provisioned_snapshot_volume_tester.go, tests/e2e/testsuites/specs.go
New feature for e2e tests
This PR is split into 3 commits:
-  *Fix controller.CreateSnapshot to create new err variable instead of overwriting existing with nil*
Fixes a minor logging bug discovered during the e2e test development
- *Add e2e snapshot tests*  
Adds tests for creating a volume and snapshot with additional tags
- *Add e2e FSR tests*  
Adds tests for creating a snapshot with an FSR zone
This PR is adding new tests
=> Add volume/snapshot tagging and FSR e2e tests

pkg/cloud/volume_limits.go, pkg/driver/node.go, pkg/driver/node_test.go
Bugfix
closes #1688 
This PR addresses a bug in the driver where the calculation that subtracts ENIs and Instance store values is bypassed for certain instance types. More specifically, instance types included in `maxVolumeLimits`:  https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v1.21.0/pkg/cloud/volume_limits.go#L56-66. 
As an example, `d3.8xlarge` (nitro instance) reports a value of `3`: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/6f2db761cfa352e05483b7f360b4ed9053b382d6/pkg/cloud/volume_limits.go#L57C3-L57C13 even when several ENIs are attached.
Following the current logic, `availableAttachments` is equal to the default value of `nitroMaxAttachments=28`  when enis and …
=> Bugfix: Instances listed under `maxVolumeLimits` not taking into account ENIs/Instance storage

pkg/driver/node.go
Bug fix
Sometimes, the node taint removal can fail (for example, due to a temporary networking outage, or if another client tries to remove a taint at the same time as us and gets to the API server first). In that case we should retry the taint removal.
This PR does two things:
- Moves the taint removal to run in a goroutine in the background so it doesn't block node startup
- Adds retries with an exponential backoff to the taint removal
Manually tested on a local cluster (but please at least one reviewer double check my work), as well as CI
=> Add retry and background run to node taint removal

charts/aws-ebs-csi-driver/templates/NOTES.txt
=> Add warning about --reuse-values to NOTES.txt

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
Releases aws-ebs-csi-driver v1.26
* Updates changelog.md
* Updates readme.md latest version and install table
* Updates Makefile VERSION 
* Updates install.md all occurences of old version
* Updates charts/aws-ebs-csi-driver/Chart.yaml with new version & appVersion 
* Updates charts/aws-ebs-csi-driver/CHANGELOG.md with Helm changelog
* Updates overlays by running make generate-kustomize
=> Release aws-ebs-csi-driver v1.26.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release 
Merge release-1.26 branch into master
Confirmed that the images are available on ECR Public + GCR
```
❯ crane manifest registry.k8s.io/provider-aws/aws-ebs-csi-driver:v1.26.0
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1098,
"digest": "sha256:76aac89455f0683f7a4572cc1b66724fc4a88a7a34f7c539d8fcd4123a0752ff",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1098,
"digest": "sha256:63893ea328168f4b83049e98686f86df2cefb55e7051c1dd6914a6 …
```
=> Release aws-ebs-csi-driver v1.26.0 

go.mod, go.sum
What type of PR is this?
/kind bug
What this PR does / why we need it:
fix: [CVE-2023-48795](https://github.com/advisories/GHSA-45x7-px36-x8w8)
Release note:
```release-note
fix: CVE-2023-48795
```
=> CVE-2023-48795: bump golang.org/x/crypto to v0.17.0

go.mod, go.sum, pkg/cloud/cloud.go
bug fix
This regression first appears in v1.12.0 of the driver, and blocks workloads (pods, deployments, stateful-sets) that dynamically provision GP3 volumes but explicitly specify an IOPS below the GP3 minimum of 3000.
In other words, the workload produced from the following manifests will run when driver v1.8 is deployed, but NOT when v1.25 is deployed.
```
...
metadata:
name: ebs-sc
parameters:
type: gp3
iops: "1500"
---
...
kind: PersistentVolumeClaim
spec:
storageClassName: ebs-sc
resources:
requests:
storage: 8Gi
---
...
kind: Pod
spec:
containers:
...
volumes:
- name: persistent-storage
persistentVolumeClaim:
claimName: ebs-claim
```
If these K8s objects were created …
=> Remove regression for GP3 storage classes below 3000 IOPS

charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, go.mod, go.sum
Dependency upgrade
Upgrades dependencies ahead of patch release v1.26.1. 
Also upgrades to the latest CSI sidecar images which will fix the sidecar container restarts-- closes #1875 
`make test` & `make verify`
=> Update driver dependencies

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Bug fix
EBS CSI Driver will let [EC2 CreateVolume](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html) enforce minimum IOPS values instead of enforcing the [hardcoded minimum limits in cloud.go](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/0c459169dd183c1b1fb27443d562cc0f6579a62b/pkg/cloud/cloud.go#L65-L78) (Unless `allowAutoIOPSPerGBIncrease` is set).
Note: This is a volume-type agnostic version of PR #1879, as requested by EBS CSI Driver team. 
Pro: 
- EBS CSI Driver relies more on EC2 API as source of truth for input validation (This fixes the GP3 storage class regression mentioned in #1879, as well as prevents future de-sync between the EC2 and CSI …
=> Remove premature CreateVolume error if requested IOPS is below minimum

tests/e2e/format_options.go
Test coverage
Adds `ebscsidriver.FSTypeExt3` and `ebscsidriver.FSTypeXfs` as tested filesystems for our e2e format option tests. 
This is separate from turning on the `ext3` feature flag for upstream k8s storage conformance tests. See #1891 for that.
This is separate from the discussion of whether we are deprecating support for `ext2`
This would add the following tests:
```
[ebs-csi-e2e] [single-az] [format-options] Formatting a volume using an ext3 filesystem with a custom blocksize parameter successfully mounts and is resizable
[ebs-csi-e2e] [single-az] [format-options] Formatting a volume using an ext3 filesystem with a custom bytesperinode parameter successfully mounts and is resizable …
```
=> Add ext3 and xfs fsTypes to e2e format-option test coverage

tests/e2e-kubernetes/manifests.yaml
E2E Test coverage
Add ext3 FSType coverage to our runs of the [upstream k8s storage conformance suite](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external). 
This would add the following K8s storage conformance tests to our CI's Linux e2e-kubernetes jobs:
- [Dynamic PV (ext3)] volumes should allow exec of files on the volume
- [Dynamic PV (ext3)] volumes should store data
- [Inline-volume (ext3)] volumes should allow exec of files on the volume
- [Inline-volume (ext3)] volumes should store data
- [Pre-provisioned PV (ext3)] volumes should allow exec of files on the volume
- [Pre-provisioned PV (ext3)] volumes should store data
CI
=> Add ext3 test coverage to our e2e-kubernetes storage conformance tests

hack/e2e/run.sh, tests/ct-config.yaml
This PR:
- Enables kubetest2 container logs for `pull-aws-ebs-csi-driver-test-helm-chart`.
- Lowers `kubectl-timeout` from 30m -> 10m to reduce job time when the test hangs. For context, the tests complete within 3m ~99% of the time.
CI
=> Enable kubetest2 container logs for pull-aws-ebs-csi-driver-test-helm-chart

pkg/driver/node_linux.go, pkg/driver/node_linux_test.go
Bug fix
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1224
```text
I1221 18:37:12.769528       1 node_linux.go:140] "Comparing volume serial" expected="vol0b99a3d34724acd2b" actual="vol0b99a3d34724acd2b"
```
CI/Added new unit tests
=> Use lsblk to safeguard against outdated symlinks

hack/cluster-debugging-scripts/README.md, hack/cluster-debugging-scripts/device_slot_test.tmpl, hack/cluster-debugging-scripts/find-attachment-limit, hack/cluster-debugging-scripts/generate_example_manifest.go, hack/cluster-debugging-scripts/get-attachment-breakdown, hack/cluster-debugging-scripts/go.mod
Cluster debugging tool
NOTE: This PR is an expansion of #1852 
These scripts help answer the question: `How can I validate that the aws-ebs-csi-driver correctly makes use of all available attachment slots for instance type X?`
This question is important because the aws-ebs-csi-driver currently [hard-codes the attachment limit for each EC2 Instance family and type](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/b894ce5d19c696195609c8cd534aacc2ee9f2ade/pkg/cloud/volume_limits.go#L223) (Due to not having an EC2 API that outputs the attachment limit of a given instance type, and whether Non-EBS-volume-attachments count towards that limit). 
See README.md for overview of each script. At a …
=> Add attachment limit scripts to hack/cluster-debugging-scripts

.github/workflows/publish-ecr.yaml
CI
#1805 provided a workaround for the aws-ebs-csi-driver's minimal AL23 base image not working on `a1` instance family by building and maintaining `a1compat` images (that are based off of an AL2 minimal base image) for use on `a1` nodes. 
This PR automates the copying of this a1-compatible manifest to our [public ECR repository](https://gallery.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver).
Note: This step was placed before "Copy manifest list to ECR Public" so that the latest non-workaround manifest list shows up by default on our ECR repository.
=> Add a1compat image to publish-ecr github action

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/devicemanager/allocator.go, pkg/cloud/devicemanager/allocator_test.go, pkg/cloud/devicemanager/manager.go, pkg/cloud/devicemanager/manager_test.go
Bug fix
Despite our best efforts, it is difficult to conclusively determine a safe block device name to use, and sometimes we get it wrong.
After thorough testing with the AMI from #1674, it was discovered that AMIs can include block device mappings (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html#ami-block-device-mapping) that behave unintuitively: block device names used by AMIs do NOT appear in the block device mappings returned by `DescribeInstances`
This leaves us with two options:
1. *Call `DescribeImages` for every attachment operation to check for block device mappings on the AMI.*  
This was discarded because it requires spending a massive amount of …
=> Remember likely bad device names for an hour

pkg/driver/node.go, pkg/driver/node_test.go
Bug fix
https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#ExponentialBackoff
When the condition func returns an error, it isn't retried:
```
Stops and returns as soon as: 1. the condition check returns true or an error
```
This change configures the conditional func used by `removeTaintInBackground` to always swallow the error
Added basic unit test confirming the function retries
Manually tested, output from real world retry failures:
```
I0119 15:57:29.455540       1 metadata_ec2.go:25] "Retrieving EC2 instance identity metadata" regionFromSession=""
E0119 15:57:29.472054       1 node.go:861] "Unexpected failure when attempting to remove node taint(s)" err="nodes …
```
=> Fix taint removal retry for non-swallowed errors

charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
Helm chart feature.
This PR adds chart parameters to tune the `revisionHistoryLimit` on the Deployment & DaemonSet and also to tune the `emptyDir` volumes used for sockets and probes, (set `sizeLimit`, `medium`, etc.).
Default values match the implicit Kubernetes default (in the case of `revisionHistoryLimit`) or match the original hardcoded value.
Generated manifests only show the addition of the (now explicit) default `revisionHistoryLimit`, volumes remain unchanged.
=> fix: Add parameters for tuning revisionHistoryLimit and emptyDir volumes

hack/prow.sh
Bug fix
`prow.sh` doesn't bootstrap the builder, which causes a race condition when building images in parallel
Successful prow run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1749495304584957952
=> Bootstrap buildx builder in prow.sh

charts/aws-ebs-csi-driver/values.yaml
Dependencies
Bump vol-modifier-for-k8s to fix its otel-grpc [CVE-2023-47108](https://avd.aquasec.com/nvd/cve-2023-47108)
CI
=> Bump volume-modifier-for-k8s to v0.2.1

Makefile, hack/e2e/metrics/metrics.sh
Bug fix
Pins metrics server version as the new version from 3 hours ago broke CI and is blocking our release
Also fixes a minor makefile bug I discovered along the way (`make cluster/create` didn't correctly depend on the AWS cli)
Manual/CI
=> Pin metrics server version; Fix minor `make cluster/create` bug

hack/release-scripts/generate-release-pr
Bug Fix
#1856 updated the makefile target for generating kustomize overlays based off of the helm charts. 
Local testing:
```
❯ ./hack/release-scripts/generate-release-pr v1.27.0 v1.27.1
2024-01-24 15:24:18 [INFO] - Confirming v1.27.0 < v1.27.1
...
2024-01-24 15:24:19 [INFO] - Updating helm chart and generates kustomize
...
SUCCESS!
...
```
=> Update release-script to use new makefile target

README.md, docs/faq.md
Documentation
In [aws-ebs-csi-driver v1.25.0](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/3981294942b4aa3bdfac95a06d7ab57b43c8130d/CHANGELOG.md?plain=1#L26), we introduced several scalability related improvements to the driver. Some customers have asked for explanations of how this version improves driver scalability, as well as learning how to tune the sidecar parameters to their specific cluster setups.
N/A
=> Add scalability section to FAQ

.github/workflows/trivy-containers.yaml, .github/workflows/trivy.yaml
This PR addresses a recurring issue with the Trivy image scanner action:
```
2024-01-21T00:26:20.3634014Z 2024-01-21T00:26:20.362Z	[31mFATAL[0m	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
2024-01-21T00:26:20.3637568Z 	* unable to inspect the image (public.ecr.aws/ebs-csi-driver/volume-modifier-for-k8s:v0.1.3): Error response from daemon: No such image: public.ecr.aws/ebs-csi-driver/volume-modifier-for-k8s:v0.1.3
2024-01-21T00:26:20.3639509Z 	* containerd socket not found: /run/containerd/containerd.sock
2024-01-21T00:26:20.3640750Z 	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory …
```
=> Fix Trivy image scanner

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Bug fix
The [kubekins-e2e v1 image](https://github.com/kubernetes/test-infra/tree/master/images/kubekins-e2e) used in our [helm tester pod](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/33fffa3d094f4451cfd94226377b8b94706315a1/charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml#L188-L222) is not multi-arch. Therefore we should assure we schedule it only on Linux `amd64` nodes. 
Closes #1921 
CI
TODO Attempt to run test on `arm64` only cluster.
=> Enforce linux amd64 nodeAffinity for helm tester pod

charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
helm feature
Closes #1918
"Running static analysis tools like KubeLinter against the chart fails due to pods (specifically ebs-plugin node.containerSecurityContext) allowing a container to run in privilege mode.
These can be ignored via annotations to the resource (not the pod but the daemonset) but currently there are no means to provide them."
CI
Manually testing the following values file:
```
controller:
deploymentAnnotations:
test.deployment.annotation/foo: bar
some.deployment.annotation/foo2: bar2
node:
daemonSetAnnotations:
test.annotation/foo: bar
test.annotation.2/foo2: bar2
enableWindows: true
```
Result: 
```
❯ helm upgrade \
--install aws-ebs-csi-driver \ …
```
=> Allow driver node daemonSet annotations to be configurable

docs/faq.md
Documentation
This PR adds 6-minute delay information to the FAQ section
=> Add 6 minute attachment delay to FAQ

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml, charts/aws-ebs-csi-driver/values.yaml
Helm
Closes #1920 
Today, [helm-tester.yaml](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml) has an hardcoded image which is not modifiable by helm chart.
This PR exposes a value in our helm chart to change the registry or customize the image name/tag.
Note, the repetition of the current kubekins image across helm-tester.yaml and values.yaml will be corrected once we deprecate the use of `--reuse-values` when upgrading our helm chart. See #1864 
CI and manual:
```
❯ helm upgrade \
--install aws-ebs-csi-driver \
--namespace kube-system \
./charts/aws-ebs-csi-driver --dry-run --debug --set …
```
=> Supply custom image to ebs-csi-driver-test pod via Helm

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Complementary PR to #1923, see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1923#issuecomment-1930626252 for context.
```
$ kube-linter lint aws-ebs-csi-driver 
KubeLinter development
No lint errors found!
```
=> Incorporate KubeLinter recommended best practices for chart tester pod

Makefile, hack/e2e/kops/kops.sh, hack/prow-e2e.sh
Bug fix
---
Fixes three small papercuts (each in their own commit):
When the local kubeconfig represents a cluster that no longer exists, patching (and thus creating) a kops-based cluster will get stuck. This fixes that by explcitly setting the config for patch operations to `/dev/null`
`shfmt` was trying to modify scripts in the `venv` in `bin/`, sometimes causing `make verify/update` to fail locally.
We already delete clusters where the e2e tests fail (as of #1856), but leave behind clusters where creation failed.
---
Manual/CI
=> Fix Three Papercuts

pkg/driver/node.go, pkg/driver/node_test.go
Both?
See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/729#issuecomment-1942026577
- Manually tested locally by attaching volumes created by both this and a previous version of the driver, and ensuring they both attached
- e2e (see CI)
=> Report zone via well-known topology key in NodeGetInfo

.gitignore, Makefile, docs/makefile.md
This PR makes modifications to `make test` to generate a test coverage report that explicitly excludes all generated mock files, giving contributors and maintainers more insight into code coverage.
In place of using the `grep` tech to filter out mock files, I initially attempted to split out mocked code into its own separate package. However, I quickly discovered that this is not possible due to a circular dependencies issue. To prevent the import cycle we'd have to bring in the tests over to the mock package as well - this is undesirable as a) it would effectively break the code coverage measurement altogether and b) not a standard Go practice.
```
make test
```
=> Add code coverage report

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release 1.28.0

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/values.yaml
Release
* Add `reservedVolumeAttachments` that overrides heuristic-determined reserved attachments via  `--reserved-volume-attachments` CLI option from [PR #1919](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1919) through Helm ([#1939](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1939), [@AndrewSirenko](https://github.com/AndrewSirenko)) 
* Add `additionalArgs` parameter to node daemonSet ([#1939](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1939), [@AndrewSirenko](https://github.com/AndrewSirenko))
See #1939
=> Release Helm Chart v2.28.1

pkg/batcher/batcher_test.go, pkg/cloud/cloud_test.go
Testing
~65s speed up for running `make test` via the following slow unit tests: 
- batcher_test.go: From 15s to 0.250s 
- Lower timeouts still functionally test code
- Cloud TestCreateDisk: "fail: Volume is not ready to use, volume stuck in creating status and controller context deadline exceeded" subtest: From 60s to 5s 
- Simulate a controller context deadline in the test. 
- The whole of TestCreateDisk still needs some work such that unit tests don't sleep serially. Will work on this in a separate PR. 
Manual testing to make sure batcher and TestCreateDisk unit tests still fail when their implementations break.
`make test`, `make verify`
`go test -race -count=1000` …
=> Fix slow createDisk and batcher unit tests

Makefile, charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml, charts/aws-ebs-csi-driver/templates/clusterrole-resizer.yaml, deploy/kubernetes/base/clusterrole-provisioner.yaml, deploy/kubernetes/base/clusterrole-resizer.yaml, docs/modify-volume.md, examples/kubernetes/modify-volume/README.md, examples/kubernetes/modify-volume/manifests/pod-with-volume.yaml, examples/kubernetes/modify-volume/manifests/volumeattributesclass.yaml, hack/e2e/kops/patch-cluster.yaml, pkg/driver/controller.go, pkg/driver/controller_modify_volume.go, pkg/driver/controller_modify_volume_test.go, pkg/driver/controller_test.go, pkg/driver/request_coalescing_test.go, tests/e2e/modify_volume.go, tests/e2e/testsuites/e2e_utils.go, tests/e2e/testsuites/modify_volume_tester.go
/kind feature
Implements support for modifying volumes via KEP3751 (https://kep.k8s.io/3751) using the EBS CSI Driver.
Change is split into multiple small commits:
- Refactor modification primitives out of ModifyVolumeProperties to separate functions
- Implement ControllerModifyVolume and MutableParameters in CreateVolume
- Update unit tests for ControllerModifyVolume/MutableParameters
- Add VolumeAttributesClass RBAC permissions to external-resizier and external-provisioner
- Add ControllerModifyVolume e2e tests
Manually tested, unit tests and e2e tests added
=> Implement KEP3751 ("ControllerModifyVolume")

pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/driver.go, pkg/driver/node.go, pkg/driver/node_test.go, tests/e2e/driver/ebs_csi_driver.go
This PR introduces the addition of an (OS) topology key to the node segments map returned by `NodeGetInfo` within the node service.
The change enables scoping down a StorageClass using the `allowedTopologies` attribute to an OS type. It is backward compatible and should not impact existing deployments. Nodes will simply start reporting additional topology information post-update.
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1946
`make test` && manual testing && CI e2e
Example StorageClass:
```
apiVersion: storage.k8s.io/v1
metadata:
name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
- key: …
```
=> Add OS topology key to node segments map

README.md, cmd/options.go, cmd/options_test.go, hack/e2e/kops/kops.sh, hack/release-scripts/generate-release-pr
Largely bug fix
Fixes three small issues:
**[Add missing kubeconfig in kops.sh](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/2af98faaa1f5a168a43ca71632af1dc67fbd0b30)**
Adds a `--kubeconfig dev/null` missed in #1933
**[Cleanup README images and compatibility](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/f66e87d9dde2b65ba4104d3df9cda48606e0d0c4)**
Change README section to only supported images, update release PRs script to account for this change.
**[Refactor options.go so that flags are always loaded](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/c8128be91f70cfde09aecd077b77908dfbea822b)**
Fixes #1952 by refactoring the logic to greatly simplify the …
=> Fix Small Papercuts 2.0

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Feature
Coalesces EC2 DescribeInstances calls across ControllerPublishVolume/ControllerUnpublishVolume RPCs. 
This decreases the likelihood of being exceeding one's [Non-mutating API request token limit](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html#throttling-limits) (ie being throttled for making too many`Describe*` calls).
Manual testing on statefulset to check that DescribeInstances calls were batched across RPCs
CI
=> Batch EC2 DescribeInstances calls

pkg/cloud/cloud.go, pkg/cloud/cloud_interface.go, pkg/cloud/mock_cloud.go
Cleanup
`IsExistInstance` is not used anywhere in our repository. This was added in order in order to inject a fake cloud provider back in this commit: [Make sanity tests happy · kubernetes-sigs/aws-ebs-csi-driver@3527d7f](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/3527d7fa25cf33379249c613edcbe91e4036bc02#diff-d4a686c1cd62817e5e4a8c812266913ae1a6b61439c462f9d3f630c9be6e73e5). 
Because we no longer rely on this function, we should consider removing this dead code. 
A text search for `IsExistInstance` usages; CI
=> Remove unused 'IsExistInstance'

go.mod, go.sum
CVE fix
Unblock CI:
```
Vulnerability #1: GO-2024-2611
Infinite loop in JSON unmarshaling in google.golang.org/protobuf
More info: https://pkg.go.dev/vuln/GO-2024-2611
Module: google.golang.org/protobuf
Found in: google.golang.org/protobuf@v1.32.0
Fixed in: google.golang.org/protobuf@v1.33.0
Example traces found:
Error:       #1: pkg/driver/mount_linux.go:151:46: driver.NodeMounter.Unstage calls fmt.Sprint, which eventually calls json.Decoder.Peek
Error:       #2: pkg/driver/mount_linux.go:151:46: driver.NodeMounter.Unstage calls fmt.Sprint, which eventually calls json.Decoder.Read
Error:       #3: pkg/driver/mount_linux.go:151:46: driver.NodeMounter.Unstage calls fmt.Sprint, which eventually …
```
=> Address CVE GO-2024-2611

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml, charts/aws-ebs-csi-driver/values.yaml
Feature
Adding a flag to enable / disable test during pipeline when using chart-testing 
Manual / pipeline tests
=> Add helm-tester enabled flag

hack/tools/helm-runner.sh, hack/tools/install.sh
Executes #1864 by changing CT to use `--reset-then-reuse-values` instead of `--reuse-values`
Currently this is done via a workaround until https://github.com/helm/chart-testing/pull/531 or similar is merged, I will likely be submitting our own PR to `chart-testing` to add the ability to switch the upgrade method, but this will workaround that in our e2e tests and CI until such a feature is released.
Manually tested + CI
=> Add helm wrapper to convert --reuse-values to --reset-then-reuse-values for CT testing

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller_modify_volume.go
Feature
Today, if a user changes the [VolumeAttributeClass](https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/#:~:text=This%20page%20assumes%20that%20you,quality%2Dof%2Dservice%20levels.) of a PVC to one that is infeasible (i.e. volume type `gp7`), the external-resizer will immediately and continuously resend the infeasible request (with backoff). This leads to wasted work by the driver/k8s API and possible EC2 API throttling. 
In order to fix this, `ebs-plugin` must report an `INVALID_ARGUMENT` gRPC error code to the `external-resizer` when the VAC could never be possible, so that the `external-resizer` marks status as infeasible and re-queues the request with a much longer …
=> Return ErrInvalidArgument in cloud upon EC2 ModifyVolume

go.mod, tests/e2e/requires_aws_api.go
Bug fix e2e
Today we use a fixed tag name in our AWS volume and snapshot tagging single-az e2e tests. This may lead to collisions when multiple tests are done in parallel and/or test resources are not cleaned up properly (e.g. a test is aborted).
This should unblock CI, which is suffering from this problem. 
CI
=> Randomly generate tag names in e2e tests to prevent flakes due to collisions

cmd/hooks/prestop_test.go, hack/tools/install.sh, pkg/cloud/cloud_test.go, pkg/driver/controller_modify_volume_test.go, pkg/driver/controller_test.go, pkg/driver/node.go, pkg/driver/node_linux_test.go, pkg/driver/node_test.go, pkg/mounter/safe_mounter_unix_test.go, pkg/util/util.go, pkg/util/util_test.go, tests/integration/integration_test.go
Dependency upgrade
CSI driver team vs entropy & technical debt PR number seven hundred and eighty-seven.
This PR upgrades the `golangci-lint` dependency to latest and makes the necessary changes fixing linter errors to make the code more compliant with recommended best practices in Go.
`make verify && make test`
=> Upgrade golangci-lint

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml, charts/aws-ebs-csi-driver/values.yaml, hack/prow-e2e.sh
"Bug fix" for CI
1. Fixes quoting issues in Helm test pod causing disruptive tests to run (also cleans up the logic a bit to greatly increase readability)
2. Bumps kubekins image to latest tag
3. Removes `--reuse-values` workaround that is no longer needed
4. Add memory limit to tester pod, bump requests
5. Bump instance type to `c5.xlarge` for helm CI job
CI
=> Fixup Helm test job

hack/e2e/run.sh
Bug fix
Ran locally and found that pulling the new image can take longer than 60 seconds, which is longer than the current timeout value.
```
ct lint-and-install --config tests/ct-config.yaml &
------------------------------------------------------------------------------------------------------------------------
✔︎ aws-ebs-csi-driver => (version: "2.28.1", path: "charts/aws-ebs-csi-driver")
------------------------------------------------------------------------------------------------------------------------
All charts linted and installed successfully
```
=> Fix `ebs-csi-driver-test` CT pod timeout

.github/ISSUE_TEMPLATE/support-request.md
This PR updates the support issue template for the EBS CSI Driver repository to rectify an outdated reference to the Slack channel. Currently, the template mentions the non-existent channel name sig-aws, which may mislead users seeking support. The correct channel name is provider-aws. This update ensures that users are directed to the appropriate channel for AWS-related support queries, enhancing the efficiency of issue resolution and community engagement.
=> Update Support Issue Template to Reflect Correct Slack Channel Name for AWS Provider

hack/e2e/ecr.sh, hack/prow.sh
Bug fix
Buildkit 0.13.0 and above don't correctly forward `os.version` for Windows images in multi-arch manifests. Hardcode buildkit to 0.12.5
Manually tested locally via `./hack/prow.sh` (need to modify registry inside)
=> [master] Hardcode buildkit verison to 0.12.5

hack/e2e/ecr.sh, hack/prow.sh
Bug fix
Buildkit 0.13.0 and above don't correctly forward `os.version` for Windows images in multi-arch manifests. Hardcode buildkit to 0.12.5
Manually tested locally via `./hack/prow.sh` (need to modify registry inside)
=> [release-1.29] Hardcode buildkit verison to 0.12.5

charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml, deploy/kubernetes/base/clusterrole-snapshotter.yaml
bug fix
Closes #1983 by adding missing 'patch' verb to `clusterrole-snapshotter.yaml`
Followed #1983's reproduction steps, and saw the following message on VolumeSnapshotContent object (and also a similar error on VolumeSnapshot object):
```
Name:         static-snapshot-content
...
Status:
Error:
Message:     Failed to check and update snapshot content: failed to list snapshot for content static-snapshot-content: "rpc error: code = Internal desc = Could not get snapshot ID \"snap-07f7084a5d87a82b7\": InvalidSnapshot.NotFound: The snapshot 'snap-07f7084a5d87a82b7' does not exist.\n\tstatus code: 400, request id: 6a7ab5c4-f023-4ace-8faa-4bdc4685b155"
Time: …
```
=> Update voluemessnapshotcontents/status RBAC

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Feature
Coalesces EC2 DescribeVolumesModifications (DVM) polling across ControllerExpandVolume/ControllerModifyVolume/ModifyVolume RPCs by volumeID.
This decreases the likelihood of being exceeding one's [Non-mutating API request token limit](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html#throttling-limits) when modifying many volumes at once, which may impact all driver RPCs (ie being throttled for making too manyDescribe* calls).
Note: We do not batch any DVM call that we are unsure if a volume modification has been made for, due to undocumented behavior of a an error being returned if any volume queried for has never been modified. 
CI
Rested …
=> Batch polling of DescribeVolumesModifications

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Bug Fix
Today, the driver relies on the `DescribeInstances` API to determine the attachment state of a volume to an EC2 instance. The API may incorrectly report the volume as attached due to EC2's eventual consistency model, as a result the driver will skip making an expected `AttachVolume` API call and proceed to directly poll the attachment state of the volume.
This PR adds an explicit `AttachVolume` API call in the `WaitForAttachmentState` function when there is a mismatch between the expected attachment state and the actual attachment state reported for a volume. If the `AttachVolume` call fails, it is logged for debugging purposes but the overall behavior of returning an error and triggering …
=> Add explicit `AttachVolume` call in `WaitForAttachmentState`

cmd/hooks/prestop.go
Bug fix
_Handle deleted Node case in hook_
When the `Node` object does not exist, the existing hook returns an error. Instead, in this case, assume the node is being drained and proceed with the hook. Partially solves #1955
_Add support for CAS taint_
Similar to Karpenter, `cluster-autoscaler` has its own custom taint it uses when draining nodes. Add it to the hook's drain detection logic.
Manual/CI
=> Handle deleted Node case in hook; Add support for CAS taint

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Bug fix
Today, when we time out waiting for the volume to create, we delete it. This is broken for several reasons:
- It often doesn't even run, because the sidecar will have already closed the context elsewhere
- Whenever it does run, it will trigger #1951 when the CO re-calls `CreateVolume`
- It handles behavior that is the CO's responsibility according to the CSI spec:
```
//    The CO is responsible for cleaning up volumes it provisioned
//    that it no longer needs. If the CO is uncertain whether a volume
//    was provisioned or not when a `CreateVolume` call fails, the CO
//    MAY call `CreateVolume` again, with the same name, to ensure the
//    volume exists and to retrieve the volume's …
```
=> Remove DeleteDisk call in CreateDisk path

pkg/cloud/cloud.go, pkg/cloud/handlers.go
Bug fix
This PR ensures that throttled requests are correctly captured in the `cloudprovider_aws_api_throttled_requests_total` metric instead of `cloudprovider_aws_api_request_errors metric`.
`RecordThrottledRequestsMiddleware` has been removed as it is no longer needed.
```
// RecordRequestsHandler is added to the Complete chain; called after any request
func RecordRequestsMiddleware() func(*middleware.Stack) error {
return func(stack *middleware.Stack) error {
return stack.Finalize.Add(middleware.FinalizeMiddlewareFunc("RecordRequestsMiddleware", func(ctx context.Context, input middleware.FinalizeInput, next middleware.FinalizeHandler) (output …
```
=> Consolidate request handling in RecordRequestsMiddleware

pkg/driver/node.go
Currently, if K8s API client creation fails, it does so silently. Thus it is possible for `k8sClient` to be `nil`, which gets passed into `NewDriver` -> `NewNodeService`.  To avoid a panic, `removeTaintInBackground` should only be executed if the client is available.
```
k8sClient, err := cfg.K8sAPIClient()
if err != nil {
klog.V(2).InfoS("Failed to setup k8s client")
}
drv, err := driver.NewDriver(cloud, &options, m, md, k8sClient)
```
```
driver.node = NewNodeService(o, md, m, k)
```
```
if k != nil {
// Remove taint from node to indicate driver startup success
// This is done at the last possible moment to prevent race conditions or false positive removals
time.AfterFunc(taintRemovalInitialDelay, func() {
removeTaintInBackground(k, …
```
=> Run taint removal only if Kubernetes API is available

pkg/cloud/cloud.go
Improvement
Cut median dynamic provisioning latency in half (~3.7 to 2 seconds) by polling  EBS volume creation more agressively.  
Today, when dynamically provisioning a volume via our CreateVolume RPC, we wait 3s after an EC2 CreateVolume call to start polling DescribeVolumes. Based on testing in `us-west-2`, `ap-northeast-1`, and `us-east-1`, the p10 & median time between calling EC2 CreateVolume and the volume being created is ~1.5s. 
Polling every 3 seconds means that a typical CreateVolume RPC will take ~3.5 seconds (and a worse case of 6+ seconds once every hundred volumes). In this PR, we use a more aggressive initial delay and polling interval. Finally, we switch to an exponential backoff …
=> Decrease dynamic provisioning time by 1.5 seconds

pkg/coalescer/coalescer.go, pkg/coalescer/coalescer_test.go
New feature
Adds a independent `coalescer` package that will be used to migrate the coalescing in the `driver` package used for `ModifyVolume` requests.
Unit tests added as part of the PR
=> Implement separate coalescer package and unit tests

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/retry_manager.go
Improvement
Today, we sleep in cloud package tests due to hardcoding volume polling parameters inside `waitFor` functions like `waitForVolume`
This PR:
- Injects the volumeWaitParameters dependency
- Decreases cloud package unit test duration by ~9 seconds (from 12s to 3.3s)
- (Optional) Consolidates backoff parameters and explanatory comments to their own `volumeWaitParameters.go` file 
Note:  Will rebase once #2021 is merged. 
`make test`
=> Inject volumeWaitParameters dependency

Makefile, docs/makefile.md, hack/e2e/build-image.sh, hack/e2e/config.sh, hack/e2e/create-cluster.sh, hack/e2e/eksctl/cluster.yaml, hack/e2e/eksctl/eksctl.sh, hack/e2e/eksctl/patch.yaml, hack/e2e/kubeconfig.sh, hack/e2e/run.sh, hack/prow-e2e.sh, hack/tools/install.sh
"New Feature"
This PR is split into several much smaller commits:
<ins>Move WINDOWS and WINDOWS_HOSTPROCESS out of Makefile to correct location in config.sh</ins>
Small fix to remove unnecessary variables in the `Makefile`.
<ins>Use Prow BUILD_ID in CI jobs if present to greatly reduce the chance of cluster name collisions in CI</ins>
Prow jobs have a random chance of colliding because `$RANDOM` is only a 4 digit number (You'd think it's 1/10000 but it's much higher than that because of the [Birthday Paradox](https://en.wikipedia.org/wiki/Birthday_problem)).
Use `$BUILD_ID` in CI which is guaranteed to be unique. Had to cut off a little bit of the beginning of the name to make it short enough for …
=> `Makefile` & `hack/` Process Improvements

pkg/driver/controller.go, pkg/driver/controller_modify_volume.go, pkg/driver/controller_test.go, pkg/driver/request_coalescing_test.go
New feature
Replaces the previous mixed-in coalescer implementation with the new package from #2024
What this PR does NOT do, on purpose:
- *Significantly change the unit tests*: The unit tests could be refactored to mock the coalescer instead of cloud for the ModifyVolume tests (and probably should be, in the future). I chose not to do this in this iteration because it would be a significant overhaul, and keeping the unit tests as close as possible to the original best demonstrates this PR introduces no new bugs. I plan to refactor the coalescing-related tests in a follow up PR.
- *Refactor `cloud.ModifyDiskOptions` and `cloud.ModifyOrResizeDisk`*: I think the remaining `ModifyVolume` code could …
=> Replace coalescer implementation with new coalescer package

pkg/cloud/cloud.go
Improvement
Given that no throttling is observed for DescribeVolumes with 7k volume scalability tests, we reduced the current 1 second max batch delay to 500ms, and set that as the standard batcher delay. 
This PR makes sure each RPC takes ~0.25s of batch latency per EC2 Describe call on average (and worst case extra delay of 0.5s).  
This PR also makes sure each batcher will execute twice per second. In the rare case that each batcher is executing at once, the combined 12 requests per second is under the default [EC2 Non-Mutating Action Bucket Refill Rate](https://docs.aws.amazon.com/ec2/latest/devguide/ec2-api-throttling.html) of 20.
Scalability tests with batcher …
=> Tune batcher EC2 Describe* delays

go.mod
CVE Fix
```
Vulnerability #1: GO-2024-2824
Malformed DNS message can cause infinite loop in net
More info: https://pkg.go.dev/vuln/GO-2024-2824
Standard library
Found in: net@go1.22.2
Fixed in: net@go1.22.3
Example traces found:
Error:       #1: tests/e2e/testsuites/testsuites.go:752:78: testsuites.podLogs calls rest.Request.Do, which eventually calls net.Dialer.DialContext
Error:       #2: pkg/driver/driver.go:99:29: driver.Driver.Run calls net.Listen
Error:       #3: pkg/cloud/cloud.go:331:38: cloud.newEC2Cloud calls config.LoadDefaultConfig, which eventually calls net.LookupHost
Error:       #4: tests/e2e/format_options.go:33:17: e2e.init calls ginkgo.Describe, which eventually calls …
```
=> Address GO-2024-2824

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/templates/metrics.yaml, charts/aws-ebs-csi-driver/values.yaml
Added an option to configure the interval rate.
Fixes: #2004 
helm template. using this values.yaml :
```shell
enableMetrics: true
serviceMonitor:
forceEnable: true
labels:
release: prometheus
interval: "30s"
```
will get:
```shell
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: ebs-csi-controller
namespace: default
labels:
app: ebs-csi-controller
release: prometheus
spec:
selector:
matchLabels:
app: ebs-csi-controller
namespaceSelector:
matchNames:
- default
endpoints:
- targetPort: 3301
path: /metrics
interval: 30s
```
Default was set to 15 sec
=> Make scrape interval configurable

pkg/driver/controller.go, pkg/driver/node.go, pkg/util/util.go, pkg/util/util_test.go
Security enhancement
The EBS CSI Driver does not support [Token Requests](https://kubernetes-csi.github.io/docs/token-requests.html) , however - out of an abundance of caution - this PR addresses the potential vulnerability of sensitive information being logged inadvertently.
The main change is adding a new utility function `SanitizeRequest` that takes a request object and returns a copy of the request with the "Secrets" field cleared. This function creates a new instance of the same type as the input request, copies all the fields from the original request to the new instance, and sets the "Secrets" field to an empty map if it exists.
- `make verify && make test`
- CI …
=> Sanitize CSI RPC request logs

charts/aws-ebs-csi-driver/templates/ebs-csi-default-sc.yaml, charts/aws-ebs-csi-driver/values.yaml
Helm parameter
This PR introduces a new Helm parameter: `defaultStorageClass` which deploys a default StorageClass object.
When the `defaultStorageClass.enabled` parameter is set to `true` (disabled by default), either in the `values.yaml` file or as a CLI argument during installation or upgrade, the following default StorageClass is deployed:
```
apiVersion: storage.k8s.io/v1
metadata:
name: ebs-csi-default-sc
annotations:
storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```
`make test && make verify`
```
helm upgrade --install aws-ebs-csi-driver …
```
=> Add `defaultStorageClass` parameter

hack/tools/install.sh
Bug fix
Audited dependencies for any unpinned versions. `kubetest2` was the only seen unpinned one. By pinning this we make sure no faulty upstream change breaks our CI, as has happened with previous unpinned dependencies.
`make clean; make tools; kubetest2 --help`
=> Pin kubetest2 dependency

charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/clusterrolebinding-csi-node.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml, charts/aws-ebs-csi-driver/values.yaml, docs/faq.md, go.mod
=> add namespaceOverride support

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Bug fix
PR is about making subject namespace in ClusterRoleBinding generated based on the namespace release is being deployed to.
With previous hardcoded value of kube-system the test was failing because ServiceAccount didn't have proper permissions assigned, if it was deployed to different namespace than kube-system.
It was deployed into test cluster and ended up with successful execution after deploying to custom namespace.
=> Use {{ .Release.Namespace }} in ClusterRoleBinding subject namespace

charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/node.yaml
This is adding a new feature.
This PR gives the customer the ability to change their EBS CSI Node Pod termination grace period.  
I ran helm locally on my dev cluster with a 
--set node.terminationGracePeriodSeconds=34
and with no terminationGracePeriodSecounds parameter and could see that with no parameter terminationGracePeriodSecounds was set to 30 on my pods and with the 
--set node.terminationGracePeriodSeconds=34 i could see that terminationGracePeriodSeconds on my pod was 34 seconds
=> Add terminationGracePeriodSeconds as a helm parameter

charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml
Improvement
Today, the max backoff period for any sidecar RPC is 5 minutes. This is problematic if the user has a misconfigured K8s object (such as invalid IOPS for volume type) because the invalid request will be retried to the EC2 backend every 5 minutes until user resolves the issue. 
Increase default provisioner, resizer, snapshotter `retry-interval-max` to 30 minutes. 
Deploy driver via helm with default values. 
```
❯ kubectl get pod -n kube-system ebs-csi-controller-9d9969b74-4mcgp -o yaml | grep "retry-interval"
- --retry-interval-max=30m
- --retry-interval-max=30m
- --retry-interval-max=5m
- --retry-interval-max=30m
```
WIP: Tested by trying to provision volume …
=> Increase default provisioner, resizer, snapshotter `retry-interval-max`

charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml
Helm parameter
**Note to reviewers:** `seccompProfile` has now been set to `RuntimeDefault`, which uses the default seccomp profile provided by the container runtime. This helps to restrict the system calls the containers can make, enhancing security. Do note that this changes the current default (unspecified, thus `Unconfined`):
```
const (
// SeccompProfileTypeUnconfined is when no seccomp profile is applied (A.K.A. unconfined).
SeccompProfileTypeUnconfined SeccompProfileType = "Unconfined"
// SeccompProfileTypeRuntimeDefault represents the default container runtime seccomp profile.
SeccompProfileTypeRuntimeDefault SeccompProfileType = "RuntimeDefault"
// SeccompProfileTypeLocalhost represents …
```
=> Set RuntimeDefault as default seccompProfile in securityContext

pkg/cloud/metadata/ec2.go, pkg/cloud/metadata/metadata_test.go, pkg/util/util.go, pkg/util/util_test.go
bug fix
Fixes #2064; Fixes a regression in calculating currently attached ENIs in our `EC2MetadataInstanceInfo` function to calculate CSINode allocatable count when not using `reservedVolumeAttachments`.  
Instead of checking for newlines, we should check for counts of a relevant regex, to avoid inconsistencies when IMDS returns or doesn't return a newline at end of response. 
Can confirm that there is no newline when querying IMDS for number of attached ENIs: 
```
> && curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/network/interfaces/macs
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload …
```
=> Fix EC2MetadataInstanceInfo ENI calculation

charts/aws-ebs-csi-driver/templates/_node.tpl
This is a bug fix
Previously the parameter enableLinux did not work because it was set to true regardless of what you pass in as a parameter
I deployed my dev cluster with the change and ran the following command to install the driver with enableLinux set to false
```
helm upgrade \
--install aws-ebs-csi-driver \
--namespace kube-system \
./charts/aws-ebs-csi-driver \
--set controller.replicaCount=1 \
--set image.pullPolicy=Always \
--set controller.logLevel=7 \
--set image.repository="533267024531.dkr.ecr.us-west-2.amazonaws.com/aws-ebs-csi-driver"\
--set image.tag="TEST-ELIJAH-linux-amd64-al2023" \
--set node.enableLinux="false"
```
I then ran ```kubectl -n kube-system …
```
=> Add fix for enableLinux node parameter

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/devicemanager/allocator.go, pkg/cloud/devicemanager/allocator_test.go, pkg/cloud/devicemanager/manager.go, pkg/cloud/devicemanager/manager_test.go, pkg/expiringcache/expiring_cache.go, pkg/expiringcache/expiring_cache_test.go
Fixes #1951
If `CreateVolume` fails for any reason (examples: the user provides an invalid KMS key, due to an EBS-side issue, etc), we retry with the same client token. However, despite the fact that the `CreateVolume` call corresponds to a volume that was never created, our client token is burned.
In the scenario where we detect this has occurred, this PR tries again with a different token. However, to prevent volume leaks, the token must follow a predictable pattern. To do this, I append `-2` to the volume id pre-hashing for the token, and if that request fails, I instead append `-3`, `-4`, etc. This is done strictly in order, so a CSI driver that crashes (or restarts for any other reason, such …
=> Use new client token when `CreateVolume` returns `IdempotentParameterMismatch`

cmd/main.go, pkg/cloud/metadata/k8s.go, pkg/driver/options.go
Feature
This adds a command-line flag, `--kubeconfig`, that allows an alternative to `rest.InClusterConfig()`.  This is useful when running the CSI driver outside of a Pod.
If `--kubeconfig` is empty, the behavior is unchanged.
I see the k8s client instantiated successfully:
```
> CSI_NODE_NAME=ip-192-168-69-200.us-west-2.compute.internal bin/aws-ebs-csi-driver --kubeconfig ~/.kube/config
I0704 00:50:11.709966   21408 main.go:157] "Initializing metadata"
I0704 00:50:11.710049   21408 metadata.go:66] "The AWS_EC2_METADATA_DISABLED environment variable disables access to EC2 IMDS" enabled="true"
E0704 00:50:11.710363   21408 metadata.go:51] "Retrieving IMDS metadata …
```
=> Add --kubeconfig flag for out-of-cluster auth

pkg/coalescer/coalescer.go
Bug fix (internal facing, not customer facing)
`InputType` in the coalescer shouldn't be `comparable` as we don't use it as a key anywhere. Requiring it to be `comparable` breaks coalescing with types that are not comparable such as maps, slices, etc. (for example see PR #2082 where it had to be added as a pointer instead of a map directly).
CI
=> Change coalescer InputType from `comparable` to `any`

charts/aws-ebs-csi-driver/templates/controller.yaml
bug fix
Fix the indentation of `dnsConfig` option in controller.yaml. It should be at the same level of `template.spec.containers`, but before this change, it was as `template.spec` level.
edit the values.yml and set a custom configuration, iE:
```yaml
dnsConfig:
options:
- name: ndots
value: "2"
```
The manifest you get from the previous is:
```yaml
....
- name: liveness-probe
image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.13.0-eks-1-30-8
imagePullPolicy: IfNotPresent
args:
- --csi-address=/csi/csi.sock
volumeMounts:
- name: socket-dir
mountPath: /csi
resources:
limits:
memory: 256Mi
requests:
cpu: 10m
memory: 40Mi
securityContext: …
```
=> fix dnsConfig indentation in controller template file

go.mod, go.sum
Bug fix
See title, fixes `govulncheck` blocking all PRs
CI
=> govulncheck: Bump google.golang.org/grpc to v1.64.1

pkg/cloud/cloud.go
This is a fix for comment section of function.
This PR fixes a wrong function name in the comment above the isAWSErrorBlockDeviceInUse function.
=> fix function name in comment

docs/example-iam-policy.json, docs/tagging.md, examples/kubernetes/modify-volume/README.md, examples/kubernetes/modify-volume/manifests/volumeattributesclass.yaml, hack/e2e/kops/patch-cluster.yaml, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/ec2_interface.go, pkg/cloud/interface.go, pkg/cloud/mock_cloud.go, pkg/cloud/mock_ec2.go, pkg/driver/controller.go, pkg/driver/controller_modify_volume.go, pkg/driver/controller_modify_volume_test.go, pkg/driver/request_coalescing_test.go, tests/e2e/modify_volume.go, tests/e2e/testsuites/e2e_utils.go, tests/e2e/testsuites/modify_volume_tester.go
New Feature
This feature allows for EBS CSI Driver customers to Add, Modify, and Delete tags of existing volumes via the official CSI `ControllerModifyVolume` RPC through a `VolumeAttributesClass`.
Besides running existing unit and e2e tests, this feature was tested manually by doing the following:
1. Make test cluster by running `make cluster/create`
2. Creating and uploading image of driver with changes to ECR Repo
3. Deploying driver to cluster via helm, with the necessary flags. 
4. Creating various testing VolumeAttributesClass documents
5. Applying VACs and verifying that the correct tag operations were performed on the volume by describing the volume and looking …
=> Modifying Tags On Existing Volume

examples/kubernetes/static-provisioning/README.md, examples/kubernetes/static-provisioning/manifests/pv.yaml, examples/kubernetes/storageclass/manifests/storageclass.yaml, pkg/driver/controller.go, pkg/driver/controller_test.go, tests/e2e/driver/ebs_csi_driver.go
*Is this a bug fix or adding new feature?**
Feature
See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/729#issuecomment-1942026577
CI/Manual
=> Migrate CreateVolume response topology to standard label topology.kubernetes.io/zone

deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, go.mod, go.sum
Bug fix
Fixes #2090
Manually tested but long-term we need a CI job for each overlay that runs on `release-*` branches
```
$ kubectl apply -k deploy/kubernetes/overlays/stable/gcr                          
serviceaccount/ebs-csi-controller-sa created
serviceaccount/ebs-csi-node-sa created
role.rbac.authorization.k8s.io/ebs-csi-leases-role created
clusterrole.rbac.authorization.k8s.io/ebs-csi-node-role created
clusterrole.rbac.authorization.k8s.io/ebs-external-attacher-role created
clusterrole.rbac.authorization.k8s.io/ebs-external-provisioner-role created
clusterrole.rbac.authorization.k8s.io/ebs-external-resizer-role created …
```
=> Bump GCR sidecars that reference broken tags

deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Cherry pick of first commit of #2091 to `master`
/cc @torredil 
=> [cherry-pick] Bump GCR sidecars that reference broken tags

charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml
bug fix #2101 
sidecars.snapshotter.logLevel does not take affect when change the log level in values.yaml.
=> fix: sidecars.snapshotter.logLevel not being respect

pkg/cloud/cloud_test.go, pkg/driver/controller_modify_volume_test.go, pkg/driver/controller_test.go, pkg/driver/driver_test.go, pkg/driver/validation.go, pkg/driver/validation_test.go
This adds more units tests for more code coverage.
As driver and Cloud coverage are both below 90% coverage this PR is to add more coverage to those areas
Ran the unit tests to validate they pass and ran make test/coverage to verify that the coverage had increased after each unit test was added
=> add more unit tests to increase test coverage

charts/aws-ebs-csi-driver/templates/clusterrole-attacher.yaml, charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml, charts/aws-ebs-csi-driver/templates/clusterrole-resizer.yaml, charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-provisioner.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-resizer.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshotter.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/csidriver.yaml, charts/aws-ebs-csi-driver/templates/ebs-csi-default-sc.yaml, charts/aws-ebs-csi-driver/templates/metrics.yaml, charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml, charts/aws-ebs-csi-driver/templates/role-leases.yaml, charts/aws-ebs-csi-driver/templates/rolebinding-leases.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml, charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml, charts/aws-ebs-csi-driver/values.yaml
/feature
Add a nodeComponentOnly parameter to helm chart.
Here are helm template results with and without setting nodeComponentOnly=true, as well as the diff (as textfiles because gists don't support yaml):
[nodeComponentOnlyTemplate.txt](https://github.com/user-attachments/files/16565770/controllerDisabledTemplate.txt)
[defaultChart.txt](https://github.com/user-attachments/files/16565771/defaultChart.txt)
[diff.txt](https://github.com/user-attachments/files/16565773/diff.txt)
Also deployed the driver with this setting:
```
helm upgrade \
--install aws-ebs-csi-driver \
--namespace kube-system \
$HOME/workplace/aws-ebs-csi-driver/charts/aws-ebs-csi-driver \
--values …
```
=> Add nodeComponentOnly parameter to helm chart

hack/generate-gpu-count-table.sh, hack/generate-instance-store-table.sh, pkg/cloud/volume_limits.go, pkg/driver/node.go, pkg/driver/node_test.go
bug fix to address part of gh [#2105](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2105) gpus not being considered when counting allocatables.
We need this PR in order to fix the above referenced bug
Compared manually to [list of gpu instances](https://aws.amazon.com/ec2/instance-types/)
and created unit tests for instances mentioned in ticket and for a gpu instance with 4 gpus.
=> Fix gpus not being considered when counting allocatables

charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml, charts/aws-ebs-csi-driver/values.yaml
/feature
Fixes #1934 
The EBS CSI Controller Pod's [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) ensures that 1 controller Pod is always running, even when many nodes are being drained at once. This ensures that PersistentVolumes are always able to be Attached/Detached Created/Deleted, and that stateful pods are not delayed by missing PVs. 
Some customers have requested ability to disable this PodDisruptionBudget  in order to prioritize node draining / Karpenter consolidation over the availability of the EBS CSI Driver. While we don't recommend this, this PR exposes the parameter for those who use EBS only with non-critical applications.  
**What testing is …
=> Add toggle for PodDisruptionBudget in chart

charts/aws-ebs-csi-driver/templates/controller.yaml, docs/modify-volume.md
Feature
Automatically enable VAC on clusters using the beta API version. This improves the experience for beta users and ensures they do not accidentally create a volume with a VAC bound that was not applied due to the feature gate being disabled.
Also updates the VAC documentation to reflect this, and fix a few minor issues.
Templating:
```
$ helm template charts/aws-ebs-csi-driver | grep VolumeAttributesClass
<blank output>
$ helm template charts/aws-ebs-csi-driver --api-versions "storage.k8s.io/v1beta1/VolumeAttributesClass" | grep VolumeAttributesClass
- --feature-gates=VolumeAttributesClass=true
- --feature-gates=VolumeAttributesClass=true
```
Also tested manually …
=> Auto-enable VAC on clusters with beta API version

hack/generate-gpu-count-table.sh, hack/generate-instance-store-table.sh, pkg/cloud/volume_limits.go, pkg/driver/node.go, pkg/driver/node_test.go
bug fix fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2105
This PR fixes GH https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2105 as before we where not taking accelerators into consideration when calculating volume limits  
I spun up and hand added ebs volumes to an instance in each accelerator family to ensure there where no special cases outside of the VT1 family where accelerators take up two slots. 
Additionally I found that the calculation in node.go was incorrect for any instance type in the maxVolumeLimits table the documentation states that for the instance types in that table the calculation of 28 - enis - …
=> Fix accelerators not being considered when counting allocatables

charts/aws-ebs-csi-driver/templates/controller.yaml, docs/modify-volume.md
Revert of #2114
Based on testing, we don't want to auto-enable VAC until the sidecars we ship with the driver support beta API version instead of alpha. We expect that to happen in the next upstream external-resizer/external-provisioner releases but not before our August release.
N/A
=> Backout VAC auto-enable

docs/install.md
Documentation
This PR adds documentation to `install.md`'s prerequisite section that metadata is required, as well as information about available metadata sources.
N/A, docs only
=> Document metadata requirement and available sources

docs/faq.md
Update faq.md with Karpenter best practices since Karpenter v1.0.0's [fix: Ensure persistent volumes are detached before deleting node](https://github.com/kubernetes-sigs/karpenter/pull/1294)
=> Update faq.md with Karpenter best practices

.github/workflows/govulncheck.yaml
N/A
This makes the govulncheck github action only run on PRs merging into release branches:
- New vulnerability blocks the merge of a new contributor, requiring a rebase. This is not a great contributor experience and has led to delays due to PR churn.
The risk here is that we suddenly find out about a vulnerability for our release PR, instead of in any pr, which may delay our release by 1-3 hours (due to waiting for CI to re-run). But that should be rare since we are bumping dependencies right before a release anyway.
CI
=> Make govulncheck only run on release branches

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release 1.35

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml
Bug fix
VAC feature gate is applied to the wrong sidecar (attacher instead of resizer), fix that and push a new Helm release.
Manual
=> [master] Fix csi-attacher crash due to VAC feature gate on wrong sidecar

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml
Bug fix
VAC feature gate is applied to the wrong sidecar (attacher instead of resizer), fix that and push a new Helm release.
Manual
=> [release-1.35] Fix csi-attacher crash due to VAC feature gate on wrong sidecar

pkg/cloud/metadata/k8s.go
This MR is a part of effort to elevate single eks cluster performance by migrating the EKS components to use protobuf instead of json.
Modify kubeconfig type to use content type application/vnd.kubernetes.protobuf instead of json for performance gain.
This change essentially lets the ebs driver (client) to talk to apiserver using protobuf and falls back to json if protobuf isn't supported. It will only affect the wire format between ebs driver and apiserver.
=> use protobuf content type instead of json for k8s client

tests/e2e/testsuites/modify_volume_tester.go
bug fix
External-provisioner + resizer only list v1beta1 versioned `VolumeAttributeClass`es
These tests are currently turned off in our CI due to no Kubernetes 1.31 cluster creation yet.  
In progress, manual single-az test on 1.31 cluster
=> Upgrade vac to beta in e2e tests

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/serviceaccount-csi-controller.yaml, hack/e2e/run.sh, pkg/cloud/devicemanager/allocator_test.go, pkg/expiringcache/expiring_cache_test.go
Bug fix, mostly
Fixes four small papercuts:
This should prevent code coverage constantly flapping on this test by properly setting up the `existingNames` map. Also, added some comments to make the test more clear.
This test flakes all the time in CI, especially on the Windows unit tests. I bumped up the sleeps to hopefully combat this, it's set to run in parallel so shouldn't make a significant difference to overall test time.
Our helm chart contains two places that are used to magically inject comments into the Kustomize deployment. Remove these to standardize the chart and because they're bad:
- In `controller.yaml`, the Kustomize deployment comments out the mode by default, thus running the …
=> Fix four small papercuts

.github/workflows/trivy-containers.yaml
Bug fix
The version of the `yq` GitHub action was mistakenly pinned from `master` to `4` in - when it should have been pinned to `v4`.
N/A / CI
=> Fix yq action version typo

docs/modify-volume.md, docs/tagging.md, examples/kubernetes/modify-volume/README.md, examples/kubernetes/modify-volume/manifests/pod-with-volume.yaml, examples/kubernetes/modify-volume/manifests/volumeattributesclass.yaml
Update
The current ModifyVolume example will not work with aws-ebs-csi-driver version >= v1.35.0 due to the VolumeAttributesClass object upgrading to v1beta1 in Kubernetes v1.31 and external sidecars. 
Also decreased volume size and iops to be more frugal.
Am open to updating `modify-volume.md` further to remove steps that are no longer relevant for aws-ebs-csi-driver >= 1.35.0 (i.e. adding feature gate on sidecars manually instead of relying on our helm chart)
Going through example manually
=> Update VolumeAttributesClass example to beta

charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml, charts/aws-ebs-csi-driver/values.yaml
New feature
I opened an issue #2146 asking for support for the new `unhealthyPodEvictionPolicy` for the PDB in the chart.
I generated a helm template file locally and tried to set `unhealthyPodEvictionPolicy` in the chart values to `AlwaysAllow` with a successful output.
=> feat: Added new policy to PodDisruptionBudget

docs/parameters.md
A typo in the documentation
If we compare it to: https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies, the doc contain the the availability zone and not the region.
None ATM, just reading the docs.
=> docs: Fix typo in volume topology zone match label

docs/example-iam-policy.json
"Feature"
Adds `ec2:EnableFastSnapshotRestores` to the example IAM policy
This is already present in the policy used by kops for testing, so it is already tested
=> Add EnableFSRs to example policy

docs/faq.md
Documentation
See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2153 for context.
=> Update FAQ to include section on Volume Attachment Capacity Issues

pkg/cloud/cloud_test.go, pkg/driver/options.go
spelling fix
Fixes two spelling errors found from [Go report card](https://goreportcard.com/report/github.com/kubernetes-sigs/aws-ebs-csi-driver#misspell)
N/A
=> Fix typos in options.go and cloud_test.go

.github/workflows/generate-code-coverage.yaml, .github/workflows/trivy-containers.yaml, .github/workflows/trivy.yaml
Dependency
Bump the following GitHub actions:
- [github/codeql-action](https://github.com/github/codeql-action) from 2 to 3.
- v2 is deprecated, support will end Dec 5, 2024 [(source)](https://github.com/github/codeql-action?tab=readme-ov-file#supported-versions-of-the-codeql-action)
- [aquasecurity/trivy-action](https://github.com/aquasecurity/trivy-action) from 0.16.1 to 0.26.0*
- [Changelog here](https://github.com/aquasecurity/trivy-action/releases)
- [actions/upload-artifact](https://github.com/actions/upload-artifact) from 3 to 4.
CI, changelog read-through, what else should be done? 
Confirmed no [upload-artifact v3 to v4 migration …
=> Bump GH actions (trivy, codeql, upload-artifact)

charts/aws-ebs-csi-driver/templates/_helpers.tpl, charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl
helm
The driver node plugin must stay running after all stateful workloads are evicted from pod so that it can Unpublish/Unstage volumes and report that back to the Kubelet. Therefore, EBS CSI Driver Daemonset needs to tolerate auto-scalar node drain/deletion taints if customers have set `node.TolerateAllTaints=false`
With this PR we tolerate 3 common auto-scalar taints:
- [Cluster Autoscaler](https://github.com/kubernetes/autoscaler/blob/d2077d6294bc29b7dea4d38e3aea65ecde3d598e/cluster-autoscaler/utils/taints/taints.go#L40)
- [Karpenter v1](https://github.com/kubernetes-sigs/karpenter/blob/a860293883b67cbda0b8f7917130ccd6857b6cc3/pkg/apis/v1/taints.go#L27)
- [Karpenter …
=> helm: add recommended autoscalar Tolerations to driver DaemonSet

Makefile, charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml, charts/aws-ebs-csi-driver/values.yaml, docs/makefile.md, hack/release-scripts/update-e2e-images
Automation
First, this PR automates two manual steps of our release process: updating the kubekins e2e image in our Helm chart, and updating the gcb-docker-gcloud image in our cloudbuild.yaml.
It combines these updates with our sidecar update script in the new Makefile target: `update-image-dependencies`
---
Second, kubekins-e2e is [deprecated](https://github.com/kubernetes/test-infra/tree/master/images/kubekins-e2e), so let's move to [kubekins-e2e-v2](https://github.com/kubernetes/test-infra/tree/master/images/kubekins-e2e-v2)
Quote from [Kubernetes SIG-Testing slack](https://kubernetes.slack.com/archives/C09QZ4DQB/p1708956700866859):
- It is leaner than the old image. We got rid of many legacy …
=> Automate image dependency upgrades & Migrate to kubekins-e2e-v2

pkg/cloud/volume_limits.go
Bug fix
Add m8g, c8g, x8g, g6e, and p5e attachment limits
See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html
`hack/generate-table` scripts
=> Add m8g, c8g, x8g, g6e, and p5e attachment limits

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Bug fix
In `WaitForAttachmentState`, we bail to calling `AttachVolume` and immediately returning an error if the volume was reported as attached by `DescribeInstances` (i.e. if `alreadyAssigned` is true), but the volume returns a state other than `attached`. This check exists to guard against the case where `DescribeInstances` is incorrect, bailing early allows us to get the attachment moving and avoid sitting in an infinite loop until a timeout occurs.
However, this is incorrect - we should only perform this action if the volume is `detached`, not all states other than `attached`. This is for two reasons:
1. Making an `AttachVolume` call when the volume is in a state other than `detached` will …
=> Only bail to AttachVolume if volume is detached

.github/dependabot.yaml, docs/updating-dependencies.md
N/A
Performing all dependency upgrades during the release process leads to delays when a certain upgrade contains breaking changes. Let's decrease the chance of release delays by spreading most of these updates out before we start a release, and automate that work with  [GitHub's Dependabot](https://github.com/dependabot). Even better, dependabot cleanly shows release notes, changelogs, and even commits for each dependency it is upgrading in its PR.
See the new `docs/updating-dependencies.md` for an introduction to Dependabot and our project dependencies. 
Let's start with a weekly cadence. If we find that too many dependencies occur in same PR such that troubleshooting breaking changes becomes …
=> Add Dependabot for Go module & GitHub Action dependencies

docs/parameters.md
Fixes a mistake in one of the notes about allowed topologies for storage classes.
=> Update parameters.md to fix a typo in `allowedTopologies`

CHANGELOG.md, README.md, charts/aws-ebs-csi-driver/templates/NOTES.txt
Docs update
Adds a warning about the upcoming IAM changes to `CreateVolume` to the README, CHANGELOG, and Helm NOTES.txt (which Helm will display when the chart is upgraded/installed)
N/A
=> Add warning about upcoming IAM update

hack/e2e/config.sh, hack/e2e/kops/kops.sh, hack/tools/install.sh
CI
This PR should not be merged until we fix any rate-limit issues in our CI (likely by submitting a PR to kops for different retry policies) 
We want our CI to test changes to the EBS CSI Driver against the latest stable version of Kubernetes to proactively spot issues and guarantee that we pass the Kubernetes Storage conformance tests.
However, EKS and recently kOps do not release support for the latest stable Kubernetes version until 1-2 months afterwards, which blocks us from upgrading our CI to the latest Kubernetes version.
Many of upstream e2e tests run against newer versions of Kubernetes without the latest kops version (see [test-infra …
=> Add K8s 1.31 to CI by pinning kops commit instead of version

pkg/mounter/mount_unsupported.go
Developer Experience
Fixes #1556 
EBS CSI Driver does not support MacOS, but contributors may only have a mac development machine. Therefore the project should compile well enough for the typical development loop (e.g. build, running unit and e2e tests). 
As issue #1556 puts it "I should be able to run the e2e tests from my laptop without having to jump through hoops."
`make test` and ran e2e tests
=> Stub nodeService to improve macos devloop

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Bug fix.
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2198
```
helm test aws-ebs-csi-driver -n kube-system &
kubectl logs ebs-csi-driver-test -n kube-system -f
Test Suite Passed
kubetest2 test run completed.
```
=> Fix fetching test package version for kubetest in helm-tester

pkg/cloud/cloud.go, pkg/cloud/handlers.go
Both? Kinda?
Fixes #2154
When the SDK hits a retryable error (for example, most server errors or network issues), it does not log the error in the log, preventing users and maintainers from discovering the nature of the issue. There is a built in logger for retries, but it would be sub-optimal to use that because it would flood the logs any time `RequestLimitExceeded` errors occurred. Thus, this PR instead introduces a simple logging middleware that allows us to customize the verbosity of the error message based on whether the error is a RLE/throttle error.
Manually tested (We don't have a way to test log messages atm, and maybe shouldn't even be doing so)
=> Add middleware to log server errors

hack/e2e/util.sh
Makefile/CI change
Because the tag is based on the cluster name, not setting `image.pullPolicy` in dev can lead to stale images. Set it to `Always` so that a fresh image is guaranteed.
Manually tested + CI
=> Set image.pullPolicy to Always for Makefile installations

hack/e2e/kops/patch-cluster.yaml
/kind cleanup
Update patch-cluster.yaml to v1beta1 for Vac so we can use our own VAC example in CI for Kops clusters.  
=> Update patch-cluster.yaml to v1beta1 for Vac

.github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
Add release-note to pull request template so that we can think about release-notes at PR time and use [Kubernetes release-notes generator](https://github.com/kubernetes/release/blob/master/cmd/release-notes/README.md) instead of hand-crafting release notes at the end of each release. 
Also switches first question to suggesting to add a GitHub label. Hopefully one-day we can add an `area/helm` label as well. 
**Impact**: Saves ~25 minutes crafting release notes (if you aren't using [OSS-Repo-Management-Tools/get_pull_requests_since_last_version](https://github.com/AndrewSirenko/OSS-Repo-Management-Tools/blob/main/get_pull_requests_since_last_version)), and a team check-in about what note goes where. 
N/A
```release-note
NONE
```
=> Upgrade Pull Request Template

Makefile, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/metrics.yaml, cmd/main.go, deploy/kubernetes/base/node.yaml, go.mod, pkg/driver/node.go, pkg/driver/options.go, pkg/driver/options_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/nvme.go, pkg/metrics/nvme_test.go, pkg/metrics/nvme_windows.go, tests/e2e/nvme_metrics.go, tests/e2e/testsuites/testsuites.go
New feature.
This PR adds support for collecting detailed performance statistics for CSI managed devices. The log page for each device is retrieved at gather time, transformed into a prometheus-compatible format, and exposed at a `/metrics` HTTP endpoint.
```
make verify && make test
ginkgo run --focus='should create a stateful pod and read NVMe metrics from node plugin' -v
Test Suite Passed
```
```
curl 127.0.0.1:3302/metrics
...
volume_queue_length{instance_id="i-0725b88fb342cd1c9",volume_id="vol-0aa37802a7c970c8e"} 0
write_io_latency_histogram_bucket{instance_id="i-0725b88fb342cd1c9",volume_id="vol-0aa37802a7c970c8e",le="1"} 0 …
```
=> Expose NVMe Volume Metrics

.github/workflows/trivy-containers.yaml, .github/workflows/trivy.yaml
This PR removes trivy scans that run on push to master. Since we're already scanning all PRs before they get merged, running the scan on master push is redundant.
Similar change for the container image scan workflow, it is desirable to run them only once, daily.
CI
```release-note
NONE
```
=> Fixup trivy workflows

tests/e2e-kubernetes/manifests.yaml, tests/e2e-kubernetes/volumeattributesclass.yaml, tests/e2e/modify_volume.go
/kind cleanup
This PR enables VAC testing 
CI 
```release-note
NONE
```
=> Enable VAC tests

charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/values.yaml
Adding a new feature
Adds the ability to add init containers to the node daemonset with the helm chart. 
The controller has this configuration. We have a use case where we would like to use an init container on the node to set the hop limit on each node in our cluster that uses the csi driver. 
I was only able to test this on a Linux cluster, I do not have any windows nodes. 
Using the following values file
```yaml
node:
initContainers:
- name: wait
image: busybox
command: ['sh', '-c', "sleep 20"]
```
Generates the following manifest for the node-daemonset
```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
name: ebs-csi-node
namespace: default
labels: …
```
=> Add helm chart configuration to add init containers to the node daemonset 

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release v1.37.0

.github/workflows/trivy-containers.yaml, .github/workflows/trivy.yaml
/kind cleanup
This should eliminate or greatly reduce the number of `TOOMANYREQUESTS` errors hit by the Trivy action via:
- Only running the PR scanner on PRs to release branches (which is where we care about avoiding vulnerabilities in our dependencies)
- Adds ECR Public as a fallback to both Trivy actions
N/A
```release-note
NONE
```
=> Fix Trivy TOOMANYREQUESTS errors

deploy/kubernetes/base/controller.yaml, hack/update-kustomize.sh
/kind feature
Fixes #2238 
After discussion, we decided for a consistent experience and because the downsides are significant if a user attempts to use it while disabled on the sidecars, we will enable the VAC feature gate for the Kustomize deployment. 
Manually tested + CI
```release-note
[TODO AFTER GENERATING RELEASE NOTES: Move to "Urgent Upgrade Notes" section] Enables the `VolumeAttributesClass` by default for the Kustomize deployment. If you are deploying using the Kustomize manifests on a cluster that does not have the `VolumeAttributesClass` feature gate enabled on the control plane, you may see harmless extra failures related to the feature in the csi-provisioner and/or csi-resizer logs.
```
=> Enable VAC feature gate for Kustomize deployments

charts/aws-ebs-csi-driver/values.yaml, cmd/main.go, docs/metrics.md, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/handlers.go, pkg/driver/options.go, pkg/driver/options_test.go, pkg/metrics/metrics.go, pkg/metrics/nvme.go, pkg/metrics/nvme_test.go, tests/e2e/dynamic_provisioning.go, tests/e2e/nvme_metrics.go, tests/e2e/pre_provsioning.go
/kind cleanup
This PR updates the metrics registered by the node plugin to align with Prometheus best practices by:
- Adding a `aws_ebs_csi` namespace prefix.
- Following Prometheus conventions such as adding `_total` suffix for counter metrics.
- Using base units (seconds) instead of microseconds.
It also introduces a new parameter `controller.deprecatedMetrics` to disable registering the existing controller metrics that use an outdated namespace, such as:
```
cloudprovider_aws_api_request_duration_seconds_bucket{request="AttachVolume",le="0.005"} 0
```
Metrics using the new namespace will be registered by default if `controller.enableMetrics` is configured:
```
aws_ebs_csi_api_request_duration_seconds_bucket{request="AttachVolume",le="0.005"} 0
```
- `make verify && make test`
- …
=> Update metrics to align with Prometheus best practices

charts/aws-ebs-csi-driver/templates/metrics.yaml, charts/aws-ebs-csi-driver/values.yaml
/kind bug
Enabling node metrics causes helm apply failure on malformed yaml. 
The flag for enabling the it is missing from `values.yaml`.
By installing and upgrading the chart - 
```
helm -n kube-system diff upgrade aws-ebs-csi-driver helm-charts/aws-ebs-csi-driver --reset-then-reuse-values --set node.enableMetrics=true
```
```release-note
Helm chart failed to install/upgrade if `node.enableMetrics=true` was set.
```
=> enabling node metrics causes helm apply failure on malformed yaml

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
/kind release
This is a release PR
CI/Manually
```release-note
NONE
```
=> Release v1.38.0

Dockerfile, Makefile, charts/aws-ebs-csi-driver/templates/_helpers.tpl, charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, docs/fips.md, docs/makefile.md, hack/cloudbuild.sh
/kind feature
This PR adds a FIPS image and helm chart option `fips` that enables that image as well as deplying with the environment variable needed to instruct the AWS SDK to use FIPS endpoints.
Manually/CI
```release-note
Build additional FIPS image and add Helm FIPS parameter
```
=> Add FIPS image and Helm option

docs/metrics.md
This pr adds documentation that seems to be missing for node.enableMetrics figured this would be important given the metric endpoints are on different ports 
No test needed docs 
NONE
```release-note
```
=> Update metrics.md to included quick start for node.enableMetrics 

Makefile, hack/e2e/build-image.sh
/kind cleanup
Fixes two issues currently flaking our CI left and right:
- Use a different tag when pushing the FIPS image in `sub-push-fips`
- Switch `make cluster/image` from `all-push` to `sub-push` so it doesn't waste time building the a1compat and FIPS images
Manual/CI
```release-note
NONE
```
=> Fixup FIPS Makefile/E2E

charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/values.yaml
/kind feature
Adds a new helm parameter, `node.selinux`, that mounts the relevant directories to allow the selinux-aware `mount` binary to perform selinux-specific optimizations. (This parameter can also be used in the future for any other selinux optimizations on the node).
This must be a parameter that is default-disabled, because `/sys/fs/selinux` will not exist unless SELinux is actually enabled on the nodes.
CI/Manually
```release-note
Add Helm parameter `node.selinux` to enable SELinux-specific mounts on the node DaemonSet
```
=> Selinux Mount Option

.golangci.yml, Makefile, go.mod, go.sum, pkg/cloud/metadata/mock_metadata.go, pkg/cloud/mock_cloud.go, pkg/cloud/mock_ec2.go, pkg/driver/controller_modify_volume.go, pkg/driver/mock_k8s_client.go, pkg/driver/mock_k8s_corev1.go, pkg/driver/mock_k8s_storagev1.go, pkg/driver/mock_k8s_storagev1_csinode.go, pkg/driver/node.go, pkg/driver/node_test.go, pkg/mounter/mock_mount.go, tests/sanity/fake_sanity_cloud.go, tests/sanity/fake_sanity_metadata_service.go, tests/sanity/fake_sanity_mounter.go, tests/sanity/sanity_test.go
/kind feature
This PR adds csi-sanity tests to the driver to be enable in CI afterwards.
Ran `make test-sanity`
and received the following results
```
Ran 76 of 92 Specs in 0.355 seconds
SUCCESS! -- 76 Passed | 0 Failed | 1 Pending | 15 Skipped
--- PASS: TestSanity (0.36s)
PASS
ok  	github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/sanity	1.429s
```
```release-note
Add csi-sanity tests
```
=> Add csi-sanity tests

hack/cloudbuild.sh
/kind cleanup
`hack/cloudbuild.sh` references invalid makefile target `all-push-for-release`, it should be `all-push` - this causes all of our commits to `master` to fail to build (and would break building images for release as well).
Manually
```release-note
NONE
```
=> Fix cloudbuild.sh target

docs/install.md
Cleans up the permissions section of the installation docs, and adds information about EKS Pod Identities.
N/A, docs change
```release-note
NONE
```
=> Refactor driver permissions docs and add Pod Identities

docs/example-iam-policy.json, docs/install.md, hack/e2e/kops/patch-cluster.yaml
This PR updates the example policy and associated documentation to be in sync with the upcoming managed policy revision.
In particular; it:
- Scopes down several permissions (notably changing `*` resources to specific types such as `volume/*` and `snapshot/*`)
- Adds necessary permission change for the upcoming `CreateVolume` IAM handling change
- Adds the `EnableFSRs` permission
- Reverts the previous change to use the `*` partition, instead choosing to document the partition name in `install.md` to be consistent with the managed policy
- Adds documentation around permissions for modifying tags (and cleans up the IAM section of `install.md`)
Manually/CI
```release-note
Update the example IAM policy to be in sync with the AWS managed policy
```
=> Update example policy and documentation

pkg/cloud/cloud.go
Fix for #2302 
```release-note
Fix backoff when waiting for volume creation
```
=> Fix wait for volume ready ~60s

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release EBS CSI Driver v1.39.0 & Helm Chart v2.39.0
```
❯ ./generate-release-pr v1.38.1 v1.39.0
2025-01-23 02:17:31 [INFO] - Confirming v1.38.1 < v1.39.0
2025-01-23 02:17:31 [INFO] - Updating README.md
2025-01-23 02:17:31 [INFO] - Updating Makefile
2025-01-23 02:17:31 [INFO] - Updating docs/install.md
2025-01-23 02:17:31 [INFO] - Updating helm chart and generates kustomize
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 16.6M  100 16.6M    0     0  40.2M      0 --:--:-- --:--:-- --:--:-- 40.1M
SUCCESS!
Before you submit the release PR, you must also:
1. Check that 'git diff' produces what you expected.
2. Update CHANGELOG.md
3. Update charts/aws-ebs-csi-driver/CHANGELOG.md
> GITHUB_TOKEN="FAKE_TOKEN" …
```
=> Release EBS CSI Driver v1.39.0 & Helm Chart v2.39.0

hack/e2e/run.sh
/kind cleanup
Today if you try to run `make e2e/single-az` on a cluster with nodes in multiple AZs, certain tests will mysteriously fail (because they require there only being nodes in one AZ). This is a painful gotcha for new contributors or those that try to run all of our e2e tests. 
For the short-term, this PR fast-fails `make e2e/single-az` if your cluster has schedulable nodes in multiple AZs, or in an AZ that is not referenced by $AWS_AVAILABILITY_ZONES. 
In the future, we should see if we can do something in the `[single-az]` e2e tests themselves to have them pass on a multi-az cluster. (Maybe pick an AZ at start of test, and add a node-selector for that AZ for all pods?) 
Have multi-az cluster. See failure. Delete or cordon nodes in other AZs. Tests pass. 
```
❯ make …
```
=> Fast-fail `make e2e/single-az` if cluster has nodes in multiple AZs

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/_node.tpl
/kind bug
Fix node.selinux configuration parameter because Pod spec.volumes.hostpath does not have a `readOnly`. That belongs in pod.spec.containers.volumeMounts.
When you install via helm this readOnly is dropped with a warning. However this breaks add-on. 
```
❯ helm upgrade --install aws-ebs-csi-driver \
--namespace kube-system --set "node.selinux=true" \
aws-ebs-csi-driver/aws-ebs-csi-driver
Release "aws-ebs-csi-driver" does not exist. Installing it now.
W0124 19:27:54.986662   29648 warnings.go:70] unknown field "spec.template.spec.volumes[4].hostPath.readOnly"
W0124 19:27:54.986683   29648 warnings.go:70] unknown field "spec.template.spec.volumes[5].hostPath.readOnly"
```
```
❯ helm template aws-ebs-csi-driver ./charts/aws-ebs-csi-driver > pre.yml
helm template aws-ebs-csi-driver …
```
=> Fix node.selinux configuration parameter & release Helm Chart v2.39.1

docs/modify-volume.md
/kind cleanup
- A small typo fix which is visible in the modify-volume doc(`-volume-ids` -> `--volume-ids`).
- Reduce customer cost the volume-modifier example pvc from `100Gi`  to `10Gi` to keep consistent with VAC example.
=> Fix: modify-volume doc typo

charts/aws-ebs-csi-driver/values.schema.json, charts/aws-ebs-csi-driver/values.yaml
/kind feature
This PR adds the values.schema.json file. Allowing us to make sure changes to helm chart parameters also appear in the eks add-on version of the driver as long as it makes sense to do so. 
```
❯ helm lint .
==> Linting .
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
```
```release-note
Add values.schema.json to validate changes in values.yaml make it to the add-on schema.
```
=> Add values.schema.json

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/node.yaml
/kind bug
Fix helm regression with a1CompatibilityDaemonSet.
Fixes #2315 
Setting a1 true should render helm template:
```
> helm template aws-ebs-csi-driver ./charts/aws-ebs-csi-driver --set a1CompatibilityDaemonSet=true
...
volumes:
- name: config-vol
configMap:
name: ebs-csi-driver-test
restartPolicy: Never
```
Setting a1 and fips both on should fail:
```
❯ helm template aws-ebs-csi-driver ./charts/aws-ebs-csi-driver --set a1CompatibilityDaemonSet=true --set fips=true --debug
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /home/andsirey/workplace/aws-ebs-csi-driver/charts/aws-ebs-csi-driver
Error: execution error at (aws-ebs-csi-driver/templates/node.yaml:16:4): FIPS mode not supported for A1 instance family compatibility image
helm.go:84: …
```
=> Fix helm regression with a1CompatibilityDaemonSet & release chart v2.39.2

docs/updating-dependencies.md
/cleanup
Fix command listed in `docs/updating-dependencies.md`
```
gh repo checkout pr 2320
unknown command "checkout" for "gh repo"
Usage:  gh repo <command> [flags]
Available commands:
archive
autolink
clone
create
delete
deploy-key
edit
fork
gitignore
license
list
rename
set-default
sync
unarchive
view
```
```
❯ gh pr checkout 2320
branch 'dependabot/go_modules/misc-dependencies-9f91678858' set up to track 'origin/dependabot/go_modules/misc-dependencies-9f91678858'.
Switched to a new branch 'dependabot/go_modules/misc-dependencies-9f91678858'
```
```release-note
NONE
```
=> Fix command in dep bump document

charts/aws-ebs-csi-driver/values.schema.json, charts/aws-ebs-csi-driver/values.yaml
Simple addition of a global dict to allow Helm sub-charting.
Fixes: #2319
```release-note
`global` has been added to the values schema, allowing aws-ebs-csi-driver to be used in a Helm sub chart
```
/kind bug
=> fix(helm): Add global as part of the values schema to allow sub-charting

hack/ebs-scale-test/README.md, hack/ebs-scale-test/helpers/scale-test/collect-and-export-metrics.sh, hack/ebs-scale-test/helpers/scale-test/expand-and-modify-test/expand-and-modify.sh, hack/ebs-scale-test/helpers/scale-test/expand-and-modify-test/expand-and-modify.yaml, hack/ebs-scale-test/helpers/scale-test/pre_test_validation.sh, hack/ebs-scale-test/helpers/scale-test/scale-sts-test/scale-sts.sh, hack/ebs-scale-test/scale-test
Add ebs-scale-test tool `TEST_TYPE='expand-and-modify'` to guard against regressions in how EBS CSI Driver handles concurrent volume modifications and/or expansions. 
Creates `$REPLICAS` block volumes. Patches PVC capacity and VACName at rate of 5 PVCs per second. Ensures PVCs are expanded and modified before deleting them. Exercises ControllerExpandVolume & ControllerModifyVolume. Set `MODIFY_ONLY` or `EXPAND_ONLY` to 'true' to test solely volume modification/expansion.
Note: As of Feb 2025, EBS CSI Driver can handle high amounts of concurrent modifications expansions at a rate of 5 patches per second. However due to our current [coalescing implementation](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/6e844a8fcc49fa95092418e094003ffe1bcec51b/docs/design.md …
=> Add expand-and-modify test type to ebs-scale-test

pkg/cloud/cloud.go
/kind bug
Currently, there is a logging issue in [cloud.EnableFastSnapshotRestores](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/4f4c7b7ec9617e5887a8cee4e1834c1e60fd9b59/pkg/cloud/cloud.go#L1421) which surfaces because the existing code is printing out raw pointers from the error structures rather than their underlying string values. With this cc, we explicitly extract the error code and error message from each failed FSR operation and consolidate them into a single, readable error message.
Exceed the regional FSR limit to induce the error, which can be reviewed by looking at the controller logs.
Without this patch:
```
E0210 16:42:42.944417       1 driver.go:108] "GRPC error" err="rpc error: code = Internal desc = Failed to create Fast Snapshot Restores for snapshot ID …
```
=> Fix raw pointer log in `EnableFastSnapshotRestores`

pkg/cloud/metadata/metadata.go, pkg/cloud/metadata/metadata_test.go
/kind bug
Today we attempt to call IMDS even if we know it is unavailable (via `AWS_EC2_METADATA_DISABLED=true` env var). 
/hold
Unit tests, CI
Will test on instance with and without EC2 metadata disabled shortly. 
```release-note
Skip IMDS call if AWS_EC2_METADATA_DISABLED=true
```
=> Skip IMDS call if AWS_EC2_METADATA_DISABLED=true

charts/aws-ebs-csi-driver/values.schema.json
/kind bug
Fixes schema validation in several places:
- Adds missing `additionalProperties: false` in several places
- Adds missing properties validation to `otelTracing`
- Removes properties validation in several places where the data is directly passed through into Kubernetes (We should not validate Kubernetes objects and instead just directly pass them through to k8s, as what is valid changes between k8s versions and is already validated by Kubernetes itself on installation)
Manually
```release-note
NONE
```
=> Fix incorrect properties validation in Helm schema

charts/aws-ebs-csi-driver/templates/_node-windows.tpl
/kind bug
Order of Helm `end` is incorrect in Windows, causing a null pointer deref when windows and otel tracing are enabled at the same time:
```
Error: template: aws-ebs-csi-driver/templates/node-windows.yaml:4:4: executing "aws-ebs-csi-driver/templates/node-windows.yaml" at <include "node-windows" (deepCopy $ | mustMerge $defaultArgs)>: error calling include: template: aws-ebs-csi-driver/templates/_node-windows.tpl:114:26: executing "node-windows" at <.Values.fips>: nil pointer evaluating interface {}.fips
```
Manually/CI
```release-note
Prevent nil pointer deref in Helm chart when `node.enableWindows` and `node.otelTracing` are both set
```
=> Prevent null deref when enableWindows and otelTracing enabled on node

cmd/main.go, pkg/cloud/handlers.go, pkg/metrics/constants.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
/kind feature
Currently the driver does not initialize metrics until there is some EBS activity, which can cause issues on customer dashboards/alerts due to missing data points. This PR modifies this behavior, and it allows for all registered metrics to be initialized to 0 on startup and published on the metrics endpoint even if no EBS activity has been recorded yet.
closes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2312
I tested these changes by doing the following:
1. Made cluster by running `make cluster/create`
2. Set controller replica count to 1
3. Built driver image with my changes by running `make cluster/image`
4. Installed image with changes on my cluster by running `make cluster/install`
5. Run `export ebs_csi_controller=ebs-csi-controller-<controller ID>`
6. …
=> Initialize metrics at 0 on startup

hack/verify-update.sh
/kind cleanup
At the beginning of each calendar year, `make verify` fails because the copyright year changes on mock code generated by `make update` (`pkg/mounter/mock_mount.go` for example). This is because mock files are generated by `./hack/update-mockgen.sh` without the header, and then `./hack/generate-license-header.sh` adds the headers back with the current year.
This means at the beginning of each year, contributors with open PR's are blocked by the verify job until someone commits a `make update` change to each release branch to update headers on generated files. It's a minor thing, but it's still wasted time and cpu cycles each January.
This PR adds a regex to `./hack/verify-update.sh` to ignore copyright year changes so the verify job will not fail if that is the only change …
=> cleanup: `make verify` should ignore copyright year

pkg/cloud/handlers.go
/kind feature
**Description**:
This PR enhances the `aws_ebs_csi_api_request_errors_total` metric by adding an `error_code` label to provide more granular visibility into the specific types of API errors encountered.
**Changes**:
- Added `code` as a new label to `aws_ebs_csi_api_request_errors_total` metric
- Error code is extracted from the AWS API error response
This additional dimension allows operators to:
- Better understand the nature of API failures
- Set up more specific alerting rules
- Troubleshoot issues more effectively by filtering on specific error types
- Verified metric exposition format
- Tested with common error scenarios
```release-note
Error `code` label is now supported EBS CSI API request error metrics
```
=> feat: Add error `code` label to EBS CSI API request error metrics

CHANGELOG.md, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/NOTES.txt, charts/aws-ebs-csi-driver/values.schema.json
This PR releases helm chart 2.40.2 cherry picks Add enabled flag to schema for sub-charting and replaces IAM policy change announcement  with AWS Snow Family device support for the EBS CSI Driver deprecation announcement 
```release-note
NONE
```
=> Release helm chart 2.40.2 

hack/generate-gpu-count-table.sh, hack/generate-instance-store-table.sh, pkg/cloud/volume_limits.go
/kind bug 
fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2301
Eddie manually attached 28 volumes to a p4d.24xlarge and the public docs have been updated to show it can have 28 ebs volumes attached  see https://docs.aws.amazon.com/ec2/latest/instancetypes/ac.html#ac_storage-ebs
```release-note
Fix p4d.24xlarge reporting wrong volume limit
```
=> Fix p4d.24xlarge reporting wrong volume limit

Makefile, hack/cloudbuild.sh
/kind cleanup
Changes `cloudbuild.sh` and `make sub-push-a1compat` to use the tags from the promoted versions of images for consistency.
Manually
```release-note
NONE
```
=> Update tags in cloudbuild.sh/Makefile to match promoted images

pkg/cloud/metadata/ec2.go, pkg/driver/node.go
/kind cleanup
Today we log number of attached ENIs upon driver start if IMDS is our metadata source. However, we accidentally log it even if driver is in controller mode, which is an confusing experience for customers (Why should ebs-csi-controller care about the ENI count of the node it is on?) 
This PR removes logging of ENIs when in controller mode and also adds logging of some of the information used to calculate CSI Node Allocatable, this way customers can have a better understanding of how this final node allocatable count was calculated.
Manually by spinning up a cluster and checking logs for nodes. 
Logs output looks like this: 
```
node.go:777] "getVolumesLimit:" instanceType="c5.large"
node.go:781] "getVolumesLimit:" maxAttachments=28
node.go:786] "getVolumesLimit:" …
```
=> Adding Logs On How We Calculate CSINode.allocatables in NodeGetInfo

charts/aws-ebs-csi-driver/values.schema.json
/kind bug
#2388 
Ran the failing command post change
```
helm template ebs ./aws-ebs-csi-driver --set controller.podDisruptionBudget.unhealthyPodEvictionPolicy="AlwaysAllow"
```
Yes, schema will now allow use of podDisruptionBudget
```release-note
```
=> Fix incorrect schema entry for controller.podDisruptionBudget.unhealthyPodEvictionPolicy value

pkg/driver/options.go
/kind cleanup
This PR switches the default value of deprecatedMetrics to false. Customers that still have the need to use the deprecated metrics can set it to true. 
N/A
```
Sets `deprecatedMetrics` to false by default
```
=> Switching deprecatedMetrics Default Value to False

Makefile, hack/e2e/test-images.sh
/kind feature
This PR adds a make file target which builds and pushes images to our `ECR` and then ensures that all images are pushed successfully. This will be used for a CI job after this is approved
Manually running the make file target
```release-note
NONE
```
=> Add make file target for testing images

.golangci.yml, pkg/cloud/cloud_test.go, pkg/driver/controller_test.go, pkg/driver/node_test.go, pkg/driver/request_coalescing_test.go
/kind cleanup
This PR enables the `usetesing` linter which ensures that wherever we are using test methods in our unit tests.
```release-note
NONE
```
=> Enable useTesting linter

Dockerfile, charts/aws-ebs-csi-driver/values.yaml, examples/kubernetes/block-volume/manifests/pod.yaml, examples/kubernetes/dynamic-provisioning/manifests/pod.yaml, examples/kubernetes/ephemeral-volume/manifests/pod.yaml, examples/kubernetes/modify-volume/manifests/pod-with-volume.yaml, examples/kubernetes/resizing/manifests/pod.yaml, examples/kubernetes/snapshot/manifests/app/pod.yaml, examples/kubernetes/snapshot/manifests/snapshot-import/app/pod.yaml, examples/kubernetes/snapshot/manifests/snapshot-restore/pod.yaml, examples/kubernetes/static-provisioning/manifests/pod.yaml, examples/kubernetes/storageclass/manifests/pod.yaml
Pulling images from Docker Hub is a poor experience, due to Docker Hub rate limiting. Additionally, the images we reference are extremely outdated. Replace all Docker Hub images with `public.ecr.aws/amazonlinux/amazonlinux`.
Manually
```release-note
NONE
```
=> Remove all examples/references to Docker Hub

cmd/main.go, pkg/metrics/metrics.go
/kind cleanup
This PR ensures that controller Prometheus metrics do not also populate on the node metrics.
Installed driver on cluster with three different configurations and confirmed that the metric outputs were as expected. The configurations were:
1. `--set="node.enableMetrics=true" --set="controller.enableMetrics=true"`
2. `--set="node.enableMetrics=true" --set="controller.enableMetrics=false"`
3. `--set="node.enableMetrics=false" --set="controller.enableMetrics=true"`
This what node metrics look like now: 
```# HELP aws_ebs_csi_nvme_collector_duration_seconds Histogram of NVMe collector scrape duration in seconds.
aws_ebs_csi_nvme_collector_duration_seconds_bucket{instance_id="i-0e2bb1585c491000c",le="0.001"} 1
aws_ebs_csi_nvme_collector_duration_seconds_bucket{instance_id="i-0e2bb15 …
```
=> Fix to only initialize controller metrics in controller

Makefile, hack/prow-e2e.sh
/kind feature
This PR adds the necessary changes in the driver repo to add a1compat and fips image e2e tests
Tested locally by running make file targets
```release-note
NONE
```
=> Add e2e tests for fips and a1compat images

hack/e2e/build-image.sh
/kind cleanup
In some cases, logging in to ECR doesn't work but isn't necessary, such as if the user has a login helper installed. Instead of failing out on this step, explicitly ignore failures as any issues will show up shortly after in the push anyways.
Manually
```release-note
NONE
```
=> Ignore ECR login failure in make cluster/image

CONTRIBUTING.md, Makefile, docs/makefile.md, hack/e2e/util.sh
/kind cleanup
While the existing `Makefile` works great for testing changes to the Go driver code, it requires building the image to install and cannot be easily modified to use the default (released) image. This means that to test a Helm-only change you have to waste your time building the image, and if you explicitly want to install the released image (such as to test something with the released version of the driver) you can't (easily) use `make cluster/install`.
This PR adds a new command, `make cluster/helm` that installs the default image. This command is primarily intended for (and documented as) a way to test Helm-only changes without needing to build the image. It uses the same function as the normal installation, so it will automatically respect the existing environment …
=> Add make cluster/helm

docs/metrics.md, pkg/cloud/handlers.go, pkg/metrics/constants.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
/kind cleanup
This PR adds more descriptive HELP texts to the driver controller metrics
Deployed driver with controller metrics enabled and checked that HELP texts on top were showing correctly
```
Add more descriptive Prometheus `HELP` texts to each metric from the controller.
```
=> Adding more metric specific HELP texts for controller metrics

hack/e2e/config.sh, hack/e2e/run.sh
/kind feature
Adds a junit report for the "local" E2E jobs (those in `tests/e2e/...`). Automatically outputs this report to the `ARTIFACTS` environment variable if present (this is how Prow tells the job where to put artifacts). Also removes an unused and incorrect `-report-dir` CLI flag that appears to be a previous attempt at this.
Click single-az / multi-az jobs down below after they finish running, see that they now show which tests passed/failed/were skipped
```release-note
NONE
```
=> Output junit report for `tests/e2e/...` E2E jobs

Makefile, hack/e2e/build-image.sh, hack/e2e/config.sh, hack/prow-e2e.sh
/kind cleanup
This CR removes the a1 compat CI job and fixes the fips CI jobs
Ran CI test and confirmed with this fix errors subside.
Windows 
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/2417/pull-aws-ebs-csi-driver-test-e2e-external-eks-windows-fips/1904537879137226752
Linux
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/2417/pull-aws-ebs-csi-driver-external-test-fips/1904537816684040192
```release-note
NONE
```
=> Fix a1compat makefile target and fix fips CI jobs

pkg/metrics/nvme_unsupported.go
/kind cleanup
This PR changes our stub NVMECollector implementations from Windows only to non-linux, so that ebs-csi-controller is buildable and unit-testable on MacOS. 
See #1556 for more context on why being able to build and run tests on MacOS / darwin is helpful.
Today: 
```
❯ make test
go test -v -race ./cmd/... ./pkg/... ./tests/sanity/...
pkg/metrics/metrics.go:78:2: undefined: registerNVMECollector
FAIL	github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd [build failed]
FAIL	github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/hooks [build failed]
...
```
After PR:
```
❯ make test
go test -v -race ./cmd/... ./pkg/... ./tests/sanity/...
...
PASS
ok  	github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/util/template	(cached)
?   	github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/sanity …
```
=> Change stub NVMECollector from windows to non-linux platforms

charts/aws-ebs-csi-driver/templates/metrics.yaml
/kind feature
This PR sets interenalTrafficPolicy to true on the node pods metrics service
Confirmed change does not break current metrics flow.
https://gist.github.com/ElijahQuinones/62d7d8f5d37d237ac86cb10bc38d77ab
```release-note
NONE
```
=> Set internalTrafficPolicy to local on node metric service

Makefile, pkg/metrics/nvme.go, pkg/metrics/nvme_test.go, pkg/mounter/mount_linux.go, pkg/mounter/mount_linux_test.go, pkg/mounter/mount_unsupported.go, pkg/mounter/mount_windows.go, pkg/mounter/mount_windows_proxyV1.go, pkg/mounter/mount_windows_proxyV2.go, pkg/util/util_test.go, tests/sanity/sanity_test.go
/kind cleanup
`go fix` is a command built into go that automatically rewrites code using deprecated golang APIs to new APIs ([reference 1](https://pkg.go.dev/cmd/fix), [reference 2](https://go.dev/blog/introducing-gofix). We have a few instances of this in our codebase, notably using `+build` where `go:build` is standard.
This PR adds `go fix` to `make update`, so that our codebase will be automatically updated to fixup any deprecated APIs that `go fix` handles when we bump the go version.
```
$ make update         
go fix ./...
gofmt -s -w .
./hack/update-kustomize.sh
./hack/update-mockgen.sh
go mod tidy
./bin/shfmt -w -i 2 -d ./hack/
./hack/generate-license-header.sh
Adding license header...
All updates succeeded!
```
```release-note
NONE
```
=> Add `go fix` to `make update`

pkg/cloud/metadata/ec2.go, pkg/cloud/metadata/interface.go, pkg/cloud/metadata/metadata.go, pkg/cloud/metadata/metadata_test.go, pkg/cloud/metadata/mock_metadata.go, pkg/driver/node.go, pkg/driver/node_test.go, tests/sanity/fake_sanity_metadata_service.go
/kind feature
When Kubernetes periodically calls NodeGetInfo, the driver should return updated information about the maximum number of attachable volumes. This commit modifies the driver to refresh dynamic metadata (ENI count) when calculating volume limits, rather than using cached values from driver initialization.
Attaching one additional ENI after driver startup and observing driver logs / CSINode object.
- Node plugin logs:
```
I0409 15:36:55.336607       1 node.go:574] "NodeGetInfo: called" args=""
I0409 15:36:55.338301       1 metadata.go:93] "Updated metadata" numAttachedENIs=1 numBlockDeviceMappings=0
I0409 15:36:55.338335       1 node.go:781] "getVolumesLimit:" instanceType="c5.large"
I0409 15:36:55.338344       1 node.go:785] "getVolumesLimit:" availableAttachments=28
I0409 …
```
=> Refresh dynamic instance metadata for NodeGetInfo calls

docs/parameters.md, pkg/cloud/cloud.go
/kind bug
EC2 updated io2 max IOPS to size ratio from 500 to 1000: 
```
❯ aws ec2 create-volume --availability-zone us-west-2a --size 6 --iops 10000 --volume-type io2
An error occurred (InvalidParameterCombination) when calling the CreateVolume operation: io2 volumes configured with greater than 64 TiB or 256K IOPS or 1000:1 IOPS:GB ratio are not supported.
❯ aws ec2 create-volume --availability-zone us-west-2a --size 6 --iops 6000 --volume-type io2
{
"Iops": 6000,
"Tags": [],
"VolumeType": "io2",
"MultiAttachEnabled": false,
"VolumeId": "vol-0a8c747261f4e3a15",
"Size": 6,
"SnapshotId": "",
"AvailabilityZone": "us-west-2a",
"State": "creating",
"CreateTime": "2025-05-14T14:55:30+00:00",
"Encrypted": true
}
```
We should ensure driver reflects true value. In the longterm, we should avoid …
=> Update io2MaxIOPSPerGb from 500 to 1000

Makefile, hack/tools/check-security.sh, hack/tools/install.sh
/kind cleanup
Add security Makefile target that currently runs govulncheck against only our ebs-csi-driver module. That way we can move our govulncheck GH action to Prow (so we can override it). 
Spotted a vuln on release-1.39 branch!
```
❯ git checkout release-1.39
Your branch is ahead of 'upstream/release-1.39' by 1 commit.
❯ make clean && make security
rm -rf bin/
/home/linuxbrew/.linuxbrew/bin/python3
./hack/tools/check-security.sh
=== Symbol Results ===
Vulnerability #1: GO-2025-3547
Kubernetes kube-apiserver Vulnerable to Race Condition in k8s.io/kubernetes
More info: https://pkg.go.dev/vuln/GO-2025-3547
Module: k8s.io/kubernetes
Found in: k8s.io/kubernetes@v1.32.2
Fixed in: N/A
Example traces found:
#1: pkg/driver/node.go:43:2: driver.init calls volume.init, which eventually calls …
```
=> Add security Makefile target

.github/dependabot.yaml
/kind cleanup
We split out a separate `go.mod` in #2471, but now Dependabot PRs are failing because it only tries to update the main `go.mod`. This PR fixes that issue.
It wasn't
```release-note
NONE
```
=> Update tests/e2e go.mod in Dependabot

go.mod, go.sum, tests/e2e/go.mod, tests/e2e/go.sum
/kind cleanup
Currently, our go.mod replaces client-go, which causes it to incorrectly "upgrade" to v1.5.2. This PR undoes that breakage and pins external-resizer to a non-broken version.
This brokenness comes to us from `volume-modifier-for-k8s`, and will be fixed there in https://github.com/awslabs/volume-modifier-for-k8s/pull/52
Standard E2E Run + CI
```release-note
NONE
```
=> Remove broken client-go replace

.github/dependabot.yaml
/kind cleanup
No need for dependabot PRs to have release note
Hasn't
```release-note
NONE
```
=> Have dependabot add release-note-none label

Makefile
/kind cleanup
Adds the new `tests/e2e` go.mod to `make update/gomod` action. The single-az/multi-az tests technically cover this, but this will (1) ensure `make update` actually does all needed updates and (2) cause a failure in `make verify` thus much faster feedback on this issue.
```bash
$ make update/gomod
go mod tidy
go mod tidy -C tests/e2e/
```
```release-note
NONE
```
=> Include tests/e2e go.mod in make update/gomod

hack/ebs-scale-test/README.md, hack/ebs-scale-test/helpers/cluster-setup/manage-cluster.sh, hack/ebs-scale-test/helpers/cluster-setup/scale-driver-values.yaml, hack/ebs-scale-test/helpers/scale-test/collect-and-export-metrics.sh, hack/ebs-scale-test/helpers/scale-test/snapshot-volume-scale-test/snapshot-volume-scale.sh, hack/ebs-scale-test/helpers/scale-test/snapshot-volume-scale-test/snapshot-volume-scale.yaml, hack/ebs-scale-test/scale-test
This PR adds a scale test for the CreateSnapshot / restore volume from snapshot code paths.
Manually:
```
export TEST_TYPE="snapshot-volume-scale"
export REPLICAS=1000
./scale-test run
```
https://gist.github.com/torredil/f1cd9806d013e56115f1ea93f018384d
```release-note
NONE
```
=> Add snapshot-volume-scale to scalability test suite

charts/aws-ebs-csi-driver/templates/clusterrole-csi-node.yaml, deploy/kubernetes/base/clusterrole-csi-node.yaml, pkg/driver/node.go, pkg/driver/node_test.go
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2447
/kind bug
The current implementation uses a 1 s sleep to look for the `ebs.csi.aws.com/agent‑not‑ready` taint.  If `eks:node‑manager` (or any other controller) applies the taint *after* that initial probe, the driver never retries and the node stays unschedulable until the pod is restarted.
This patch replaces that logic with a short‑lived, event‑driven Node informer filtered to the current node as a better mechanism for reliably removing the startup taint.
Note: Some minor refactoring was done in the existing unit tests because we no longer need to mock the call to retrieve the node object in `removeNotReadyTaint` -  now, the node object gets passed in directly into `removeNotReadyTaint` from the informer's event …
=> Reliably remove driver startup taint

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_test.go
/kind cleanup
This PR updates the Attach code path to return the `ResourceExhausted` gRPC error code in `ControllerPublishVolume` when the attachment limit is exceeded for the instance. In newer versions of Kubernetes, CSI drivers can opt in to a feature that allows for updating the `CSINode.Allocatables.Count` value when this gRPC error code is reported in the VolumeAttachment object.
```
make verify && make test
```
Manually, by deploying the driver with `volumeAttachLimit: 200` and scaling up StatefulSet to induce this failure mode. See driver log:
```
E0521 18:02:25.853256       1 driver.go:108] "GRPC error" err="rpc error: code = ResourceExhausted desc = Attachment limit exceeded for volume \"vol-0d8d2bab6fc5dd31b\" on node \"i-00f897f741bb9326a\": attachment limit exceeded: …
```
=> Return `ResourceExhausted` gRPC error code in `ControllerPublishVolume` when `AttachmentLimitExceeded`

charts/aws-ebs-csi-driver/values.schema.json
/kind bug
We need this PR to improve our `extraVolumeTags` validation to follow EC2 tagging convention as described [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions)
This PR addresses #2491 
`cd aws-ebs-csi-driver/charts/aws-ebs-csi-driver`
`helm template . -f test-file.yaml --debug | grep "extra-tag"`
created 3 files
1. valid-test-values.yaml
```
controller:
extraVolumeTags:
normal-key: "normal-value"
with.dot: "value.with.dot"
with_underscore: "value_with_underscore"
with-hyphen: "value-with-hyphen"
withNumber123: "value123"
UPPERCASE: "UPPERCASE_VALUE"
"key:with:colon": "value:with:colon"
"key@with@at": "value@with@at"
"key/with/slash": "value/with/slash"
"unicode_key_测试": "unicode_value_测试"
awstest: "valid"
aws-test: "valid"
aws.test: "valid" …
```
=> improving extraVolumeTags validation to follow EC2 tagging convention

docs/metrics.md
This is the actual name of the metric, as the namespace  `aws_ebs_csi_` is hardcoded in the code. Matches the other examples here too.
The example names for the node metrics were missing the prefix, making it slightly difficult
to validate that metrics collection is enabled.
I verified that these metrics *are* available in my installation.
```release-note
NONE
```
=> Use correct name for nvme_collector_duration_seconds

.golangci.yml, hack/tools/install.sh, pkg/cloud/cloud.go, pkg/driver/controller.go, pkg/mounter/mount_linux.go
/kind cleanup
Migrates our config to golangci-lint v2's format. This was done by using the built-in migration tool, and then fixing some resulting issues (e.g. missing comments) in the generated file.
Also fixes several instances of incorrect errors found by a new linter, and adds a `nolint` for a particularly egregious suggestion by a new linter.
`make verfy/golangci-lint`
```release-note
NONE
```
=> Migrate to golangci-lint v2

OWNERS
Adding mdzraf to OWNERS file in order to allow for review/approval of PRs as well as conducting release related tasks. 
```release-note
NONE
```
=> Add mdzraf to OWNERS file

pkg/cloud/cloud.go
/kind cleanup
This PR removes the TODO comment to check if the device is attached before releasing as that is already being done in this function, here we defer the release: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/af089444c5b7e17907cef26415febc511b7699aa/pkg/cloud/cloud.go#L970 
Right before the function returns we check that the volume is in an detached state and if it isn't we log it:  https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/af089444c5b7e17907cef26415febc511b7699aa/pkg/cloud/cloud.go#L994-L1001
```release-note
NONE
```
=> Remove completed TODO comment

hack/ebs-scale-test/README.md, hack/ebs-scale-test/helpers/cluster-setup/manage-cluster.sh, hack/ebs-scale-test/helpers/cluster-setup/nodes-karpenter.yaml, hack/ebs-scale-test/helpers/cluster-setup/scale-cluster-config.yaml, hack/ebs-scale-test/helpers/scale-test/snapshot-volume-scale-test/snapshot-volume-scale.sh, hack/ebs-scale-test/scale-test
Adds cluster type which installs [Karpenter](https://github.com/aws/karpenter-provider-aws) during cluster setup. 
Karpenter will provision and delete worker nodes during scalability test run as needed.
Bonus: Creating a karpenter cluster when running NON `scale-sts` tests is super frugal because only 2 m5large nodes are up!
Running 
```
export CLUSTER_TYPE="karpenter"
export TEST_TYPE="scale-sts"
export REPLICAS="1000"
./scale-test setup
./scale-test run
./scale-test cleanup
```
But for each test-type 
```release-note
Add Karpenter ebs-scale-test cluster type
```
=> Add Karpenter ebs-scale-test cluster type

.github/dependabot.yaml
/kind cleanup
Fixes a mistake in #2557 - by default dependabot has _no_ grouping, so we are getting 1 PR for each dependency upgrade right now.
:shrug: the dependabot experience
```release-note
NONE
```
=> Group Dependabot PRs

charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml, docs/example-iam-policy.json, go.mod, go.sum, hack/e2e/kops/patch-cluster.yaml, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/ec2_interface.go, pkg/cloud/interface.go, pkg/cloud/mock_cloud.go, pkg/cloud/mock_ec2.go, pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/util/util.go, pkg/util/util_test.go, tests/e2e/go.mod, tests/e2e/go.sum, tests/e2e/requires_aws_api.go, tests/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go, tests/sanity/fake_sanity_cloud.go
/kind feature
Allows users to delay ControllerPublishVolume success (and therefore start of workload) until a volume restored from snapshot is fully initialized. 
This is achieved by polling `EC2 DescribeVolumeStatus` after volume attached. 
If feature is popular, In future we may add:
- ability to override blocking via VAC parameter
- Parallel polling for volume attachment and for volume initialized
- Our new E2E test (initialization rate + blockAttachUntilInitialized)
- Manually testing blockAttachUntilInitialized on volume restored from snapshot WITHOUT initializationRate
- Manually testing blockAttachUntilInitialized on non-restored volume
```release-note
Added StorageClass parameter 'blockAttachUntilInitialized' for users who want to delay ControllerPublishVolume success (and …
```
=> Add blockAttachUntilInitialized SC parameter

cloudbuild.yaml
/kind cleanup
Bumps the cloudbuild image, because our current jobs are timing out building the driver images for release.
CI
```release-note
NONE
```
=> Bump cloudbuild to machine type with 32GB of RAM

cmd/main.go, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, tests/e2e/dynamic_provisioning.go, tests/e2e/pre_provsioning.go
/kind bug
Fixes #2619
CI + Manually on HP cluster:
Test on HP cluster:
```
$ make e2e/external
...
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1755197721 - will randomize all specs
Will run 263 of 7034 specs
Running in parallel across 25 processes
...
###
#
###
#
```
Relevant log snippet from HP cluster:
```
I0814 18:55:22.676240       1 cloud.go:1964] "Retrieved AWS account ID for HyperPod operations" accountID="REDACTED (was correct account ID)"
```
```release-note
Prevent liveness probe failure (and thus CrashLoopBackoff) without proper logging by moving sts:GetCallerIdentity call from blocking startup to just in time
```
=> Call sts:GetCallerIdentity Just in Time instead of blocking on startup

.github/workflows/helm-chart-release.yaml
/kind cleanup
Fixes Helm release action so we can correctly release patch releases.
N/A
```release-note
NONE
```
=> Run Helm release action on release branches, not master

pkg/cloud/cloud.go, pkg/driver/constants.go, pkg/driver/driver.go, pkg/driver/identity.go, pkg/driver/node.go, pkg/driver/node_test.go, pkg/util/util.go, tests/e2e/driver/ebs_csi_driver.go, tests/e2e/testsuites/modify_volume_tester.go, tests/e2e/testsuites/testsuites.go
/kind cleanup
Remove a couple of hardcodings. Helpful ahead of #2591. 
```
❯ rg "ebs.csi.aws.com" --glob '!hack/' --glob '!charts/' --glob '!examples/' --glob '!*.yaml' --glob '!*.md' --glob '!*.json' | rg -v "//"
pkg/util/util.go:	DriverName = "ebs.csi.aws.com"
```
```release-note
NONE
```
=> Ensure codebase uses DriverName constant instead of ebs.csi.aws.com

Makefile, hack/verify-update.sh
golangci-lint has the ability to autofix many linter errors by adding the `--fix` flag. By running a version of this in make update we can reduce developer toil (and CI failures). 
Enjoy an easier life soon:
```
❯ git diff cmd
<WRONG IMPORT ORDER>
❯ make verify
go vet $(go list ./...)
./bin/golangci-lint run --timeout=10m --verbose
INFO golangci-lint has version 2.3.1 built with go1.24.5 from 5256574b on 2025-08-02T21:24:45Z
...
INFO [runner] linters took 977.720427ms with stages: goanalysis_metalinter: 968.993476ms
cmd/main.go:30:1: File is not properly formatted (gci)
"github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/metrics"
^
1 issues:
* gci: 1
INFO File cache stats: 1 entries of total size 6.5KiB
INFO Memory: 19 samples, avg is 153.7MB, max is 753.1MB
INFO Execution took …
```
=> Autofix some golangci-lint errors in make update

.golangci.yml, pkg/cloud/cloud.go, pkg/metrics/nvme.go, pkg/mounter/mount_linux_test.go, tests/sanity/sanity_test.go
/hold
/kind cleanup
This PR enables the `std-error-handling` checker in the Gosec linter. It also fixes issues caught by the checker:
```
pkg/cloud/cloud.go:358:12: Error return value of `os.Setenv` is not checked (errcheck)
os.Setenv("AWS_EXECUTION_ENV", "aws-ebs-csi-driver-"+driverVersion+"-"+userAgentExtra)
^
pkg/cloud/cloud.go:360:12: Error return value of `os.Setenv` is not checked (errcheck)
os.Setenv("AWS_EXECUTION_ENV", "aws-ebs-csi-driver-"+driverVersion)
^
pkg/metrics/nvme.go:290:15: Error return value of `f.Close` is not checked (errcheck)
defer f.Close()
^
pkg/mounter/mount_linux_test.go:92:20: Error return value of `os.RemoveAll` is not checked (errcheck)
defer os.RemoveAll(dir)
^
pkg/mounter/mount_linux_test.go:120:20: Error return value of `os.RemoveAll` is not checked …
```
=> Enable std-error-handling linter

hack/e2e/create-cluster.sh
/kind cleanup
Currently, running `make cluster/create` with `WINDOWS=true` and the default `CLUSTER_TYPE=kops` creates a cluster with no Windows nodes, which is confusing for developers expecting Windows support.
```
make cluster/create WINDOWS=true                                                                                                                                                                             
Error: Windows clusters are not supported with kops. Please set CLUSTER_TYPE=eksctl when WINDOWS=true
make: *** [cluster/create] Error 1
```
```release-note
NONE
```
=> Makefile: Add validation to prevent Windows clusters with kOps

pkg/driver/controller_modify_volume.go
/kind bug
This PR makes it so that when there is a modifyVolume request and the request to modify tags which happens before the `ResizeOrModifyDisk`, succeeds, and then there is a failure when `ResizeOrModifyDisk` is called due to an InvalidParameter, the driver does not return codes.InvalidArgument which is considered an infeasible error by the resizer. Because there was _some_ modification done to the volume, an infeasible error is not to be returned as this would signal that no changes were done at all.
Running `make test` for unit tests.
```release-note
NONE
```
=> Not Returning Infeasible If Tags Were Modified

charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/controller.yaml
/kind feature
#closes #2653
Verified that all sidecar containers now have matching containerPort declarations, conditionally added only when enableMetrics is true.
```release-note
Added containerPort declarations for containers in Helm chart to enable proper metrics discovery by monitoring systems
```
=> Add containerPort spec for metrics endpoint

charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml
/kind feature
Set the termination message policy to `FallbackToLogsOnError` for all our containers, which will cause Kubernetes to use our logs (hopefully containing a relevant error) for the termination message rather than nothing.
See the last paragraph of https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/#customizing-the-termination-message for details.
Example from `kubectl describe`:
```
$ kubectl -n kube-system describe pod ebs-csi-controller-55c6c84c5f-c48nn
Name:                 ebs-csi-controller-55c6c84c5f-c48nn
Namespace:            kube-system
...
Containers:
ebs-plugin:
Container ID:    containerd://ac1258afa97e3c8f3cf984a4f4787206786dbb62ee0b0c7ebc3f18fab4580a3c
Image:           public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.49.0
... …
```
=> Add FallbackToLogsOnError termination message policy to all containers
