.gitignore, pkg/cloud/devicemanager/manager.go
Fixes #3 
Using `%v` as format style since device is a struct instead of string
=> fix make test by fixing glog format

hack/update-gofmt, hack/verify-all, hack/verify-gofmt, hack/verify-govet
4 scripts are added:
* verify-govet
* verify-gofmt
* update-gofmt
* verify-all
=> Add scripts for running go vet and go fmt

pkg/util/util_test.go
Covering the parse logic for endpoint for different cases.
=> Add unit test for util package

tests/e2e/setup_test.go
=> Remove hard-coded region in e2e test

Dockerfile
mount command is needed by the driver to mount the EBS volume
=> Fix dockerfile by installing mount command from util-linux package

README.md
=> Update README to be ready for alpha release

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement-request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/support-request.md
=> Update issue templates

CHANGELOG-0.1.md, docs/README.md
=> Add CHANGELOG for v0.1.0 alpha release

CHANGELOG-0.1.md
=> Add CHANGELOG for v0.1.0

pkg/driver/driver.go
/kind bug
/assign leakingtapan
Fixes #123.
=> Remove unsupported MULTI_NODE_READER_ONLY volume capability

docs/README.md
/bug
Fix README to reflect latest changes on master branch
=> Fix README

Makefile, deploy/kubernetes/latest/attacher.yaml, deploy/kubernetes/latest/node.yaml, deploy/kubernetes/latest/provisioner.yaml, docs/README.md
Fixes: #144 
Also differentiates container image push between latest and release
=> Bump driver version to 0.2.0

pkg/cloud/cloud.go, tests/integration/integration_test.go, tests/integration/setup_test.go
Fix issues detect during enabling integration test
Ref #153
=> Fix integration Test

hack/run-e2e-test
/bug
Update e2e test script to create/delete secret
=> Update e2e test script to create ssh key

Makefile
=> Strip symbol for production build

pkg/cloud/cloud_test.go, pkg/cloud/devicemanager/allocator_test.go, pkg/cloud/metadata_test.go, pkg/driver/controller_test.go, pkg/driver/internal/inflight_test.go
=> Update all unit tests to use go subtest

pkg/cloud/fakes.go, pkg/cloud/metadata.go, pkg/driver/controller_test.go, pkg/driver/fakes.go, pkg/driver/node_test.go, tests/sanity/sanity_test.go
=> Fake clean

pkg/driver/controller.go
This bug could happen when `req.GetCapacityRange()` is nil but it is still used later for `req.GetCapacityRange().GetLimitBytes()`
=> fix a bug when capacity range is nil

CHANGELOG-0.x.md
/release
Update CHANGELOG for 0.3 release
=> Update CHANGELOG for 0.3 release

CHANGELOG-0.x.md, deploy/kubernetes/controller.yaml, deploy/kubernetes/node.yaml, docs/README.md
* Add sha512 for release zip and tar.gz 
* Update 0.3 README link in CHANGELOG
* Flip container image link back to latest for dev
* Update driver matrixs in README
=> Post 0.3 documentation changes

docs/README.md
=> Update README for driver permission

pkg/cloud/devicemanager/manager.go, pkg/driver/controller.go, pkg/driver/identity.go, pkg/driver/node.go
* Update `klog.Infof` to be `klog.V(*).Inforf`
* Update log message where we print the whole object
* Update prob log verbosity to be V(6) to reduce log messages
=> Update log verbosity and log message

Makefile, hack/run-integration-test
=> Refactor integration test script

tests/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
/bug
Fix a test issue when Pod start times out and PVC is stuck in `terminating` state since Pods are not deleted.
/cc @dkoshkin
=> Fix e2e test when pod start times out

deploy/kubernetes/manifest.yaml
Ref: #177 
/cc @dkoshkin @bertinatto
=> Rename driver sa, clusterrole and clusterrole binding to be driver specific

deploy/kubernetes/manifest.yaml
=> Fix liveness probe memory leak

pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/controller_test.go, tests/e2e/driver/ebs_csi_driver.go, tests/e2e/dynamic_provisioning.go
=> Make storageclass paramter case in-sensitive

deploy/kubernetes/manifest.yaml, hack/run-e2e-test
=> Update e2e test to run against 1.14.0

examples/kubernetes/snapshot/specs/snapshot-import/volume-snapshot-content.yaml, examples/kubernetes/snapshot/specs/snapshot-import/volume-snapshot.yaml, pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/cloud/mocks/mock_ec2.go, pkg/cloud/mocks/mock_ec2metadata.go, pkg/driver/controller.go, pkg/driver/controller_test.go, pkg/driver/mocks/mock_cloud.go, pkg/driver/mocks/mock_metadata_service.go, pkg/driver/mocks/mock_mounter.go, tests/sanity/fake_cloud_provider.go
=> Fix ListSnapshot bug to use GetSnapshotById

aws-ebs-csi-driver/templates/manifest.yaml, aws-ebs-csi-driver/values.yaml
=> Adding volume resizing support in helm chart

aws-ebs-csi-driver/templates/manifest.yaml, aws-ebs-csi-driver/values.yaml, deploy/kubernetes/manifest.yaml, hack/run-e2e-test, hack/utils/helm.sh, hack/utils/tiller-rbac.yaml
Remove snapshot from default manifest and make it configurable from helm since snapshot is still alpha feature
Fixes: #314
=> Remove snapshot from default manifest and make it configurable from helm

aws-ebs-csi-driver/templates/manifest.yaml, deploy/kubernetes/manifest.yaml
=> Add node selector for linux node only

docs/README.md, examples/kubernetes/resizing/README.md, examples/kubernetes/resizing/spec/example.yaml
=> Add documentations for volume resizing

docs/README.md
=> Remove DISCLAIM

CHANGELOG-0.x.md, docs/README.md
Update CHANGELOG for 0.4 release
/cc @wongma7
=> Update CHANGELOG for 0.4 release

hack/release
This change extend the release script to generate noteable changes using Github API:
Fixes: #120
=> Implement auto generating change log

go.mod, go.sum
=> Update tester version

docs/README.md
Update README for installation step using kustomize
=> Update README for installation step

docs/design.md
=> Add design doc

docs/README.md, go.sum, pkg/cloud/cloud.go, pkg/driver/controller_test.go, tests/e2e/driver/ebs_csi_driver.go
=> Add standard volume type

aws-ebs-csi-driver/templates/manifest.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/rbac.yaml, deploy/kubernetes/overlays/alpha/controller_add_resizer.yaml, deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
Fixes: #255 
* Updated the manifest to use Deployment for controller service
=> Enable leader election

Makefile
=> Update version string

hack/run-e2e-test
Fix skip pattern to ignore disruptive tests
=> Fix skip pattern to ignore disruptive tests

hack/run-e2e-test
Enable volume expansion e2e test for CSI migration
/cc @davidz627 @ddebroy @wongma7
=> Enable volume expansion e2e test for CSI migration

docs/README.md, examples/kubernetes/storageclass/specs/example.yaml
Update example and README for allowed topologies
/cc @bertinatto
=> Update example and README for allowed topologies

pkg/driver/node.go, pkg/driver/node_test.go
Fixes #352
NodeStageVolume should use the mount flags passed in. I got hit by this while trying to run the upstream tests against the driver:
```
External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (default fs)] provisioning should provision storage with mount options"
```
Manual, also added a unit test.
=> Handle mount flags in NodeStageVolume

CHANGELOG-0.x.md, Makefile, hack/release
Add release note for v0.5.0
Update release script
=> Add release note for v0.5.0

CHANGELOG-0.x.md, aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/values.yaml, docs/design.md
Bump version for v0.5.0 release
=> Bump version for v0.5.0 release

CHANGELOG-0.x.md, Makefile, docs/README.md
=> Post release doc update

tester/multi-az-config.yaml, tester/single-az-config.yaml
=> Fix e2e test

docs/README.md
Fixed typo error optinal -> optional
=> Fixed typo in README

.travis.yml, Dockerfile, docs/README.md
=> Bump Go to 1.14.1

pkg/driver/mount_test.go
=>  Add mount unittest

hack/run-e2e-test
=> Fix migration test

docs/README.md
Update the features state as currently they wrong state that given features are still alpha.
=> Update features state

.golangci.yml, docs/README.md, go.mod, go.sum, tester/multi-az-config.yaml, tester/single-az-config.yaml
Update test cluster version. #487
=> Update test cluster version

CHANGELOG-0.x.md, Makefile, aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
=> update changelog and version

CHANGELOG-0.x.md, aws-ebs-csi-driver/values.yaml, docs/README.md
Post release update
Fixes: #547
=> Post release update

tester/multi-az-config.yaml, tester/single-az-config.yaml, tests/e2e/dynamic_provisioning.go
**Is this a bug fix or adding new feature?** mitigation
**What is this PR about? / Why do we need it?** certain tests are super flaky https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/545. I haven't had much chance to debug so I'm just going to remove redundant tests for now and figure it out later.
=> Skip sc1 and st1 tests, only test xfs

CHANGELOG-0.x.md, aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, docs/README.md
=> Post-release v0.7.0

docs/README.md
See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/516
=> Fixing Helm install command

Makefile, aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
Bug fix. 
Our v0.7.0 tag still uses the v0.6.0 image. This release is to fix it.
N/A.
Closes #617
=> Release v0.7.1

CHANGELOG-0.x.md, Makefile, aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
Update the docs for the 0.7.1 release.
=> Post-release v0.7.1

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/arm64/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
=> release v0.9.0

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, cloudbuild.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
Release driver v0.9.0 + increase cloudbuild timeout
=> release 0.9.0

docs/README.md
This is a very simple documentation only change where we update the installation instructions to use the latest version.
=> Updated installation to use latest 0.9 release

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
Patch release 0.9 to use gcr image in stable kustomization
=> patch stable release to use gcr image

deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
=> correct kustomization gcr image repo

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/statefulset.yaml, charts/aws-ebs-csi-driver/values.yaml
All the other images can be modified via changing the variable in values.yaml, except for the snapshotController. This PR fixes that.
=> Remove hardcoded snapshot controller image references

charts/aws-ebs-csi-driver/Chart.yaml
We have a couple of chart PRs merged. Need to release a new version.
=> Update chart version

OWNERS
Add Xiang as reviewer, to help with code review
=> Add self as reviewer

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md, pkg/driver/constants.go, pkg/driver/controller.go, pkg/driver/node.go, pkg/driver/node_linux.go, pkg/driver/node_test.go
Bi-weekly csi driver release 
Bump minor version to v0.10.1 to include latest driver updates
=> Release 0.10.1

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
Cherry pick release note to master
=> release v0.10.1

docs/README.md
update installation command to use latest stable version
=> update installation command to use latest stable version

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
=> release v1.0.0

OWNERS
adding @vdhanan as an owner/maintainer of this repo
=> add self as owner

charts/aws-ebs-csi-driver/Chart.yaml
PR #874 was merged without helm chart version increase
=> bump helm chart version

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/clusterrolebinding-csi-node.yaml, charts/aws-ebs-csi-driver/templates/controller.yaml, deploy/kubernetes/base/clusterrolebinding-csi-node.yaml, deploy/kubernetes/base/controller.yaml
cherry picking the commit from master
=> fix naming mistake in clusterrolebinding, add env var to controller yaml

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
**Is this a bug fix or adding new feature?** fix https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/854
=> Reduce default log level to 2

.github/workflows/helm-chart-release.yaml
=> Bump chart-releaser-action to v1.2.1

CHANGELOG-0.x.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
=> release v1.1.0

CHANGELOG-0.x.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
=> merge v1.1.0 release commits back to master

CHANGELOG-0.x.md
=> Nit: Fix typo in the CHANGELOG

CHANGELOG-0.x.md, Dockerfile, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
release v1.1.2 to address security vulnerability
=> Release 1.1

CHANGELOG-0.x.md, Dockerfile, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
**What is this PR about? / Why do we need it?** bug in our internal build means the ECR tag is pointing to the debian image, fix.
N/A
=> Release v1.1.3

docs/README.md
readme update
add ecr images to readme
checked which images exist in ecr repo
=> add ecr images to readme

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
Merge Release commits back to master
=> Release v1.2.0

deploy/kubernetes/base/kustomization.yaml
Should close this:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/821
=> Include ClusterRole and ClusterRoleBinding for csi-node

CHANGELOG-0.x.md, Makefile, docs/README.md
patch
fixes mount idempotency bug
=> release v1.1.4

CHANGELOG-0.x.md, Makefile, docs/README.md
patch
fixes mount idempotency bug
=> release 1.2.1

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
=> 1.1.4 post-release commit

charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
=> 1.2.1 post-release commit

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
merge patch commits back to master, bump helm chart version
=> merge patch commits back to master

CHANGELOG-0.x.md, Makefile, docs/README.md
=> v1.3.0 release

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml
=> post-release commit 1.3.0

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
fixes #1066 , but not a bug
complete 1.3.0 release
n/a
=> merge 1.3.0 release and post-release commits into master

examples/kubernetes/windows/README.md
**Is this a bug fix or adding new feature?** csi-proxy v1.0.0 and v1.3.0 of the driver are out .
**What testing is done?**  This example has been manually tested
=> Update windows example for image release

CHANGELOG-0.x.md, Makefile, docs/README.md, examples/kubernetes/windows/README.md
=> release 1.5.0

pkg/driver/node.go
Otherwise, windows complains with: 
```
Nov 15 18:49:27.687: INFO: At 2021-11-15 18:38:41 -0800 PST - event for pod-016f0f0a-924a-4526-a80d-63681a517bfd: {kubelet ip-192-168-30-131.us-west-2.compute.internal} FailedMount: MountVolume.MountDevice failed while expanding volume for volume "pvc-35b4f6a6-f522-410a-869c-4149ed465f15" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = Could not determine device path: executable file not found in %!!(MISSING)P(MISSING)ATH%!!(MISSING)(NOVERB)
```
~~WIP, testing on my windows + migration set up.~~
Now error shows as event on PVC which is better but ideally resize should work on windows too! …
=> Find volume path to expand device path in platform-agnostic way

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/overlays/stable/ecr/kustomization.yaml, deploy/kubernetes/overlays/stable/kustomization.yaml, docs/README.md
/hold
waiting for ECR image promotion
=> [release-1.5] Post-release v1.5.0

charts/aws-ebs-csi-driver/templates/_helpers.tpl, charts/aws-ebs-csi-driver/values.yaml
Add custom labels to metadata for all resources
=> Support for custom labels

Makefile
**Is this a bug fix or adding new feature?** cleanup
=> PHONY make rules

docs/RELEASE.md, hack/release
**What is this PR about? / Why do we need it?** it's a bit too complicated at the moment, I think step-by-step is always clearer.
=> Simplify branch/version part of release process

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
=> Fix the wrong app and helm chart version

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
=> Update ECR sidecars to 1-18-13

CHANGELOG-0.x.md, Makefile, docs/README.md
=> Prepare for release v1.5.1

.github/workflows/release.yaml, CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/README.md
=> Merge release-1.5 to master for v1.5.1

CHANGELOG-0.x.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
Removed external-snapshot-role gain u-necessary access to secrets
=> Update helm charts for a secrect exposure

CHANGELOG-0.x.md, Makefile, docs/README.md
=> prepare for release v1.5.2

docs/TAGGING.md
Doc fix.
Updates TAGGING.md to mention that tagging support will be available from v1.6.0 onwards. 
(Note: as of this PR, v1.6.0 doesn't yet exist). 
=> Updated TAGGING.md to mention minimum version for tagging

CHANGELOG-0.x.md, Makefile, docs/README.md
=> Prepare for release v1.5.3

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/RELEASE.md
=> Driver v1.5.3 post-release

CHANGELOG-0.x.md, Makefile, docs/README.md
=> Prepare for release v1.6.0

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/RELEASE.md, examples/kubernetes/windows/README.md
=> Driver v1.6.0 post-release

CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/README.md, docs/RELEASE.md, examples/kubernetes/windows/README.md
Merge branch release-1.6 to master
=> Release 1.6

.github/workflows/release.yaml, CHANGELOG-0.x.md, Makefile, docs/README.md
- Address CVE ALAS2-2022-1782, ALAS2-2022-1788, ALAS2-2022-1784
=> Prepare for release v1.6.1

.github/workflows/release.yaml, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/RELEASE.md, examples/kubernetes/windows/README.md
=> Driver v1.6.1 post-release

.github/workflows/release.yaml, CHANGELOG-0.x.md, Makefile, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/README.md, docs/RELEASE.md, examples/kubernetes/windows/README.md
Merge release branch to master.
=> Release v1.6.1

CHANGELOG-0.x.md, Makefile, docs/README.md
Prepare for release v1.6.2
Remove deprecated image listing in README.md
=> Prepare for release v1.6.2

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/clusterrole-snapshotter.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/RELEASE.md, examples/kubernetes/windows/README.md
=> Post-release v1.6.2

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
=> Bump up helm chart to v2.6.9

.github/workflows/release.yaml, CHANGELOG.md, Makefile, README.md
=> Prepare for release v1.7.0

.github/workflows/release.yaml, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Post-release v1.7.0

CHANGELOG.md, Dockerfile, Makefile, README.md
Signed-off-by: Eddie Torres [torredil@amazon.com](mailto:torredil@amazon.com)
=> Prepare for release v1.8.0

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Post-release v1.8.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
Signed-off-by: Eddie Torres [torredil@amazon.com](mailto:torredil@amazon.com)
=> Release v1.8.0

charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml
=> Feature: Node affinity

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
- Bump up Helm chart to v2.8.0
=> Bump up Helm chart to v2.8.0

CHANGELOG.md, Makefile, README.md
=> Prepare for release v1.9.0

CHANGELOG.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
- https://github.com/kubernetes/k8s.io/pull/3963
=> Post-release v1.9.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
Signed-off-by: Eddie Torres [torredil@amazon.com](mailto:torredil@amazon.com)
=> Release 1.9.0

pkg/driver/node.go
- Validate file system type before mounting.
- `make test`
=> Validate fs type before mounting

CHANGELOG.md, Makefile, README.md
=> Pre-release v1.10.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md, pkg/cloud/cloud.go, pkg/cloud/devicemanager/allocator.go, pkg/cloud/volume_limits.go, pkg/mounter/safe_mounter_windows.go
Hey I think someone accidentally force-pushed and deleted the merge of #1323, reopened it for you
cc @torredil @gtxu @rdpsin
=> Release 1.10

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
=> Release v1.11.2

docs/example-iam-policy.json, docs/install.md
Doc update
The example policy should include some sensible defaults for encrypted drives to work.
Used the policy to create drives
=> Example policy to support encrypted drives

deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Bug fix
Address deploying from master using v1.10.0 image. Will need a cherry-pick to Release-1.11 
local unit test
=> Update the kustomization deployment to latest image tag

CHANGELOG.md, Makefile, README.md, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
=> Release `v1.11.3`

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
=> Release Helm chart `v2.11.0`

docs/install.md
revise docs
update guidance on EBS CSI IAM Policy, link to AWS docs (where appropriate). 
n/a
=> add link to install guide

CHANGELOG.md, Makefile, README.md, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
=> Release v1.11.4

.github/workflows/trivy.yaml
- Update `trivy.yaml` workflow event trigger; this workflow will run when new changes are pushed to master, and all pull requests.
- Validated behavior on forked repo.
=> Update `trivy.yaml` workflow event trigger

Dockerfile, Makefile
=> Build Windows container for Windows Server 2022 LTSC

CHANGELOG.md, Makefile, README.md, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
=> Release v1.12.0

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
New feature
Fixes #1416 
Manually tested with `helm template`
=> Add parameter to force enable snapshotter sidecar

.github/workflows/unit-tests.yaml
=> Update go version in unit-tests.yaml to 1.19

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
=> Release 1.14.1

Makefile, hack/e2e/run.sh, tests/ct-config.yaml
=> Fix chart testing for CI

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Release v1.15.0

.github/workflows/trivy-containers.yaml
=> Migrate Trivy workflow to grab images from values.yaml

Makefile
=> Remove migration tests

hack/provenance
=> Update speculative execution of docker buildx to check buildkit daemon type

docs/install.md
=> Update installation docs

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
=> Release v1.16.0

README.md
See https://kubernetes.io/blog/2023/03/10/image-registry-redirect/
=> Change README warning to new redirect announcement

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
/hold awaiting image promotion
=> Release v1.17.0

hack/e2e/eksctl.sh, hack/e2e/kops.sh, hack/e2e/run.sh
Bug fix
SSH access is completely unnecessary for CI and introduces a potential flake point.
CI
=> [ANTI-FLAKE] Remove SSH from CI

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
=> Release 1.18.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml, docs/install.md
=> Release 1.18

pkg/driver/mount_linux.go
Bug fix
NodeUnstage/UnpublishVolume should return a success when the path requested has already been unstaged/unpublished.
Manual/CI
=> Check for 'not mounted' in linux Unstage/Unpublish

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go
Bug
Closes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1656
UT
=> Remove check for Throughput

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release PR 1/2 (for real this time)
/cc @hanyuel
=> Release v1.21.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Push release to master, thereby officially releasing v1.21.0
The diff in this PR should be an exact duplicate of #1680
/cc @hanyuel
=> Release 1.21

charts/aws-ebs-csi-driver/CHANGELOG.md
Docs-only changes
Fixes mistake in the Helm CHANGELOG made during the v1.21.0 release
N/A (docs only change)
=> Fixup v2.20.0/v2.21.0 Helm CHANGELOG (master branch)

charts/aws-ebs-csi-driver/CHANGELOG.md
Docs-only changes
Fixes mistake in the Helm CHANGELOG made during the v1.21.0 release
N/A (docs only change)
=> Fixup v2.20.0/v2.21.0 Helm CHANGELOG (release-1.21 branch)

Makefile, hack/e2e/metrics/cl2-config.yaml, hack/e2e/metrics/deployment.yaml, hack/e2e/metrics/metrics.sh, hack/e2e/metrics/override.yaml, hack/e2e/metrics/pvc.yaml, hack/e2e/metrics/storageclass.yaml, hack/e2e/run.sh
This PR implements a workflow to collect driver deployment time, container resource usage, and volume lifecycle performance during CI runs with the goal of preventing silent regressions over time. At a high level, the metrics collector script:
- Collects driver deployment time, resource usage metrics, and clusterloader2 metrics.
- Configures bucket policy to allow the associated Lambda function to access the bucket.
- Sets a lifecycle policy on the S3 bucket to automatically expire metrics data after 3 days.
- Configures bucket notification to trigger the Lambda function on object creation events.
- Uploads the collected metrics to the S3 bucket.
```
I0612 14:54:08.101590   27309 phase_latency.go:146] …
```
=> Implement performance metrics collector workflow

README.md
=> Fix v1.21.0 image in README (release-1.21)

README.md
=> Fix v1.21.0 image in README (master)

Makefile
=> Fix VERSION in Makefile (release-1.21)

Makefile
=> Fix VERSION in Makefile (master)

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release v1.22.0

go.mod
bug fix
Certain indirect dependencies were v0.0.0 in go.mod which caused some issues when setting up the repository locally. 
`make verify`
=> Fix go.mod indirect versions

charts/aws-ebs-csi-driver/templates/controller.yaml, charts/aws-ebs-csi-driver/values.yaml
=> [release-1.22] Bump volume-modidifer-for-k8s sidecar to 0.1.3

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
Release v1.24.0 upstream
CI 
Checklist:
* Update changelog.md with content from stage 0 of runbook
* readme.md latest version and install table
* Makefile VERSION 
* install.md all occurences of old version
* charts/aws-ebs-csi-driver/Chart.yaml with new version & appVersion 
* charts/aws-ebs-csi-driver/CHANGELOG.md with Helm changelog from stage 0
* Update overlays by running make generate-kustomize
=> Release v1.24.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
Merge release-1.24 post-release commit into master
CI
=> Release 1.24

README.md
bug fix
Our driver only performs an online resize of volumes. 
N/A
=> Correct 'Volume Resizing' feature in README.md

Dockerfile, Makefile, charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/templates/_node.tpl, charts/aws-ebs-csi-driver/templates/node-windows.yaml, charts/aws-ebs-csi-driver/templates/node.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/node.yaml, hack/e2e/ecr.sh
=> [cherry-pick release-1.24] Add compatibility workaround for A1 instance family

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
Release
Release aws-ebs-csi-driver v1.23.2
`make verify`
=> Release aws-ebs-csi-driver v1.23.2

pkg/cloud/cloud.go
=> bug hunting part 1

charts/aws-ebs-csi-driver/values.yaml
fixes #1803 
Documenting required annotations in the form of comments in values.yaml
No testing needed
=> Suggest eks.amazonaws.com/role-arn in values.yaml if EKS IAM for SA is used

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
Release
Releases aws-ebs-csi-driver v1.26.1 by updating manifests and documentation. 
CI
=> Release aws-ebs-csi-driver v1.26.1

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release v1.27.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md, hack/e2e/metrics/metrics.sh
Release
Merges v1.27.0 release into master. 
Closes #1896 
CI
=> Release 1.27.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release 1.28.0

Dockerfile, go.mod, hack/cluster-debugging-scripts/go.mod
Dependencies
Upgrade to [Go 1.22](https://tip.golang.org/doc/go1.22). Confirm no regressions. 
CI
=> Upgrade to go v1.22

examples/kubernetes/modify-volume/README.md
bug
Fix link in Volume Modification example docs
=> Fix link in Volume Modification example docs

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
Releases aws-ebs-csi-driver v1.29.0
CI
=> Release aws-ebs-csi-driver v1.29.0

charts/aws-ebs-csi-driver/Chart.yaml
=> Bump helm chart version to v2.29.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release v1.29.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/NOTES.txt, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml
=> Release v1.29.1

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/NOTES.txt, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md, hack/e2e/ecr.sh, hack/prow.sh
=> Release aws-ebs-csi-driver v1.29.1 and helm chart v2.29.1

pkg/cloud/cloud.go
Bug Fix
Corrects DeleteSnapshot error message
CI
=> Fix DeleteSnapshot error message

docs/faq.md
=> Add IMDSv2 support to FAQ

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release driver v1.30.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release 1.30

charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Bug fix
See title
CI/manual
/cc @torredil 
=> Auto-discover cluster version in Helm test pod

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
```
make verify && make test
```
=> Release v1.31.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release 1.31

go.mod
=> Bump go to 1.22.4 to make govulncheck happy

docs/faq.md
Docs
Add tolerateAllTaints advice to Karpenter FAQ so that customers have a workaround until this issue is fixed in Karpenter.
N/A
=> Add tolerateAllTaints advice to Karpenter FAQ

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release v1.32.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Finalize Release 1.32

CHANGELOG.md, hack/e2e/config.sh, hack/tools/install.sh
=> [release-1.32] Add topology label warning to changelog; Backout kops to 1.29

go.mod
=> Bump go version to fix govulncheck failure

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Finalize Release v1.33.0

pkg/cloud/volume_limits.go
Nether fixes typo in comments
This PR fixes some typos in volume_limits.go comments
Passed over volume_limits.go with Code Spell Checker extension installed.
=> Fix spelling errors in volume_limits.go comments

.github/workflows/helm-chart-release.yaml, .github/workflows/release.yaml
=> Fix github action CI permissions

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Releases aws-ebs-csi-driver v1.34.0
Please confirm Makefile, README.md, install.md, kustomize overlays, charts/aws-ebs-csi-driver/Chart.yaml all updated correctly
CI
=> Release aws-ebs-csi-driver v1.34.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
=> Release v1.34.0

charts/aws-ebs-csi-driver/templates/controller.yaml
Identical redo of #2114
/approve
/cc @torredil
=> Auto-enable VAC on clusters with beta API version

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
This PR is for the upstream release of aws-ebs-csi-driver v1.35.0
CI
=> Release aws-ebs-csi-driver v1.35.0

docs/example-iam-policy.json, hack/e2e/kops/patch-cluster.yaml
**NOTE: The docs are intentionally not changed in this PR, an announcement will be PRed separately.**
"Bug fix"
Updates the example policy (and kops policy) to account for the upcoming IAM changes to restoring snapshots during `CreateVolume`. Also includes a minor sync of the policy in the kops node to fix deviations from the example.
Manual/CI
=> Update example policy for IAM change

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
Release EBS CSI Driver v1.36.0
CI
=> Release EBS CSI Driver v1.36.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
This PR releases EBS CSI Driver v1.37.0.
=> Release 1.37

charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
/kind feature
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2241
```release-note
Render templated controller service account parameters
```
=> Add tpl to serviceAccount annotations

charts/aws-ebs-csi-driver/values.yaml
BUG
Remove duplicate 'enableMetrics' key
NONE
```release-note
Remove duplicate 'enableMetrics' key
```
=> Remove duplicate 'enableMetrics' key

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Finalizes release
CI
```release-note
NONE
```
=> Finalize Release 1.38

docs/modify-volume.md
Update volume modification example 6-hour cooldown note to explicitly mention that it doesn't apply to tag-only modification. 
```release-note
Note that tags-only modification does not lead to 6-hour modification cooldown period. 
```
=> Update volume modification example 6 hour cooldown note

Makefile
/kind feature
This PR will change make test to also run sanity tests so the CI job will run both unit and sanity tests on all PRs.
Ran make test and verified both unit tests and sanity tests run and pass.
```release-note
NONE
```
=> Change make test to also run sanity tests

examples/kubernetes/README.md, examples/kubernetes/ephemeral-volume/README.md, examples/kubernetes/ephemeral-volume/manifests/pod.yaml, examples/kubernetes/ephemeral-volume/manifests/storageclass.yaml
Add EBS-backed Ephemeral Volume example to documentation to better support users like those in #1964. 
Worked through example
```release-note
Add EBS-backed Generic Ephemeral Volume example
```
=> Add EBS-backed Ephemeral Volume example to documentation

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/_node.tpl
Cherry-pick of #2311
```release-note
NONE
```
=> [Cherry-pick release-1.39]: Release Helm Chart v2.39.1

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/templates/node.yaml
See #2316 
```release-note
NONE
```
=> [Cherry-pick release-1.39] Fix helm regression with a1CompatibilityDaemonSet & Release chart v2.39.2

charts/aws-ebs-csi-driver/templates/_node-windows.tpl, charts/aws-ebs-csi-driver/values.schema.json, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/node-windows.yaml
/kind cleanup
Fix some of the differences between the helm chart and our values.schema.json file
Manually auditing both  and then running `make update && make verify && make test ` as well as `helm lint`
```release-note
Reconcile some differences between helm chart and values.schema.json
```
=> Reconcile some differences between helm chart and values.schema.json

docs/modify-volume.md
Update volume modification doc with correct VolumeAttributesClass link to k8s doc
```release-note
```
=> Update volume modification doc with correct VolumeAttributesClass link to k8s doc

examples/kubernetes/modify-volume/README.md
=> Update modify-volume example to fix syntax typo

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Merge release branch into master 
CI 
```release-note
NONE
```
=> Merge Release 1.40 branch into master

CHANGELOG.md, charts/aws-ebs-csi-driver/CHANGELOG.md
/kind documentation 
Add the String Interpolation change to 1.40 change log
N/A doc change 
```release-note
NONE
```
=> Update changelog to include String Interpolation and enableWindows

CHANGELOG.md, charts/aws-ebs-csi-driver/CHANGELOG.md
/documentation
Cherry pick `57c7be7773810ac39209b8828a988e63b251b1e5` to release branch to update changelog
N/A docs change
```release-note
NONE
```
=> cherry-pick Update changelog to include String Interpolation and enableWindows

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
This PR releases helm chart version 2.40.1 
CI and manuel testing 
```release-note
NONE
```
=> Release helm chart 2.40.1

go.mod, go.sum, pkg/cloud/handlers.go
See #2355
```release-note
Add error code as a label to the aws_ebs_csi_api_request_errors_total
```
=> Cherry-pick release-1.40: Add error code as a label to the aws_ebs_csi_api_request_errors_total

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Release helm v2.40.3
```release-note
NONE
```
=> Release helm v2.40.3

hack/tools/install.sh
/kind cleanup
Today, several CI runs are failing because of goproxy issues with kops. We originally decided to always install via commit for simplicity/consistency, but given this impact on CI, instead install via binary when possible with commit as override.
Manually/CI
```release-note
NONE
```
=> Add binary-based kops installation, retain commit as override

pkg/driver/node.go
Saw this in my driver logs today. Lets fix it. 
N/A
```release-note
NONE
```
=> chore: fix typo

SECURITY_CONTACTS
See #2427 
```release-note
NONE
```
=> Add Elijah to Security Contacts

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
This PR releases EBS CSI Driver v1.42.0
=> Release EBS CSI Driver v1.42.0 & Helm Chart v2.42.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release v1.42.0 of the ebs-csi-driver
CI and scale tests
```release-note
NONE
```
=> Release 1.42

hack/e2e/eksctl/cluster.yaml
/kind cleanup
Add a comment to `cluster.yaml` clarifying disabling IMDS on eksctl clusters is intentional 
N/A
```release-note
NONE
```
=> Add comment clarifying disabling IMDS on eksctl clusters is intentional

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release.
```release-note
NONE
```
=> Release aws-ebs-csi-driver v1.43.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release.
```release-note
NONE
```
=> Release 1.43

examples/kubernetes/windows/README.md, examples/kubernetes/windows/manifests/windows.yaml
Windows example is broken.
Smaller [nanoserver image](https://hub.docker.com/r/microsoft/windows-nanoserver) wasn't working, so for now using `ltsc2022`. 
Run through windows example after creating windows cluster
```release-note
NONE
```
=> Fix windows example

.github/dependabot.yaml
/kind cleanup
Fixes some minor inconsistencies in `dependabot.yaml` by formatting it with `yq`
N/A
```release-note
NONE
```
=> Foramt dependabot.yaml with yq for consistency

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md, hack/ebs-scale-test/helpers/cluster-setup/scale-cluster-config.yaml
Release aws-ebs-csi-driver v1.45.0
```release-note
NONE
```
=> Release aws-ebs-csi-driver v1.45.0

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md, hack/ebs-scale-test/helpers/cluster-setup/scale-cluster-config.yaml
=> Release 1.45

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, charts/aws-ebs-csi-driver/values.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml
/kind cleanup
```release-note
NONE
```
=> Release helm chart v2.45.1

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, pkg/driver/controller.go, pkg/driver/controller_modify_volume.go, pkg/driver/controller_test.go
/kind feature
This PR ensures that the RESOURCE_EXHAUSTED gRPC error code is returned when the user exceeds their AWS quotas for Storage, IOPS, and/or number of snapshots. 
Ran `make update && make verify`, `make e2e/external`, `make test`, as well as a manual test results [here](https://gist.github.com/mdzraf/819e00c53b43fe09df7e72efc4fe6527)
```release-note
Return RESOURCE_EXHAUSTED gRPC error code when AWS quotas are exceeded
```
=> Return Resource Exhausted When Exceeding Quotas

hack/cloudbuild.sh
/kind cleanup
Bumps buildkit dependency which might be impacting release builds
N/A
```release-note
NONE
```
=> Bump moby/buildkit image to v0.23.2

.github/workflows/helm-chart-release.yaml, CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
Release
CI
```release-note
NONE
```
=> Release v1.48.0

hack/e2e/run.sh
/kind cleanup
This PR adds a check that will fail any e2e test runs that have any individual driver or sidecar container restart more than 3 times as this is unusual. Based on the few test runs that were done, 0 restarts were seen across the board, hence why it was decided that 3 restarts would be a good starting point. 
Had e2e tests ran with modified version of driver that would make it so that the containers would restart multiple times and seeing whether the test properly passed/failed.
```release-note
NONE
```
=> Adding Check to Fail Test For Unusual # of Restarts

charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml
Releases Helm chart
N/A
```release-note
NONE
```
=> Relase Helm Chart v2.49.1

pkg/cloud/cloud.go, pkg/cloud/cloud_test.go, tests/e2e/requires_aws_api.go
/kind feature
This PR adds functionality to retrieve and temporarily cache the maximum IOPS limit for volume types from the error message of a CreateVolume DryRun instead of using a hardcoded table. The driver will default to the hardcoded table if retrieving from the error fails.
Added Unit tests, ran existing ones, and tested manually.
For manual test I created a few PVCs, in the same AZ and added logging code that would show me what the max IOPS limit was set to before IOPS capping and whether it had to make the DryRun call again or if it was going to properly hit the cache if the entry already existed. 
```release-note
Retrieve maximum IOPS limit dynamically via `CreateVolume` dry-run to support increased IOPS limits for GP3 and other volume types
```
=> Refactor To Get  Maximum IOPS for Capping Through Error Message

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml, docs/install.md
This PR releases v1.50.0 of the EBS CSI Driver
```release-note
NONE
```
=> Release v1.50.0

docs/outposts.md, docs/parameters.md
This PR adds documentation for using the AWS EBS CSI Driver on outpost
Doc
```release-note
NONE
```
=> Update docs to include updated Outpost information

CHANGELOG.md, Makefile, README.md, charts/aws-ebs-csi-driver/CHANGELOG.md, charts/aws-ebs-csi-driver/Chart.yaml, deploy/kubernetes/base/controller.yaml, deploy/kubernetes/base/node-windows.yaml, deploy/kubernetes/base/node.yaml
Releasing v1.49.1
```release-note
NONE
```
=> Release v1.49.1
